// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/parameters/base/parameterList.proto

package com.parameters;

public final class ParameterListProto {
  private ParameterListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_parameters_ParameterList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_parameters_ParameterList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*schema/parameters/base/parameterList.p" +
      "roto\022\nparameters\032\024gogoproto/gogo.proto\032&" +
      "schema/parameters/base/parameter.proto\"L" +
      "\n\rParameterList\0225\n\nparameters\030\001 \003(\0132\025.pa" +
      "rameters.ParameterR\nparameters:\004\210\240\037\000B\243\001\n" +
      "\016com.parametersB\022ParameterListProtoP\001Z5g" +
      "ithub.com/AssetMantle/modules/schema/par" +
      "ameters/base\242\002\003PXX\252\002\nParameters\312\002\nParame" +
      "ters\342\002\026Parameters\\GPBMetadata\352\002\nParamete" +
      "rsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.parameters.ParameterProto.getDescriptor(),
        });
    internal_static_parameters_ParameterList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_parameters_ParameterList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_parameters_ParameterList_descriptor,
        new java.lang.String[] { "Parameters", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.parameters.ParameterProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
