// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/cancel/message.proto

package com.orders.transactions.cancel;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_cancel_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_cancel_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/orders/internal/transactions/c" +
      "ancel/message.proto\022\032orders.transactions" +
      ".cancel\032 schema/ids/base/identityID.prot" +
      "o\032\035schema/ids/base/orderID.proto\"r\n\007Mess" +
      "age\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_i_d\030\002 \001(" +
      "\0132\017.ids.IdentityIDR\006fromID\022(\n\torder_i_d\030" +
      "\003 \001(\0132\014.ids.OrderIDR\007orderIDB\204\002\n\036com.ord" +
      "ers.transactions.cancelB\014MessageProtoP\001Z" +
      "Jgithub.com/AssetMantle/modules/modules/" +
      "orders/internal/transactions/cancel\242\002\003OT" +
      "C\252\002\032Orders.Transactions.Cancel\312\002\032Orders\\" +
      "Transactions\\Cancel\342\002&Orders\\Transaction" +
      "s\\Cancel\\GPBMetadata\352\002\034Orders::Transacti" +
      "ons::Cancelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.OrderIDProto.getDescriptor(),
        });
    internal_static_orders_transactions_cancel_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_cancel_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_cancel_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "OrderID", });
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.OrderIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
