// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/cancel/transactionResponse.proto

package com.orders.transactions.cancel;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_cancel_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_cancel_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEmodules/orders/internal/transactions/c" +
      "ancel/transactionResponse.proto\022\032orders." +
      "transactions.cancel\"\025\n\023TransactionRespon" +
      "seB\220\002\n\036com.orders.transactions.cancelB\030T" +
      "ransactionResponseProtoP\001ZJgithub.com/As" +
      "setMantle/modules/modules/orders/interna" +
      "l/transactions/cancel\242\002\003OTC\252\002\032Orders.Tra" +
      "nsactions.Cancel\312\002\032Orders\\Transactions\\C" +
      "ancel\342\002&Orders\\Transactions\\Cancel\\GPBMe" +
      "tadata\352\002\034Orders::Transactions::Cancelb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_cancel_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_cancel_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_cancel_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
