// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/key/key.proto

package com.orders;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%modules/orders/internal/key/key.proto\022" +
      "\006orders\032\035schema/ids/base/orderID.proto\"/" +
      "\n\003Key\022(\n\torder_i_d\030\001 \001(\0132\014.ids.OrderIDR\007" +
      "orderIDB\212\001\n\ncom.ordersB\010KeyProtoP\001Z:gith" +
      "ub.com/AssetMantle/modules/modules/order" +
      "s/internal/key\242\002\003OXX\252\002\006Orders\312\002\006Orders\342\002" +
      "\022Orders\\GPBMetadata\352\002\006Ordersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.OrderIDProto.getDescriptor(),
        });
    internal_static_orders_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_Key_descriptor,
        new java.lang.String[] { "OrderID", });
    com.ids.OrderIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
