// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/mappable/mappable.proto

package com.orders;

public final class MappableProto {
  private MappableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_Mappable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_Mappable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/modules/orders/internal/mappable/mappa" +
      "ble.proto\022\006orders\032$schema/documents/base" +
      "/document.proto\"5\n\010Mappable\022)\n\005order\030\001 \001" +
      "(\0132\023.documents.DocumentR\005orderB\224\001\n\ncom.o" +
      "rdersB\rMappableProtoP\001Z?github.com/Asset" +
      "Mantle/modules/modules/orders/internal/m" +
      "appable\242\002\003OXX\252\002\006Orders\312\002\006Orders\342\002\022Orders" +
      "\\GPBMetadata\352\002\006Ordersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.documents.DocumentProto.getDescriptor(),
        });
    internal_static_orders_Mappable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_Mappable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_Mappable_descriptor,
        new java.lang.String[] { "Order", });
    com.documents.DocumentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
