// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/qualified/base/immutables.proto

package com.qualified;

public final class ImmutablesProto {
  private ImmutablesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qualified_Immutables_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qualified_Immutables_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&schema/qualified/base/immutables.proto" +
      "\022\tqualified\032$schema/lists/base/propertyL" +
      "ist.proto\032\024gogoproto/gogo.proto\"L\n\nImmut" +
      "ables\0228\n\rproperty_list\030\001 \001(\0132\023.lists.Pro" +
      "pertyListR\014propertyList:\004\210\240\037\000B\232\001\n\rcom.qu" +
      "alifiedB\017ImmutablesProtoP\001Z4github.com/A" +
      "ssetMantle/modules/schema/qualified/base" +
      "\242\002\003QXX\252\002\tQualified\312\002\tQualified\342\002\025Qualifi" +
      "ed\\GPBMetadata\352\002\tQualifiedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lists.PropertyListProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_qualified_Immutables_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qualified_Immutables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qualified_Immutables_descriptor,
        new java.lang.String[] { "PropertyList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.lists.PropertyListProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
