// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/qualified/base/mutables.proto

package com.qualified;

public final class MutablesProto {
  private MutablesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qualified_Mutables_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qualified_Mutables_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$schema/qualified/base/mutables.proto\022\t" +
      "qualified\032$schema/lists/base/propertyLis" +
      "t.proto\032\024gogoproto/gogo.proto\"J\n\010Mutable" +
      "s\0228\n\rproperty_list\030\001 \001(\0132\023.lists.Propert" +
      "yListR\014propertyList:\004\210\240\037\000B\230\001\n\rcom.qualif" +
      "iedB\rMutablesProtoP\001Z4github.com/AssetMa" +
      "ntle/modules/schema/qualified/base\242\002\003QXX" +
      "\252\002\tQualified\312\002\tQualified\342\002\025Qualified\\GPB" +
      "Metadata\352\002\tQualifiedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lists.PropertyListProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_qualified_Mutables_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qualified_Mutables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qualified_Mutables_descriptor,
        new java.lang.String[] { "PropertyList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.lists.PropertyListProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
