// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/genesis/genesis.proto

package com.splits;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-modules/splits/internal/genesis/genesi" +
      "s.proto\022\006splits\032\024gogoproto/gogo.proto\032/m" +
      "odules/splits/internal/mappable/mappable" +
      ".proto\032*schema/parameters/base/parameter" +
      "List.proto\"\200\001\n\007Genesis\022.\n\tmappables\030\001 \003(" +
      "\0132\020.splits.MappableR\tmappables\022?\n\rparame" +
      "terList\030\002 \001(\0132\031.parameters.ParameterList" +
      "R\rparameterList:\004\210\240\037\000B\222\001\n\ncom.splitsB\014Ge" +
      "nesisProtoP\001Z>github.com/AssetMantle/mod" +
      "ules/modules/splits/internal/genesis\242\002\003S" +
      "XX\252\002\006Splits\312\002\006Splits\342\002\022Splits\\GPBMetadat" +
      "a\352\002\006Splitsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.splits.MappableProto.getDescriptor(),
          com.parameters.ParameterListProto.getDescriptor(),
        });
    internal_static_splits_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "ParameterList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.splits.MappableProto.getDescriptor();
    com.parameters.ParameterListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
