// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/key/key.proto

package com.splits;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%modules/splits/internal/key/key.proto\022" +
      "\006splits\032\035schema/ids/base/splitID.proto\"/" +
      "\n\003Key\022(\n\tsplit_i_d\030\001 \001(\0132\014.ids.SplitIDR\007" +
      "splitIDB\212\001\n\ncom.splitsB\010KeyProtoP\001Z:gith" +
      "ub.com/AssetMantle/modules/modules/split" +
      "s/internal/key\242\002\003SXX\252\002\006Splits\312\002\006Splits\342\002" +
      "\022Splits\\GPBMetadata\352\002\006Splitsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.SplitIDProto.getDescriptor(),
        });
    internal_static_splits_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_Key_descriptor,
        new java.lang.String[] { "SplitID", });
    com.ids.SplitIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
