// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/mappable/mappable.proto

package com.splits;

public final class MappableProto {
  private MappableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_Mappable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_Mappable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/modules/splits/internal/mappable/mappa" +
      "ble.proto\022\006splits\032\035schema/types/base/spl" +
      "it.proto\".\n\010Mappable\022\"\n\005split\030\001 \001(\0132\014.ty" +
      "pes.SplitR\005splitB\224\001\n\ncom.splitsB\rMappabl" +
      "eProtoP\001Z?github.com/AssetMantle/modules" +
      "/modules/splits/internal/mappable\242\002\003SXX\252" +
      "\002\006Splits\312\002\006Splits\342\002\022Splits\\GPBMetadata\352\002" +
      "\006Splitsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.types.SplitProto.getDescriptor(),
        });
    internal_static_splits_Mappable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_Mappable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_Mappable_descriptor,
        new java.lang.String[] { "Split", });
    com.types.SplitProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
