// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/properties/base/anyProperty.proto

package com.properties;

public final class AnyPropertyProto {
  private AnyPropertyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_properties_AnyProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_properties_AnyProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(schema/properties/base/anyProperty.pro" +
      "to\022\nproperties\032)schema/properties/base/m" +
      "esaProperty.proto\032)schema/properties/bas" +
      "e/metaProperty.proto\032\024gogoproto/gogo.pro" +
      "to\"\235\001\n\013AnyProperty\022?\n\rmesa_property\030\001 \001(" +
      "\0132\030.properties.MesaPropertyH\000R\014mesaPrope" +
      "rty\022?\n\rmeta_property\030\002 \001(\0132\030.properties." +
      "MetaPropertyH\000R\014metaProperty:\004\210\240\037\000B\006\n\004im" +
      "plB\241\001\n\016com.propertiesB\020AnyPropertyProtoP" +
      "\001Z5github.com/AssetMantle/modules/schema" +
      "/properties/base\242\002\003PXX\252\002\nProperties\312\002\nPr" +
      "operties\342\002\026Properties\\GPBMetadata\352\002\nProp" +
      "ertiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.properties.MesaPropertyProto.getDescriptor(),
          com.properties.MetaPropertyProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_properties_AnyProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_properties_AnyProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_properties_AnyProperty_descriptor,
        new java.lang.String[] { "MesaProperty", "MetaProperty", "Impl", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.properties.MesaPropertyProto.getDescriptor();
    com.properties.MetaPropertyProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
