// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/properties/base/mesaProperty.proto

package com.properties;

public final class MesaPropertyProto {
  private MesaPropertyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_properties_MesaProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_properties_MesaProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)schema/properties/base/mesaProperty.pr" +
      "oto\022\nproperties\032 schema/ids/base/propert" +
      "yID.proto\032\034schema/ids/base/dataID.proto\032" +
      "\024gogoproto/gogo.proto\"]\n\014MesaProperty\022 \n" +
      "\003i_d\030\001 \001(\0132\017.ids.PropertyIDR\002iD\022%\n\010data_" +
      "i_d\030\002 \001(\0132\013.ids.DataIDR\006dataID:\004\210\240\037\000B\242\001\n" +
      "\016com.propertiesB\021MesaPropertyProtoP\001Z5gi" +
      "thub.com/AssetMantle/modules/schema/prop" +
      "erties/base\242\002\003PXX\252\002\nProperties\312\002\nPropert" +
      "ies\342\002\026Properties\\GPBMetadata\352\002\nPropertie" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.PropertyIDProto.getDescriptor(),
          com.ids.DataIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_properties_MesaProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_properties_MesaProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_properties_MesaProperty_descriptor,
        new java.lang.String[] { "ID", "DataID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.PropertyIDProto.getDescriptor();
    com.ids.DataIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
