// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/properties/base/metaProperty.proto

package com.properties;

public final class MetaPropertyProto {
  private MetaPropertyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_properties_MetaProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_properties_MetaProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)schema/properties/base/metaProperty.pr" +
      "oto\022\nproperties\032\024gogoproto/gogo.proto\032\036s" +
      "chema/data/base/anyData.proto\032 schema/id" +
      "s/base/propertyID.proto\"Y\n\014MetaProperty\022" +
      " \n\003i_d\030\001 \001(\0132\017.ids.PropertyIDR\002iD\022!\n\004dat" +
      "a\030\002 \001(\0132\r.data.AnyDataR\004data:\004\210\240\037\000B\242\001\n\016c" +
      "om.propertiesB\021MetaPropertyProtoP\001Z5gith" +
      "ub.com/AssetMantle/modules/schema/proper" +
      "ties/base\242\002\003PXX\252\002\nProperties\312\002\nPropertie" +
      "s\342\002\026Properties\\GPBMetadata\352\002\nPropertiesb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.data.AnyDataProto.getDescriptor(),
          com.ids.PropertyIDProto.getDescriptor(),
        });
    internal_static_properties_MetaProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_properties_MetaProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_properties_MetaProperty_descriptor,
        new java.lang.String[] { "ID", "Data", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.data.AnyDataProto.getDescriptor();
    com.ids.PropertyIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
