image: ubuntu

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan DEV_SSH_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


deploy:
  script:
  # try to connect to GitLab.com
  - ssh $DEV_SSH_USER@$DEV_SSH_HOST /home/deployment/update_commit.sh