FROM openjdk:11
WORKDIR /opt/docker
COPY target/docker/stage/opt /opt
ARG POSTGRES_HOST
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG WEB_APP_URL
ARG BLOCKCHAIN_HOST
ARG BLOCKCHAIN_REST_PORT
ARG BLOCKCHAIN_ABCI_PORT
ARG ASCENDEX_URL
ARG MAILGUN_USER
ARG MAILGUN_PASSWORD
ARG KEY_STORE_FILE_PATH
ARG KEY_STORE_PASSWORD
ENV ROOT_FILE_PATH = /opt/docker
ENV PLAY_SECRET = ${PLAY_SECRET}
ENV ASCENDEX_URL = ${ASCENDEX_URL}
ENV APPLICATION_FILE = ${APPLICATION_FILE}
ENV POSTGRES_HOST = ${POSTGRES_HOST}
ENV POSTGRES_USER = ${POSTGRES_USER}
ENV POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
ENV POSTGRES_DB = ${POSTGRES_DB}
ENV WEB_APP_URL = ${WEB_APP_URL}
ENV GENESIS_FILE_PATH = /opt/docker/genesis.json
ENV BLOCKCHAIN_HOST = ${BLOCKCHAIN_HOST}
ENV BLOCKCHAIN_REST_PORT = ${BLOCKCHAIN_REST_PORT}
ENV BLOCKCHAIN_ABCI_PORT = ${BLOCKCHAIN_ABCI_PORT}
ENV MAILGUN_USER = ${MAILGUN_USER}
ENV MAILGUN_PASSWORD = ${MAILGUN_PASSWORD}
ENV KEY_STORE_FILE_PATH = ${KEY_STORE_FILE_PATH}
ENV KEY_STORE_PASSWORD = ${KEY_STORE_PASSWORD}
ENTRYPOINT ["/opt/docker/bin/persistenceclient","-Dplay.http.secret.key=${PLAY_SECRET}"]
CMD []