// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/define/message.proto

package com.identities.transactions.define;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_define_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_define_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/identities/internal/transactio" +
      "ns/define/message.proto\022\036identities.tran" +
      "sactions.define\032 schema/ids/base/identit" +
      "yID.proto\032$schema/lists/base/propertyLis" +
      "t.proto\"\362\002\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022" +
      ")\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006from" +
      "ID\022O\n\031immutable_meta_properties\030\003 \001(\0132\023." +
      "lists.PropertyListR\027immutableMetaPropert" +
      "ies\022F\n\024immutable_properties\030\004 \001(\0132\023.list" +
      "s.PropertyListR\023immutableProperties\022K\n\027m" +
      "utable_meta_properties\030\005 \001(\0132\023.lists.Pro" +
      "pertyListR\025mutableMetaProperties\022B\n\022muta" +
      "ble_properties\030\006 \001(\0132\023.lists.PropertyLis" +
      "tR\021mutablePropertiesB\234\002\n\"com.identities." +
      "transactions.defineB\014MessageProtoP\001ZNgit" +
      "hub.com/AssetMantle/modules/modules/iden" +
      "tities/internal/transactions/define\242\002\003IT" +
      "D\252\002\036Identities.Transactions.Define\312\002\036Ide" +
      "ntities\\Transactions\\Define\342\002*Identities" +
      "\\Transactions\\Define\\GPBMetadata\352\002 Ident" +
      "ities::Transactions::Defineb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_identities_transactions_define_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_define_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_define_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
