// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/define/transactionResponse.proto

package com.identities.transactions.define;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_define_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_define_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nImodules/identities/internal/transactio" +
      "ns/define/transactionResponse.proto\022\036ide" +
      "ntities.transactions.define\"C\n\023Transacti" +
      "onResponse\022,\n\022classification_i_d\030\001 \001(\tR\020" +
      "classificationIDB\250\002\n\"com.identities.tran" +
      "sactions.defineB\030TransactionResponseProt" +
      "oP\001ZNgithub.com/AssetMantle/modules/modu" +
      "les/identities/internal/transactions/def" +
      "ine\242\002\003ITD\252\002\036Identities.Transactions.Defi" +
      "ne\312\002\036Identities\\Transactions\\Define\342\002*Id" +
      "entities\\Transactions\\Define\\GPBMetadata" +
      "\352\002 Identities::Transactions::Defineb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_define_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_define_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_define_TransactionResponse_descriptor,
        new java.lang.String[] { "ClassificationID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
