// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/transactions/reveal/message.proto

package com.metas.transactions.reveal;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metas_transactions_reveal_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metas_transactions_reveal_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8modules/metas/internal/transactions/re" +
      "veal/message.proto\022\031metas.transactions.r" +
      "eveal\032\036schema/data/base/anyData.proto\032 s" +
      "chema/ids/base/identityID.proto\"@\n\007Messa" +
      "ge\022\022\n\004from\030\001 \001(\tR\004from\022!\n\004data\030\002 \001(\0132\r.d" +
      "ata.AnyDataR\004dataB\376\001\n\035com.metas.transact" +
      "ions.revealB\014MessageProtoP\001ZIgithub.com/" +
      "AssetMantle/modules/modules/metas/intern" +
      "al/transactions/reveal\242\002\003MTR\252\002\031Metas.Tra" +
      "nsactions.Reveal\312\002\031Metas\\Transactions\\Re" +
      "veal\342\002%Metas\\Transactions\\Reveal\\GPBMeta" +
      "data\352\002\033Metas::Transactions::Revealb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.data.AnyDataProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_metas_transactions_reveal_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metas_transactions_reveal_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metas_transactions_reveal_Message_descriptor,
        new java.lang.String[] { "From", "Data", });
    com.data.AnyDataProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
