// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/transactions/reveal/service.proto

package com.metas.transactions.reveal;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8modules/metas/internal/transactions/re" +
      "veal/service.proto\022\031metas.transactions.r" +
      "eveal\032\034google/api/annotations.proto\0328mod" +
      "ules/metas/internal/transactions/reveal/" +
      "message.proto\032Dmodules/metas/internal/tr" +
      "ansactions/reveal/transactionResponse.pr" +
      "oto2\205\001\n\007Service\022z\n\006Handle\022\".metas.transa" +
      "ctions.reveal.Message\032..metas.transactio" +
      "ns.reveal.TransactionResponse\"\034\202\323\344\223\002\026\"\024/" +
      "mantle/metas/revealB\376\001\n\035com.metas.transa" +
      "ctions.revealB\014ServiceProtoP\001ZIgithub.co" +
      "m/AssetMantle/modules/modules/metas/inte" +
      "rnal/transactions/reveal\242\002\003MTR\252\002\031Metas.T" +
      "ransactions.Reveal\312\002\031Metas\\Transactions\\" +
      "Reveal\342\002%Metas\\Transactions\\Reveal\\GPBMe" +
      "tadata\352\002\033Metas::Transactions::Revealb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.metas.transactions.reveal.MessageProto.getDescriptor(),
          com.metas.transactions.reveal.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.metas.transactions.reveal.MessageProto.getDescriptor();
    com.metas.transactions.reveal.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
