// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/transactions/reveal/transactionResponse.proto

package com.metas.transactions.reveal;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metas_transactions_reveal_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metas_transactions_reveal_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDmodules/metas/internal/transactions/re" +
      "veal/transactionResponse.proto\022\031metas.tr" +
      "ansactions.reveal\"\025\n\023TransactionResponse" +
      "B\212\002\n\035com.metas.transactions.revealB\030Tran" +
      "sactionResponseProtoP\001ZIgithub.com/Asset" +
      "Mantle/modules/modules/metas/internal/tr" +
      "ansactions/reveal\242\002\003MTR\252\002\031Metas.Transact" +
      "ions.Reveal\312\002\031Metas\\Transactions\\Reveal\342" +
      "\002%Metas\\Transactions\\Reveal\\GPBMetadata\352" +
      "\002\033Metas::Transactions::Revealb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_metas_transactions_reveal_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metas_transactions_reveal_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metas_transactions_reveal_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
