// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/revoke/message.proto

package com.identities.transactions.revoke;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_revoke_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_revoke_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/identities/internal/transactio" +
      "ns/revoke/message.proto\022\036identities.tran" +
      "sactions.revoke\032&schema/ids/base/classif" +
      "icationID.proto\032 schema/ids/base/identit" +
      "yID.proto\"\264\001\n\007Message\022\022\n\004from\030\001 \001(\tR\004fro" +
      "m\022)\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fr" +
      "omID\022%\n\006to_i_d\030\003 \001(\0132\017.ids.IdentityIDR\004t" +
      "oID\022C\n\022classification_i_d\030\004 \001(\0132\025.ids.Cl" +
      "assificationIDR\020classificationIDB\234\002\n\"com" +
      ".identities.transactions.revokeB\014Message" +
      "ProtoP\001ZNgithub.com/AssetMantle/modules/" +
      "modules/identities/internal/transactions" +
      "/revoke\242\002\003ITR\252\002\036Identities.Transactions." +
      "Revoke\312\002\036Identities\\Transactions\\Revoke\342" +
      "\002*Identities\\Transactions\\Revoke\\GPBMeta" +
      "data\352\002 Identities::Transactions::Revokeb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_identities_transactions_revoke_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_revoke_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_revoke_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
