// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/revoke/service.proto

package com.identities.transactions.revoke;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/identities/internal/transactio" +
      "ns/revoke/service.proto\022\036identities.tran" +
      "sactions.revoke\032\034google/api/annotations." +
      "proto\032=modules/identities/internal/trans" +
      "actions/revoke/message.proto\032Imodules/id" +
      "entities/internal/transactions/revoke/tr" +
      "ansactionResponse.proto2\225\001\n\007Service\022\211\001\n\006" +
      "Handle\022\'.identities.transactions.revoke." +
      "Message\0323.identities.transactions.revoke" +
      ".TransactionResponse\"!\202\323\344\223\002\033\"\031/mantle/id" +
      "entities/revokeB\234\002\n\"com.identities.trans" +
      "actions.revokeB\014ServiceProtoP\001ZNgithub.c" +
      "om/AssetMantle/modules/modules/identitie" +
      "s/internal/transactions/revoke\242\002\003ITR\252\002\036I" +
      "dentities.Transactions.Revoke\312\002\036Identiti" +
      "es\\Transactions\\Revoke\342\002*Identities\\Tran" +
      "sactions\\Revoke\\GPBMetadata\352\002 Identities" +
      "::Transactions::Revokeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.revoke.MessageProto.getDescriptor(),
          com.identities.transactions.revoke.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.revoke.MessageProto.getDescriptor();
    com.identities.transactions.revoke.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
