// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/revoke/transactionResponse.proto

package com.identities.transactions.revoke;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.transactions.revoke.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
