// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/unprovision/message.proto

package com.identities.transactions.unprovision;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_unprovision_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_unprovision_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBmodules/identities/internal/transactio" +
      "ns/unprovision/message.proto\022#identities" +
      ".transactions.unprovision\032 schema/ids/ba" +
      "se/identityID.proto\"`\n\007Message\022\022\n\004from\030\001" +
      " \001(\tR\004from\022\016\n\002to\030\002 \001(\tR\002to\0221\n\014identity_i" +
      "_d\030\003 \001(\0132\017.ids.IdentityIDR\nidentityIDB\272\002" +
      "\n\'com.identities.transactions.unprovisio" +
      "nB\014MessageProtoP\001ZSgithub.com/AssetMantl" +
      "e/modules/modules/identities/internal/tr" +
      "ansactions/unprovision\242\002\003ITU\252\002#Identitie" +
      "s.Transactions.Unprovision\312\002#Identities\\" +
      "Transactions\\Unprovision\342\002/Identities\\Tr" +
      "ansactions\\Unprovision\\GPBMetadata\352\002%Ide" +
      "ntities::Transactions::Unprovisionb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_identities_transactions_unprovision_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_unprovision_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_unprovision_Message_descriptor,
        new java.lang.String[] { "From", "To", "IdentityID", });
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
