// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/unprovision/service.proto

package com.identities.transactions.unprovision;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBmodules/identities/internal/transactio" +
      "ns/unprovision/service.proto\022#identities" +
      ".transactions.unprovision\032\034google/api/an" +
      "notations.proto\032Bmodules/identities/inte" +
      "rnal/transactions/unprovision/message.pr" +
      "oto\032Nmodules/identities/internal/transac" +
      "tions/unprovision/transactionResponse.pr" +
      "oto2\244\001\n\007Service\022\230\001\n\006Handle\022,.identities." +
      "transactions.unprovision.Message\0328.ident" +
      "ities.transactions.unprovision.Transacti" +
      "onResponse\"&\202\323\344\223\002 \"\036/mantle/identities/u" +
      "nprovisionB\272\002\n\'com.identities.transactio" +
      "ns.unprovisionB\014ServiceProtoP\001ZSgithub.c" +
      "om/AssetMantle/modules/modules/identitie" +
      "s/internal/transactions/unprovision\242\002\003IT" +
      "U\252\002#Identities.Transactions.Unprovision\312" +
      "\002#Identities\\Transactions\\Unprovision\342\002/" +
      "Identities\\Transactions\\Unprovision\\GPBM" +
      "etadata\352\002%Identities::Transactions::Unpr" +
      "ovisionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.unprovision.MessageProto.getDescriptor(),
          com.identities.transactions.unprovision.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.unprovision.MessageProto.getDescriptor();
    com.identities.transactions.unprovision.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
