// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/unprovision/transactionResponse.proto

package com.identities.transactions.unprovision;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_unprovision_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_unprovision_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nNmodules/identities/internal/transactio" +
      "ns/unprovision/transactionResponse.proto" +
      "\022#identities.transactions.unprovision\"\025\n" +
      "\023TransactionResponseB\306\002\n\'com.identities." +
      "transactions.unprovisionB\030TransactionRes" +
      "ponseProtoP\001ZSgithub.com/AssetMantle/mod" +
      "ules/modules/identities/internal/transac" +
      "tions/unprovision\242\002\003ITU\252\002#Identities.Tra" +
      "nsactions.Unprovision\312\002#Identities\\Trans" +
      "actions\\Unprovision\342\002/Identities\\Transac" +
      "tions\\Unprovision\\GPBMetadata\352\002%Identiti" +
      "es::Transactions::Unprovisionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_unprovision_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_unprovision_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_unprovision_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
