// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/lists/base/idList.proto

package com.lists;

public final class IdListProto {
  private IdListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lists_IDList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lists_IDList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036schema/lists/base/idList.proto\022\005lists\032" +
      "\033schema/ids/base/anyID.proto\032\024gogoproto/" +
      "gogo.proto\"4\n\006IDList\022$\n\010i_d_list\030\001 \003(\0132\n" +
      ".ids.AnyIDR\006iDList:\004\210\240\037\000B~\n\tcom.listsB\013I" +
      "dListProtoP\001Z0github.com/AssetMantle/mod" +
      "ules/schema/lists/base\242\002\003LXX\252\002\005Lists\312\002\005L" +
      "ists\342\002\021Lists\\GPBMetadata\352\002\005Listsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AnyIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_lists_IDList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lists_IDList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lists_IDList_descriptor,
        new java.lang.String[] { "IDList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.AnyIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
