// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/lists/base/propertyList.proto

package com.lists;

public final class PropertyListProto {
  private PropertyListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lists_PropertyList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lists_PropertyList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$schema/lists/base/propertyList.proto\022\005" +
      "lists\032(schema/properties/base/anyPropert" +
      "y.proto\032\024gogoproto/gogo.proto\"M\n\014Propert" +
      "yList\0227\n\nproperties\030\001 \003(\0132\027.properties.A" +
      "nyPropertyR\nproperties:\004\210\240\037\000B\204\001\n\tcom.lis" +
      "tsB\021PropertyListProtoP\001Z0github.com/Asse" +
      "tMantle/modules/schema/lists/base\242\002\003LXX\252" +
      "\002\005Lists\312\002\005Lists\342\002\021Lists\\GPBMetadata\352\002\005Li" +
      "stsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.properties.AnyPropertyProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_lists_PropertyList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lists_PropertyList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lists_PropertyList_descriptor,
        new java.lang.String[] { "Properties", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.properties.AnyPropertyProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
