// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/lists/base/propertyList.proto

package com.lists;

public interface PropertyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lists.PropertyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .properties.AnyProperty properties = 1 [json_name = "properties"];</code>
   */
  java.util.List<com.properties.AnyProperty> 
      getPropertiesList();
  /**
   * <code>repeated .properties.AnyProperty properties = 1 [json_name = "properties"];</code>
   */
  com.properties.AnyProperty getProperties(int index);
  /**
   * <code>repeated .properties.AnyProperty properties = 1 [json_name = "properties"];</code>
   */
  int getPropertiesCount();
  /**
   * <code>repeated .properties.AnyProperty properties = 1 [json_name = "properties"];</code>
   */
  java.util.List<? extends com.properties.AnyPropertyOrBuilder> 
      getPropertiesOrBuilderList();
  /**
   * <code>repeated .properties.AnyProperty properties = 1 [json_name = "properties"];</code>
   */
  com.properties.AnyPropertyOrBuilder getPropertiesOrBuilder(
      int index);
}
