// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/burn/message.proto

package com.assets.transactions.burn;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_burn_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_burn_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/assets/internal/transactions/b" +
      "urn/message.proto\022\030assets.transactions.b" +
      "urn\032 schema/ids/base/identityID.proto\032\035s" +
      "chema/ids/base/assetID.proto\"r\n\007Message\022" +
      "\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_i_d\030\002 \001(\0132\017." +
      "ids.IdentityIDR\006fromID\022(\n\tasset_i_d\030\003 \001(" +
      "\0132\014.ids.AssetIDR\007assetIDB\370\001\n\034com.assets." +
      "transactions.burnB\014MessageProtoP\001ZHgithu" +
      "b.com/AssetMantle/modules/modules/assets" +
      "/internal/transactions/burn\242\002\003ATB\252\002\030Asse" +
      "ts.Transactions.Burn\312\002\030Assets\\Transactio" +
      "ns\\Burn\342\002$Assets\\Transactions\\Burn\\GPBMe" +
      "tadata\352\002\032Assets::Transactions::Burnb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AssetIDProto.getDescriptor(),
        });
    internal_static_assets_transactions_burn_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_burn_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_burn_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "AssetID", });
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AssetIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
