// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/burn/transactionResponse.proto

package com.assets.transactions.burn;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_burn_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_burn_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/assets/internal/transactions/b" +
      "urn/transactionResponse.proto\022\030assets.tr" +
      "ansactions.burn\"\025\n\023TransactionResponseB\204" +
      "\002\n\034com.assets.transactions.burnB\030Transac" +
      "tionResponseProtoP\001ZHgithub.com/AssetMan" +
      "tle/modules/modules/assets/internal/tran" +
      "sactions/burn\242\002\003ATB\252\002\030Assets.Transaction" +
      "s.Burn\312\002\030Assets\\Transactions\\Burn\342\002$Asse" +
      "ts\\Transactions\\Burn\\GPBMetadata\352\002\032Asset" +
      "s::Transactions::Burnb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_burn_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_burn_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_burn_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
