// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/genesis/genesis.proto

package com.identities;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1modules/identities/internal/genesis/ge" +
      "nesis.proto\022\nidentities\032\024gogoproto/gogo." +
      "proto\0323modules/identities/internal/mappa" +
      "ble/mappable.proto\032*schema/parameters/ba" +
      "se/parameterList.proto\"\204\001\n\007Genesis\0222\n\tma" +
      "ppables\030\001 \003(\0132\024.identities.MappableR\tmap" +
      "pables\022?\n\rparameterList\030\002 \001(\0132\031.paramete" +
      "rs.ParameterListR\rparameterList:\004\210\240\037\000B\252\001" +
      "\n\016com.identitiesB\014GenesisProtoP\001ZBgithub" +
      ".com/AssetMantle/modules/modules/identit" +
      "ies/internal/genesis\242\002\003IXX\252\002\nIdentities\312" +
      "\002\nIdentities\342\002\026Identities\\GPBMetadata\352\002\n" +
      "Identitiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.identities.MappableProto.getDescriptor(),
          com.parameters.ParameterListProto.getDescriptor(),
        });
    internal_static_identities_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "ParameterList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.identities.MappableProto.getDescriptor();
    com.parameters.ParameterListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
