// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/key/key.proto

package com.identities;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)modules/identities/internal/key/key.pr" +
      "oto\022\nidentities\032 schema/ids/base/identit" +
      "yID.proto\"8\n\003Key\0221\n\014identity_i_d\030\001 \001(\0132\017" +
      ".ids.IdentityIDR\nidentityIDB\242\001\n\016com.iden" +
      "titiesB\010KeyProtoP\001Z>github.com/AssetMant" +
      "le/modules/modules/identities/internal/k" +
      "ey\242\002\003IXX\252\002\nIdentities\312\002\nIdentities\342\002\026Ide" +
      "ntities\\GPBMetadata\352\002\nIdentitiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_identities_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_Key_descriptor,
        new java.lang.String[] { "IdentityID", });
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
