// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/mappable/mappable.proto

package com.identities;

public final class MappableProto {
  private MappableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_Mappable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_Mappable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3modules/identities/internal/mappable/m" +
      "appable.proto\022\nidentities\032$schema/docume" +
      "nts/base/document.proto\";\n\010Mappable\022/\n\010i" +
      "dentity\030\001 \001(\0132\023.documents.DocumentR\010iden" +
      "tityB\254\001\n\016com.identitiesB\rMappableProtoP\001" +
      "ZCgithub.com/AssetMantle/modules/modules" +
      "/identities/internal/mappable\242\002\003IXX\252\002\nId" +
      "entities\312\002\nIdentities\342\002\026Identities\\GPBMe" +
      "tadata\352\002\nIdentitiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.documents.DocumentProto.getDescriptor(),
        });
    internal_static_identities_Mappable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_Mappable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_Mappable_descriptor,
        new java.lang.String[] { "Identity", });
    com.documents.DocumentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
