// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/wrap/message.proto

package com.splits.transactions.wrap;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_wrap_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_wrap_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/splits/internal/transactions/w" +
      "rap/message.proto\022\030splits.transactions.w" +
      "rap\032\036cosmos/base/v1beta1/coin.proto\032\024gog" +
      "oproto/gogo.proto\032 schema/ids/base/ident" +
      "ityID.proto\"\253\001\n\007Message\022\022\n\004from\030\001 \001(\tR\004f" +
      "rom\022)\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006" +
      "fromID\022a\n\005coins\030\003 \003(\0132\031.cosmos.base.v1be" +
      "ta1.CoinB0\310\336\037\000\252\337\037(github.com/cosmos/cosm" +
      "os-sdk/types.CoinsR\005coinsB\370\001\n\034com.splits" +
      ".transactions.wrapB\014MessageProtoP\001ZHgith" +
      "ub.com/AssetMantle/modules/modules/split" +
      "s/internal/transactions/wrap\242\002\003STW\252\002\030Spl" +
      "its.Transactions.Wrap\312\002\030Splits\\Transacti" +
      "ons\\Wrap\342\002$Splits\\Transactions\\Wrap\\GPBM" +
      "etadata\352\002\032Splits::Transactions::Wrapb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cosmos.base.v1beta1.CoinProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_splits_transactions_wrap_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_wrap_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_wrap_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "Coins", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.castrepeated);
    registry.add(com.gogoproto.GogoProto.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.cosmos.base.v1beta1.CoinProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
