// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/wrap/transactionResponse.proto

package com.splits.transactions.wrap;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_wrap_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_wrap_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/splits/internal/transactions/w" +
      "rap/transactionResponse.proto\022\030splits.tr" +
      "ansactions.wrap\"/\n\023TransactionResponse\022\030" +
      "\n\010coin_i_d\030\001 \001(\tR\006coinIDB\204\002\n\034com.splits." +
      "transactions.wrapB\030TransactionResponsePr" +
      "otoP\001ZHgithub.com/AssetMantle/modules/mo" +
      "dules/splits/internal/transactions/wrap\242" +
      "\002\003STW\252\002\030Splits.Transactions.Wrap\312\002\030Split" +
      "s\\Transactions\\Wrap\342\002$Splits\\Transaction" +
      "s\\Wrap\\GPBMetadata\352\002\032Splits::Transaction" +
      "s::Wrapb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_splits_transactions_wrap_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_wrap_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_wrap_TransactionResponse_descriptor,
        new java.lang.String[] { "CoinID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
