// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mint/message.proto

package com.assets.transactions.mint;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_mint_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_mint_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/assets/internal/transactions/m" +
      "int/message.proto\022\030assets.transactions.m" +
      "int\032&schema/ids/base/classificationID.pr" +
      "oto\032 schema/ids/base/identityID.proto\032$s" +
      "chema/lists/base/propertyList.proto\"\336\003\n\007" +
      "Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_i_d\030" +
      "\002 \001(\0132\017.ids.IdentityIDR\006fromID\022%\n\006to_i_d" +
      "\030\003 \001(\0132\017.ids.IdentityIDR\004toID\022C\n\022classif" +
      "ication_i_d\030\004 \001(\0132\025.ids.ClassificationID" +
      "R\020classificationID\022O\n\031immutable_meta_pro" +
      "perties\030\005 \001(\0132\023.lists.PropertyListR\027immu" +
      "tableMetaProperties\022F\n\024immutable_propert" +
      "ies\030\006 \001(\0132\023.lists.PropertyListR\023immutabl" +
      "eProperties\022K\n\027mutable_meta_properties\030\007" +
      " \001(\0132\023.lists.PropertyListR\025mutableMetaPr" +
      "operties\022B\n\022mutable_properties\030\010 \001(\0132\023.l" +
      "ists.PropertyListR\021mutablePropertiesB\370\001\n" +
      "\034com.assets.transactions.mintB\014MessagePr" +
      "otoP\001ZHgithub.com/AssetMantle/modules/mo" +
      "dules/assets/internal/transactions/mint\242" +
      "\002\003ATM\252\002\030Assets.Transactions.Mint\312\002\030Asset" +
      "s\\Transactions\\Mint\342\002$Assets\\Transaction" +
      "s\\Mint\\GPBMetadata\352\002\032Assets::Transaction" +
      "s::Mintb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_assets_transactions_mint_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_mint_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_mint_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
