// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mint/service.proto

package com.assets.transactions.mint;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/assets/internal/transactions/m" +
      "int/service.proto\022\030assets.transactions.m" +
      "int\032\034google/api/annotations.proto\0327modul" +
      "es/assets/internal/transactions/mint/mes" +
      "sage.proto\032Cmodules/assets/internal/tran" +
      "sactions/mint/transactionResponse.proto2" +
      "\202\001\n\007Service\022w\n\006Handle\022!.assets.transacti" +
      "ons.mint.Message\032-.assets.transactions.m" +
      "int.TransactionResponse\"\033\202\323\344\223\002\025\"\023/mantle" +
      "/assets/mintB\370\001\n\034com.assets.transactions" +
      ".mintB\014ServiceProtoP\001ZHgithub.com/AssetM" +
      "antle/modules/modules/assets/internal/tr" +
      "ansactions/mint\242\002\003ATM\252\002\030Assets.Transacti" +
      "ons.Mint\312\002\030Assets\\Transactions\\Mint\342\002$As" +
      "sets\\Transactions\\Mint\\GPBMetadata\352\002\032Ass" +
      "ets::Transactions::Mintb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assets.transactions.mint.MessageProto.getDescriptor(),
          com.assets.transactions.mint.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assets.transactions.mint.MessageProto.getDescriptor();
    com.assets.transactions.mint.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
