// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mint/transactionResponse.proto

package com.assets.transactions.mint;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_mint_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_mint_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/assets/internal/transactions/m" +
      "int/transactionResponse.proto\022\030assets.tr" +
      "ansactions.mint\"1\n\023TransactionResponse\022\032" +
      "\n\tasset_i_d\030\001 \001(\tR\007assetIDB\204\002\n\034com.asset" +
      "s.transactions.mintB\030TransactionResponse" +
      "ProtoP\001ZHgithub.com/AssetMantle/modules/" +
      "modules/assets/internal/transactions/min" +
      "t\242\002\003ATM\252\002\030Assets.Transactions.Mint\312\002\030Ass" +
      "ets\\Transactions\\Mint\342\002$Assets\\Transacti" +
      "ons\\Mint\\GPBMetadata\352\002\032Assets::Transacti" +
      "ons::Mintb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_mint_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_mint_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_mint_TransactionResponse_descriptor,
        new java.lang.String[] { "AssetID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
