// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lists/base/parameter_list.proto

package com.assetmantle.schema.parameters.base;

public final class ParameterListProto {
  private ParameterListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_schema_parameters_base_ParameterList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_schema_parameters_base_ParameterList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037lists/base/parameter_list.proto\022\"asset" +
      "mantle.schema.parameters.base\032\024gogoproto" +
      "/gogo.proto\032\037parameters/base/parameter.p" +
      "roto\"d\n\rParameterList\022M\n\nparameters\030\001 \003(" +
      "\0132-.assetmantle.schema.parameters.base.P" +
      "arameterR\nparameters:\004\210\240\037\000B\225\002\n&com.asset" +
      "mantle.schema.parameters.baseB\022Parameter" +
      "ListProtoP\001Z+github.com/AssetMantle/sche" +
      "ma/go/lists/base\242\002\004ASPB\252\002\"Assetmantle.Sc" +
      "hema.Parameters.Base\312\002\"Assetmantle\\Schem" +
      "a\\Parameters\\Base\342\002.Assetmantle\\Schema\\P" +
      "arameters\\Base\\GPBMetadata\352\002%Assetmantle" +
      "::Schema::Parameters::Baseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.assetmantle.schema.parameters.base.ParameterProto.getDescriptor(),
        });
    internal_static_assetmantle_schema_parameters_base_ParameterList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_schema_parameters_base_ParameterList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_schema_parameters_base_ParameterList_descriptor,
        new java.lang.String[] { "Parameters", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.assetmantle.schema.parameters.base.ParameterProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
