// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/message.proto

package com.orders.transactions.make;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_make_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_make_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/orders/internal/transactions/m" +
      "ake/message.proto\022\030orders.transactions.m" +
      "ake\032&schema/ids/base/classificationID.pr" +
      "oto\032 schema/ids/base/identityID.proto\032\"s" +
      "chema/ids/base/anyOwnableID.proto\032$schem" +
      "a/lists/base/propertyList.proto\032\036schema/" +
      "types/base/height.proto\"\356\005\n\007Message\022\022\n\004f" +
      "rom\030\001 \001(\tR\004from\022)\n\010from_i_d\030\002 \001(\0132\017.ids." +
      "IdentityIDR\006fromID\022C\n\022classification_i_d" +
      "\030\003 \001(\0132\025.ids.ClassificationIDR\020classific" +
      "ationID\022+\n\ttaker_i_d\030\004 \001(\0132\017.ids.Identit" +
      "yIDR\007takerID\022<\n\021maker_ownable_i_d\030\005 \001(\0132" +
      "\021.ids.AnyOwnableIDR\016makerOwnableID\022<\n\021ta" +
      "ker_ownable_i_d\030\006 \001(\0132\021.ids.AnyOwnableID" +
      "R\016takerOwnableID\022,\n\nexpires_in\030\007 \001(\0132\r.t" +
      "ypes.HeightR\texpiresIn\022.\n\023maker_ownable_" +
      "split\030\010 \001(\tR\021makerOwnableSplit\022.\n\023taker_" +
      "ownable_split\030\t \001(\tR\021takerOwnableSplit\022O" +
      "\n\031immutable_meta_properties\030\n \001(\0132\023.list" +
      "s.PropertyListR\027immutableMetaProperties\022" +
      "F\n\024immutable_properties\030\013 \001(\0132\023.lists.Pr" +
      "opertyListR\023immutableProperties\022K\n\027mutab" +
      "le_meta_properties\030\014 \001(\0132\023.lists.Propert" +
      "yListR\025mutableMetaProperties\022B\n\022mutable_" +
      "properties\030\r \001(\0132\023.lists.PropertyListR\021m" +
      "utablePropertiesB\370\001\n\034com.orders.transact" +
      "ions.makeB\014MessageProtoP\001ZHgithub.com/As" +
      "setMantle/modules/modules/orders/interna" +
      "l/transactions/make\242\002\003OTM\252\002\030Orders.Trans" +
      "actions.Make\312\002\030Orders\\Transactions\\Make\342" +
      "\002$Orders\\Transactions\\Make\\GPBMetadata\352\002" +
      "\032Orders::Transactions::Makeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
          com.types.HeightProto.getDescriptor(),
        });
    internal_static_orders_transactions_make_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_make_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_make_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ClassificationID", "TakerID", "MakerOwnableID", "TakerOwnableID", "ExpiresIn", "MakerOwnableSplit", "TakerOwnableSplit", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
    com.types.HeightProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
