// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/service.proto

package com.orders.transactions.make;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/orders/internal/transactions/m" +
      "ake/service.proto\022\030orders.transactions.m" +
      "ake\032\034google/api/annotations.proto\0327modul" +
      "es/orders/internal/transactions/make/mes" +
      "sage.proto\032Cmodules/orders/internal/tran" +
      "sactions/make/transactionResponse.proto2" +
      "\202\001\n\007Service\022w\n\006Handle\022!.orders.transacti" +
      "ons.make.Message\032-.orders.transactions.m" +
      "ake.TransactionResponse\"\033\202\323\344\223\002\025\"\023/mantle" +
      "/orders/makeB\370\001\n\034com.orders.transactions" +
      ".makeB\014ServiceProtoP\001ZHgithub.com/AssetM" +
      "antle/modules/modules/orders/internal/tr" +
      "ansactions/make\242\002\003OTM\252\002\030Orders.Transacti" +
      "ons.Make\312\002\030Orders\\Transactions\\Make\342\002$Or" +
      "ders\\Transactions\\Make\\GPBMetadata\352\002\032Ord" +
      "ers::Transactions::Makeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.orders.transactions.make.MessageProto.getDescriptor(),
          com.orders.transactions.make.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.orders.transactions.make.MessageProto.getDescriptor();
    com.orders.transactions.make.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
