// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/transactionResponse.proto

package com.orders.transactions.make;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.transactions.make.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_i_d = 1 [json_name = "orderID"];</code>
   * @return The orderID.
   */
  java.lang.String getOrderID();
  /**
   * <code>string order_i_d = 1 [json_name = "orderID"];</code>
   * @return The bytes for orderID.
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();
}
