// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/transactionResponse.proto

package com.orders.transactions.make;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_make_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_make_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/orders/internal/transactions/m" +
      "ake/transactionResponse.proto\022\030orders.tr" +
      "ansactions.make\"1\n\023TransactionResponse\022\032" +
      "\n\torder_i_d\030\001 \001(\tR\007orderIDB\204\002\n\034com.order" +
      "s.transactions.makeB\030TransactionResponse" +
      "ProtoP\001ZHgithub.com/AssetMantle/modules/" +
      "modules/orders/internal/transactions/mak" +
      "e\242\002\003OTM\252\002\030Orders.Transactions.Make\312\002\030Ord" +
      "ers\\Transactions\\Make\342\002$Orders\\Transacti" +
      "ons\\Make\\GPBMetadata\352\002\032Orders::Transacti" +
      "ons::Makeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_make_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_make_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_make_TransactionResponse_descriptor,
        new java.lang.String[] { "OrderID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
