// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/data/base/anyData.proto

package com.data;

public final class AnyDataProto {
  private AnyDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_AnyData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_AnyData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036schema/data/base/anyData.proto\022\004data\032\024" +
      "gogoproto/gogo.proto\032%schema/data/base/a" +
      "ccAddressData.proto\032\"schema/data/base/bo" +
      "oleanData.proto\032\036schema/data/base/decDat" +
      "a.proto\032!schema/data/base/heightData.pro" +
      "to\032\035schema/data/base/idData.proto\032!schem" +
      "a/data/base/numberData.proto\032!schema/dat" +
      "a/base/stringData.proto\"\265\003\n\007AnyData\022@\n\020a" +
      "cc_address_data\030\001 \001(\0132\024.data.AccAddressD" +
      "ataH\000R\016accAddressData\0226\n\014boolean_data\030\002 " +
      "\001(\0132\021.data.BooleanDataH\000R\013booleanData\022*\n" +
      "\010dec_data\030\003 \001(\0132\r.data.DecDataH\000R\007decDat" +
      "a\0223\n\013height_data\030\004 \001(\0132\020.data.HeightData" +
      "H\000R\nheightData\022(\n\010i_d_data\030\005 \001(\0132\014.data." +
      "IDDataH\000R\006iDData\022-\n\tlist_data\030\006 \001(\0132\016.da" +
      "ta.ListDataH\000R\010listData\0223\n\013number_data\030\007" +
      " \001(\0132\020.data.NumberDataH\000R\nnumberData\0223\n\013" +
      "string_data\030\010 \001(\0132\020.data.StringDataH\000R\ns" +
      "tringData:\004\210\240\037\000B\006\n\004impl\"<\n\010ListData\022*\n\td" +
      "ata_list\030\001 \003(\0132\r.data.AnyDataR\010dataList:" +
      "\004\210\240\037\000By\n\010com.dataB\014AnyDataProtoP\001Z/githu" +
      "b.com/AssetMantle/modules/schema/data/ba" +
      "se\242\002\003DXX\252\002\004Data\312\002\004Data\342\002\020Data\\GPBMetadat" +
      "a\352\002\004Datab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.data.AccAddressDataProto.getDescriptor(),
          com.data.BooleanDataProto.getDescriptor(),
          com.data.DecDataProto.getDescriptor(),
          com.data.HeightDataProto.getDescriptor(),
          com.data.IdDataProto.getDescriptor(),
          com.data.NumberDataProto.getDescriptor(),
          com.data.StringDataProto.getDescriptor(),
        });
    internal_static_data_AnyData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_AnyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_AnyData_descriptor,
        new java.lang.String[] { "AccAddressData", "BooleanData", "DecData", "HeightData", "IDData", "ListData", "NumberData", "StringData", "Impl", });
    internal_static_data_ListData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_ListData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListData_descriptor,
        new java.lang.String[] { "DataList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.data.AccAddressDataProto.getDescriptor();
    com.data.BooleanDataProto.getDescriptor();
    com.data.DecDataProto.getDescriptor();
    com.data.HeightDataProto.getDescriptor();
    com.data.IdDataProto.getDescriptor();
    com.data.NumberDataProto.getDescriptor();
    com.data.StringDataProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
