// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/data/base/booleanData.proto

package com.data;

public final class BooleanDataProto {
  private BooleanDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_BooleanData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_BooleanData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"schema/data/base/booleanData.proto\022\004da" +
      "ta\032\024gogoproto/gogo.proto\")\n\013BooleanData\022" +
      "\024\n\005value\030\001 \001(\010R\005value:\004\210\240\037\000B}\n\010com.dataB" +
      "\020BooleanDataProtoP\001Z/github.com/AssetMan" +
      "tle/modules/schema/data/base\242\002\003DXX\252\002\004Dat" +
      "a\312\002\004Data\342\002\020Data\\GPBMetadata\352\002\004Datab\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_data_BooleanData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_BooleanData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_BooleanData_descriptor,
        new java.lang.String[] { "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
