// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/data/base/idData.proto

package com.data;

public final class IdDataProto {
  private IdDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_IDData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_IDData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035schema/data/base/idData.proto\022\004data\032\033s" +
      "chema/ids/base/anyID.proto\032\024gogoproto/go" +
      "go.proto\"0\n\006IDData\022 \n\005value\030\001 \001(\0132\n.ids." +
      "AnyIDR\005value:\004\210\240\037\000Bx\n\010com.dataB\013IdDataPr" +
      "otoP\001Z/github.com/AssetMantle/modules/sc" +
      "hema/data/base\242\002\003DXX\252\002\004Data\312\002\004Data\342\002\020Dat" +
      "a\\GPBMetadata\352\002\004Datab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AnyIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_data_IDData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_IDData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_IDData_descriptor,
        new java.lang.String[] { "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.AnyIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
