// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/base/number_data.proto

package com.assetmantle.schema.data.base;

public interface NumberDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.schema.data.base.NumberData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  long getValue();
}
