// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/queries/ownable/queryRequest.proto

package com.splits.queries.ownable;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_queries_ownable_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_queries_ownable_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:modules/splits/internal/queries/ownabl" +
      "e/queryRequest.proto\022\026splits.queries.own" +
      "able\032\"schema/ids/base/anyOwnableID.proto" +
      "\"A\n\014QueryRequest\0221\n\013ownable_i_d\030\001 \001(\0132\021." +
      "ids.AnyOwnableIDR\townableIDB\361\001\n\032com.spli" +
      "ts.queries.ownableB\021QueryRequestProtoP\001Z" +
      "Fgithub.com/AssetMantle/modules/modules/" +
      "splits/internal/queries/ownable\242\002\003SQO\252\002\026" +
      "Splits.Queries.Ownable\312\002\026Splits\\Queries\\" +
      "Ownable\342\002\"Splits\\Queries\\Ownable\\GPBMeta" +
      "data\352\002\030Splits::Queries::Ownableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AnyOwnableIDProto.getDescriptor(),
        });
    internal_static_splits_queries_ownable_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_queries_ownable_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_queries_ownable_QueryRequest_descriptor,
        new java.lang.String[] { "OwnableID", });
    com.ids.AnyOwnableIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
