// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/queries/ownable/queryResponse.proto

package com.splits.queries.ownable;

public final class QueryResponseProto {
  private QueryResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_queries_ownable_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_queries_ownable_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;modules/splits/internal/queries/ownabl" +
      "e/queryResponse.proto\022\026splits.queries.ow" +
      "nable\032\024gogoproto/gogo.proto\"[\n\rQueryResp" +
      "onse\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005error\030" +
      "\002 \001(\tR\005error\022\024\n\005value\030\003 \001(\tR\005value:\004\210\240\037\000" +
      "B\362\001\n\032com.splits.queries.ownableB\022QueryRe" +
      "sponseProtoP\001ZFgithub.com/AssetMantle/mo" +
      "dules/modules/splits/internal/queries/ow" +
      "nable\242\002\003SQO\252\002\026Splits.Queries.Ownable\312\002\026S" +
      "plits\\Queries\\Ownable\342\002\"Splits\\Queries\\O" +
      "wnable\\GPBMetadata\352\002\030Splits::Queries::Ow" +
      "nableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_splits_queries_ownable_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_queries_ownable_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_queries_ownable_QueryResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
