// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/queries/ownable/service.proto

package com.splits.queries.ownable;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5modules/splits/internal/queries/ownabl" +
      "e/service.proto\022\026splits.queries.ownable\032" +
      "\034google/api/annotations.proto\032:modules/s" +
      "plits/internal/queries/ownable/queryRequ" +
      "est.proto\032;modules/splits/internal/queri" +
      "es/ownable/queryResponse.proto2\210\001\n\007Servi" +
      "ce\022}\n\006Handle\022$.splits.queries.ownable.Qu" +
      "eryRequest\032%.splits.queries.ownable.Quer" +
      "yResponse\"&\202\323\344\223\002 \022\036/mantle/splits/v1beta" +
      "1/ownableB\354\001\n\032com.splits.queries.ownable" +
      "B\014ServiceProtoP\001ZFgithub.com/AssetMantle" +
      "/modules/modules/splits/internal/queries" +
      "/ownable\242\002\003SQO\252\002\026Splits.Queries.Ownable\312" +
      "\002\026Splits\\Queries\\Ownable\342\002\"Splits\\Querie" +
      "s\\Ownable\\GPBMetadata\352\002\030Splits::Queries:" +
      ":Ownableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.splits.queries.ownable.QueryRequestProto.getDescriptor(),
          com.splits.queries.ownable.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.splits.queries.ownable.QueryRequestProto.getDescriptor();
    com.splits.queries.ownable.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
