// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/revoke/message.proto

package com.orders.transactions.revoke;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_revoke_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_revoke_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/orders/internal/transactions/r" +
      "evoke/message.proto\022\032orders.transactions" +
      ".revoke\032&schema/ids/base/classificationI" +
      "D.proto\032 schema/ids/base/identityID.prot" +
      "o\"\264\001\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010fro" +
      "m_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromID\022%\n\006" +
      "to_i_d\030\003 \001(\0132\017.ids.IdentityIDR\004toID\022C\n\022c" +
      "lassification_i_d\030\004 \001(\0132\025.ids.Classifica" +
      "tionIDR\020classificationIDB\204\002\n\036com.orders." +
      "transactions.revokeB\014MessageProtoP\001ZJgit" +
      "hub.com/AssetMantle/modules/modules/orde" +
      "rs/internal/transactions/revoke\242\002\003OTR\252\002\032" +
      "Orders.Transactions.Revoke\312\002\032Orders\\Tran" +
      "sactions\\Revoke\342\002&Orders\\Transactions\\Re" +
      "voke\\GPBMetadata\352\002\034Orders::Transactions:" +
      ":Revokeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_orders_transactions_revoke_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_revoke_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_revoke_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
