// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/provision/message.proto

package com.identities.transactions.provision;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_provision_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_provision_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@modules/identities/internal/transactio" +
      "ns/provision/message.proto\022!identities.t" +
      "ransactions.provision\032 schema/ids/base/i" +
      "dentityID.proto\"`\n\007Message\022\022\n\004from\030\001 \001(\t" +
      "R\004from\022\016\n\002to\030\002 \001(\tR\002to\0221\n\014identity_i_d\030\003" +
      " \001(\0132\017.ids.IdentityIDR\nidentityIDB\256\002\n%co" +
      "m.identities.transactions.provisionB\014Mes" +
      "sageProtoP\001ZQgithub.com/AssetMantle/modu" +
      "les/modules/identities/internal/transact" +
      "ions/provision\242\002\003ITP\252\002!Identities.Transa" +
      "ctions.Provision\312\002!Identities\\Transactio" +
      "ns\\Provision\342\002-Identities\\Transactions\\P" +
      "rovision\\GPBMetadata\352\002#Identities::Trans" +
      "actions::Provisionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_identities_transactions_provision_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_provision_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_provision_Message_descriptor,
        new java.lang.String[] { "From", "To", "IdentityID", });
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
