// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/provision/service.proto

package com.identities.transactions.provision;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@modules/identities/internal/transactio" +
      "ns/provision/service.proto\022!identities.t" +
      "ransactions.provision\032\034google/api/annota" +
      "tions.proto\032@modules/identities/internal" +
      "/transactions/provision/message.proto\032Lm" +
      "odules/identities/internal/transactions/" +
      "provision/transactionResponse.proto2\236\001\n\007" +
      "Service\022\222\001\n\006Handle\022*.identities.transact" +
      "ions.provision.Message\0326.identities.tran" +
      "sactions.provision.TransactionResponse\"$" +
      "\202\323\344\223\002\036\"\034/mantle/identities/provisionB\256\002\n" +
      "%com.identities.transactions.provisionB\014" +
      "ServiceProtoP\001ZQgithub.com/AssetMantle/m" +
      "odules/modules/identities/internal/trans" +
      "actions/provision\242\002\003ITP\252\002!Identities.Tra" +
      "nsactions.Provision\312\002!Identities\\Transac" +
      "tions\\Provision\342\002-Identities\\Transaction" +
      "s\\Provision\\GPBMetadata\352\002#Identities::Tr" +
      "ansactions::Provisionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.provision.MessageProto.getDescriptor(),
          com.identities.transactions.provision.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.provision.MessageProto.getDescriptor();
    com.identities.transactions.provision.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
