// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/provision/transactionResponse.proto

package com.identities.transactions.provision;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_provision_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_provision_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nLmodules/identities/internal/transactio" +
      "ns/provision/transactionResponse.proto\022!" +
      "identities.transactions.provision\"\025\n\023Tra" +
      "nsactionResponseB\272\002\n%com.identities.tran" +
      "sactions.provisionB\030TransactionResponseP" +
      "rotoP\001ZQgithub.com/AssetMantle/modules/m" +
      "odules/identities/internal/transactions/" +
      "provision\242\002\003ITP\252\002!Identities.Transaction" +
      "s.Provision\312\002!Identities\\Transactions\\Pr" +
      "ovision\342\002-Identities\\Transactions\\Provis" +
      "ion\\GPBMetadata\352\002#Identities::Transactio" +
      "ns::Provisionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_provision_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_provision_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_provision_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
