package constants

object Actor {

  val ACTOR_NOT_FOUND = "ACTOR_NOT_FOUND"
  val ACTOR_NOT_FOUND_FOR_SHUTDOWN = "ACTOR_NOT_FOUND_FOR_SHUTDOWN"
  val USER_COMET_ACTOR_ADDED_TO_MAP = "USER_COMET_ACTOR_ADDED_TO_MAP"
  val USER_COMET_ACTOR = "USER_COMET_ACTOR"
  val SHUTTING_DOWN_COMET_USER_ACTOR = "SHUTTING_DOWN_COMET_USER_ACTOR"

}
