package constants

import scala.concurrent.duration.DurationInt

object Actor {

  val ACTOR_NOT_FOUND = "ACTOR_NOT_FOUND"
  val ACTOR_NOT_FOUND_FOR_SHUTDOWN = "ACTOR_NOT_FOUND_FOR_SHUTDOWN"

  val ACTOR_BLOCK = "ACTOR_BLOCK"
  val ACTOR_EMAIL = "ACTOR_EMAIL"
  val ACTOR_SMS = "ACTOR_SMS"
  val ACTOR_APP_WEB_SOCKET = "ACTOR_APP_WEB_SOCKET"
  val ACTOR_PUSH_NOTIFICATION = "ACTOR_PUSH_NOTIFICATION"

  val ACTOR_ASK_TIMEOUT = 5 seconds

  val NUMBER_OF_ENTITIES = 100
  val NUMBER_OF_SHARDS = 10

  object MessageType {
    val NEW_BLOCK = "NEW_BLOCK"
    val BLOCKCHAIN_CONNECTION_LOST = "BLOCKCHAIN_CONNECTION_LOST"
    val PRIVATE_MESSAGE = "PRIVATE_MESSAGE"
    val PING = "PING"
    val CHAT = "CHAT"
    val ASSET = "ASSET"
    val TEST = "TEST"
  }

}
