package constants

object Comet {

  val PING = "PING"

  val ERROR = "ERROR"

  //MessageTypes
  val ACCOUNT = "ACCOUNT"
  val ASSET = "ASSET"
  val FIAT = "FIAT"
  val ORDER = "ORDER"
  val NEGOTIATION = "NEGOTIATION"
  val CHAT = "CHAT"
  val KEEP_ALIVE = "KEEP_ALIVE"
  val TRANSACTION_SENT_ENABLE_SPINNER = "TRANSACTION_SENT_ENABLE_SPINNER"
  val TRANSACTION_FAILED_DISABLE_SPINNER="TRANSACTION_FAILED_DISABLE_SPINNER"
}
