package constants

object Common {
  val ALL_BLOCKS = "ALL_BLOCKS"
  val MASTER = "MASTER"
  val BLOCKCHAIN = "BLOCKCHAIN"
  val BLOCKS = "BLOCKS"
  val BLOCK = "BLOCK"
  val NEXT = "NEXT"
  val SEARCH = "SEARCH"
  val PREVIOUS = "PREVIOUS"
  val EVIDENCE = "EVIDENCE"
  val EVIDENCE_HASH = "EVIDENCE_HASH"
  val SEE_ALL = "SEE_ALL"
  val LATEST_BLOCK_HEIGHT = "LATEST_BLOCK_HEIGHT"
  val AVERAGE_BLOCK_TIME = "AVERAGE_BLOCK_TIME"

  val BLOCK_HASH = "BLOCK_HASH"
  val HEIGHT = "HEIGHT"
  val DATA_HASH = "DATA_HASH"
  val TRANSACTION_HASH = "TRANSACTION_HASH"
  val TYPE = "TYPE"
  val TIME = "TIME"
  val NUM_TXS = "NUM_TXS"
  val SEARCH_TX_HASH_HEIGHT = "SEARCH_TX_HASH_HEIGHT"
  val TRANSACTIONS = "TRANSACTIONS"
  val VALIDATORS = "VALIDATORS"
  val VALIDATORS_HASH = "VALIDATORS_HASH"
  val OPERATOR = "OPERATOR"
  val STATUS = "STATUS"
  val TOKENS = "TOKENS"
  val DELEGATOR_SHARES = "DELEGATOR_SHARES"

}
