package constants

object Error {
  val CONNECT_EXCEPTION = "CONNECT_EXCEPTION"
  val NO_SUCH_ELEMENT_EXCEPTION = "NO_SUCH_ELEMENT_EXCEPTION"
  val PSQL_EXCEPTION = "PSQL_EXCEPTION"
  val INVALID_OTP = "INVALID_OTP"
  val MOBILE_NUMBER_NOT_FOUND = "MOBILE_NUMBER_NOT_FOUND"
  val EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
  val NO_RESPONSE = "NO_RESPONSE"
  val NOT_LOGGED_IN = "NOT_LOGGED_IN"
  val INCORRECT_LOG_IN = "INCORRECT_LOG_IN"
}
