package constants

object Error {
  val BASE_EXCEPTION= "BASE_EXCEPTION"
  val CONNECT_EXCEPTION = "CONNECT_EXCEPTION"
  val NO_SUCH_ELEMENT_EXCEPTION = "NO_SUCH_ELEMENT_EXCEPTION"
  val PSQL_EXCEPTION = "PSQL_EXCEPTION"
  val INVALID_OTP = "INVALID_OTP"
  val MOBILE_NUMBER_NOT_FOUND = "MOBILE_NUMBER_NOT_FOUND"
  val EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
  val NO_RESPONSE = "NO_RESPONSE"
  val NOT_LOGGED_IN = "NOT_LOGGED_IN"
  val INCORRECT_LOG_IN = "INCORRECT_LOG_IN"
  val UNVERIFIED_ZONE = "UNVERIFIED_ZONE"
  val UNVERIFIED_ORGANIZATION = "UNVERIFIED_ORGANIZATION"
  val REQUEST_ALREADY_APPROVED_OR_REJECTED = "REQUEST_ALREADY_APPROVED_OR_REJECTED"
  val USERNAME_NOT_FOUND="USERNAME_NOT_FOUND"
  val TOKEN_NOT_FOUND="TOKEN_NOT_FOUND"
  val TOKEN_TIMEOUT= "TOKEN_TIMEOUT"
  val INVALID_TOKEN= "INVALID_TOKEN"
  val UNAUTHORIZED = "UNAUTHORIZED"
}
