package constants

object File {
  val IMAGE = "IMAGES"
  val DOCUMENT = "DOCUMENT"
  val FILE = "FILE"

  val PDF = "pdf"
  val TXT = "txt"
  val JPG = "jpg"
  val PNG = "png"
  val JPEG = "jpeg"
  val DOC = "doc"
  val DOCX = "docx"

  val BANK_DETAILS = "BANK_DETAILS"
  val IDENTIFICATION = "IDENTIFICATION"
  val UNKNOWN_TYPE = "UNKNOWN_TYPE"

  val UPLOAD_USER_GENERIC = "UPLOAD_GENERIC"
  val UPLOAD_USER_ZONE_KYC = "UPLOAD_USER_ZONE_KYC"
  val UPLOAD_USER_ORGANIZATION_KYC = "UPLOAD_USER_ORGANIZATION_KYC"

  val UPLOAD_BANK_DETAILS = "UPLOAD_BANK_DETAILS"
  val UPLOAD_IDENTIFICATION = "UPLOAD_IDENTIFICATION"

  val UPLOAD_ZONE_BANK_DETAILS = "UPLOAD_ZONE_BANK_DETAILS"
  val UPLOAD_ZONE_IDENTIFICATION = "UPLOAD_ZONE_IDENTIFICATION"

  val UPLOAD_ORGANIZATION_BANK_DETAILS = "UPLOAD_ORGANIZATION_BANK_DETAILS"
  val UPLOAD_ORGANIZATION_IDENTIFICATION = "UPLOAD_ORGANIZATION_IDENTIFICATION"
}
