package constants

object File {

  val KEY_FILE = "file"

  val IMAGE = "IMAGES"
  val DOCUMENT = "DOCUMENT"
  val FILE = "FILE"

  val PDF = "pdf"
  val TXT = "txt"
  val JPG = "jpg"
  val PNG = "png"
  val JPEG = "jpeg"
  val DOC = "doc"
  val DOCX = "docx"

  val BANK_DETAILS = "BANK_DETAILS"
  val IDENTIFICATION = "IDENTIFICATION"
  val ADDRESS = "ADDRESS"
  val UNKNOWN_TYPE = "UNKNOWN_TYPE"

  val BANK_ACCOUNT_DETAIL = "BANK_ACCOUNT_DETAIL"
  val LATEST_AUDITED_FINANCIAL_REPORT = "LATEST_AUDITED_FINANCIAL_REPORT"
  val LAST_YEAR_AUDITED_FINANCIAL_REPORT = "LAST_YEAR_AUDITED_FINANCIAL_REPORT"
  val MANAGEMENT = "MANAGEMENT"
  val ACRA = "ACRA"
  val SHARE_STRUCTURE = "SHARE_STRUCTURE"
  val ADMIN_PROFILE_IDENTIFICATION = "ADMIN_PROFILE_IDENTIFICATION"

  val TRADER_IDENTIFICATION = "TRADER_IDENTIFICATION"

  val PROFILE_PICTURE = "PROFILE_PICTURE"

  //Seq
  val ORGANIZATION_KYC_DOCUMENT_TYPES: Seq[String] = Seq(BANK_ACCOUNT_DETAIL, LATEST_AUDITED_FINANCIAL_REPORT, LAST_YEAR_AUDITED_FINANCIAL_REPORT, MANAGEMENT, ACRA, SHARE_STRUCTURE, ADMIN_PROFILE_IDENTIFICATION)
  val TRADER_KYC_DOCUMENT_TYPES: Seq[String] = Seq(TRADER_IDENTIFICATION)
}
