package constants

object Forms {

  val INDEX = "Index"

  //Blockchain
  val ADD_KEY_TITLE = "Add Key"
  val ADD_ZONE_TITLE = "Add Zone"
  val ADD_ORGANIZATION_TITLE = "Add Organization"
  val BUYER_EXECUTE_ORDER_TITLE = "Buyer Execute Order"
  val CHANGE_BUYER_BID_TITLE = "Change Buyer Bid"
  val CHANGE_SELLER_BID_TITLE = "Change Seller Bid"
  val CONFIRM_BUYER_BID_TITLE = "Confirm Buyer Bid"
  val CONFIRM_SELLER_BID_TITLE = "Confirm Seller Bid"
  val ISSUE_ASSET_TITLE = "Issue Asset"
  val ISSUE_FIAT_TITLE = "Issue Fiat"
  val REDEEM_ASSET_TITLE = "Redeem Asset"
  val REDEEM_FIAT_TITLE = "Redeem Fiat"
  val RELEASE_ASSET_TITLE = "Release Asset"
  val SELLER_EXECUTE_ORDER_TITLE = "Seller Execute Order"
  val SEND_ASSET_TITLE = "Send Asset"
  val SEND_COIN_TITLE = "Send Coin"
  val SEND_FIAT_TITLE = "Send Fiat"
  val SET_ACL_TITLE = "Set ACL"
  val SET_BUYER_FEEDBACK_TITLE = "Set Buyer Feedback"
  val SET_SELLER_FEEDBACK_TITLE = "Set Seller Feedback"

  val NAME = "name"
  val SEED = "seed"
  val PASSWORD = "password"
  val FROM = "from"
  val TO = "to"
  val ORGANIZATION_ID = "organizationID"
  val ZONE_ID = "zoneID"
  val BUYER_ADDRESS = "buyerAddress"
  val SELLER_ADDRESS = "sellerAddress"
  val FIAT_PROOF_HASH = "fiatProofHash"
  val PEG_HASH = "pegHash"
  val GAS = "gas"
  val BID = "bid"
  val TIME = "time"
  val DOCUMENT_HASH = "documentHash"
  val ASSET_TYPE = "assetType"
  val ASSET_PRICE = "assetPrice"
  val QUANTITY_UNIT = "quantityUnit"
  val ASSET_QUANTITY = "assetQuantity"
  val TRANSACTION_ID = "transactionID"
  val TRANSACTION_AMOUNT = "transactionAmount"
  val REDEEM_AMOUNT = "redeemAmount"
  val AWB_PROOF_HASH = "awbProofHash"
  val AMOUNT = "amount"
  val ACL_ADDRESS = "aclAddress"
  val ISSUE_ASSET = "issueAsset"
  val ISSUE_FIAT = "issueFiat"
  val SEND_ASSET = "sendAsset"
  val SEND_FIAT = "sendFiat"
  val REDEEM_ASSET = "redeemAsset"
  val REDEEM_FIAT = "redeemFiat"
  val RECEIVE_NOTIFICATIONS = "receiveNotifications"
  val RATING = "rating"
  val SELLER_EXECUTE_ORDER = "sellerExecuteOrder"
  val BUYER_EXECUTE_ORDER = "buyerExecuteOrder"
  val CHANGE_BUYER_BID = "changeBuyerBid"
  val CHANGE_SELLER_BID = "changeSellerBid"
  val CONFIRM_BUYER_BID = "confirmBuyerBid"
  val CONFIRM_SELLER_BID = "confirmSellerBid"
  val NEGOTIATION = "negotiation"
  val RELEASE_ASSET = "releaseAsset"

  //Master
  val ADDRESS = "address"
  val PHONE = "phone"
  val EMAIL = "email"
  val ID = "id"
  val CURRENCY = "currency"
  val LOGIN = "Login"
  val LOGOUT = "Logout"
  val USERNAME = "username"
  val SIGNUP = "SignUp"
  val UPDATE_CONTACT = "UpdateContact"
  val MOBILE_NUMBER = "mobileNumber"
  val EMAIL_ADDRESS = "emailAddress"
  val VERIFY_EMAIL_ADDRESS = "VerifyEmailAddress"
  val OTP = "otp"
  val VERIFY_MOBILE_NUMBER = "VerifyMobileNumber"
  val VERIFY_ORGANIZATION = "VerifyOrganization"
  val VERIFY_ZONE = "VerifyZone"
}
