package constants

object Forms {

  val Index = "Index"

  //Blockchain
  val AddKey = "AddKey"
  val AddZone = "AddZone"
  val AddOrganization = "AddOrganization"
  val BuyerExecuteOrder = "BuyerExecuteOrder"
  val ChangeBuyerBid = "ChangeBuyerBid"
  val ChangeSellerBid = "ChangeSellerBid"
  val ConfirmBuyerBid = "ConfirmBuyerBid"
  val ConfirmSellerBid = "ConfirmSellerBid"
  val IssueAsset = "IssueAsset"
  val IssueFiat = "IssueFiat"
  val RedeemAsset = "RedeemAsset"
  val RedeemFiat = "RedeemFiat"
  val ReleaseAsset = "ReleaseAsset"
  val SellerExecuteOrder = "SellerExecuteOrder"
  val SendAsset = "SendAsset"
  val SendCoin = "SendCoin"
  val SendFiat = "SendFiat"
  val SetACL = "SetACL"
  val SetBuyerFeedback = "SetBuyerFeedback"
  val SetSellerFeedback = "SetSellerFeedback"

  val name = "name"
  val seed = "seed"
  val password = "password"
  val from = "from"
  val to = "to"
  val organizationID = "organizationID"
  val zoneID = "zoneID"
  val buyerAddress = "buyerAddress"
  val sellerAddress = "sellerAddress"
  val fiatProofHash = "fiatProofHash"
  val pegHash = "pegHash"
  val gas = "gas"
  val bid = "bid"
  val time = "time"
  val documentHash = "documentHash"
  val assetType = "assetType"
  val assetPrice = "assetPrice"
  val quantityUnit = "quantityUnit"
  val assetQuantity = "assetQuantity"
  val transactionID = "transactionID"
  val transactionAmount = "transactionAmount"
  val redeemAmount = "redeemAmount"
  val awbProofHash = "awbProofHash"
  val amount = "amount"
  val aclAddress = "aclAddress"
  val issueAsset = "issueAsset"
  val issueFiat = "issueFiat"
  val sendAsset = "sendAsset"
  val sendFiat = "sendFiat"
  val redeemAsset = "redeemAsset"
  val redeemFiat = "redeemFiat"
  val rating = "rating"
  val sellerExecuteOrder = "sellerExecuteOrder"
  val buyerExecuteOrder = "buyerExecuteOrder"
  val changeBuyerBid = "changeBuyerBid"
  val changeSellerBid = "changeSellerBid"
  val confirmBuyerBid = "confirmBuyerBid"
  val confirmSellerBid = "confirmSellerBid"
  val negotiation = "negotiation"
  val releaseAsset = "releaseAsset"

  //Master
  val address = "address"
  val phone = "phone"
  val email = "email"
  val id = "id"
  val currency = "currency"
  val Login = "Login"
  val username = "username"
  val SignUp = "SignUp"
  val UpdateContact = "UpdateContact"
  val mobileNumber = "mobileNumber"
  val emailAddress = "emailAddress"
  val VerifyEmailAddress = "VerifyEmailAddress"
  val otp = "otp"
  val VerifyMobileNumber = "VerifyMobileNumber"
  val VerifyOrganization= "VerifyOrganization"
}
