package constants

object Forms {

  val INDEX = "Index"

  //Blockchain
  val ADD_KEY_TITLE               = "Add Key"
  val ADD_ZONE_TITLE              = "Add Zone"
  val ADD_ORGANIZATION_TITLE      = "Add Organization"
  val BUYER_EXECUTE_ORDER_TITLE   = "Buyer Execute Order"
  val CHANGE_BUYER_BID_TITLE      = "Change Buyer Bid"
  val CHANGE_SELLER_BID_TITLE     = "Change Seller Bid"
  val CONFIRM_BUYER_BID_TITLE     = "Confirm Buyer Bid"
  val CONFIRM_SELLER_BID_TITLE    = "Confirm Seller Bid"
  val ISSUE_ASSET_TITLE           = "Issue Asset"
  val ISSUE_FIAT_TITLE            = "Issue Fiat"
  val REDEEM_ASSET_TITLE          = "Redeem Asset"
  val REDEEM_FIAT_TITLE           = "Redeem Fiat"
  val RELEASE_ASSET_TITLE         = "Release Asset"
  val SELLER_EXECUTE_ORDER_TITLE  = "Seller Execute Order"
  val SEND_ASSET_TITLE            = "Send Asset"
  val SEND_COIN_TITLE             = "Send Coin"
  val REQUEST_COIN_TITLE          = "Request Coin"
  val SEND_FIAT_TITLE             = "Send Fiat"
  val SET_ACL_TITLE               = "Set ACL"
  val SET_BUYER_FEEDBACK_TITLE    = "Set Buyer Feedback"
  val SET_SELLER_FEEDBACK_TITLE   = "Set Seller Feedback"

  val NAME                    = "NAME"
  val SEED                    = "SEED"
  val PASSWORD                = "PASSWORD"
  val FROM                    = "FROM"
  val TO                      = "TO"
  val ORGANIZATION_ID         = "ORGANIZATION_ID"
  val ZONE_ID                 = "ZONE_ID"
  val BUYER_ADDRESS           = "BUYER_ADDRESS"
  val SELLER_ADDRESS          = "SELLER_ADDRESS"
  val FIAT_PROOF_HASH         = "FIAT_PROOF_HASH"
  val PEG_HASH                = "PEG_HASH"
  val GAS                     = "GAS"
  val BID                     = "BID"
  val TIME                    = "TIME"
  val DOCUMENT_HASH           = "DOCUMENT_HASH"
  val ASSET_TYPE              = "ASSET_TYPE"
  val ASSET_PRICE             = "ASSET_PRICE"
  val QUANTITY_UNIT           = "QUANTITY_UNIT"
  val ASSET_QUANTITY          = "ASSET_QUANTITY"
  val TRANSACTION_ID          = "TRANSACTION_ID"
  val TRANSACTION_AMOUNT      = "TRANSACTION_AMOUNT"
  val REDEEM_AMOUNT           = "REDEEM_AMOUNT"
  val AWB_PROOF_HASH          = "AWB_PROOF_HASH"
  val AMOUNT                  = "AMOUNT"
  val ACL_ADDRESS             = "ACL_ADDRESS"
  val ISSUE_ASSET             = "ISSUE_ASSET"
  val ISSUE_FIAT              = "ISSUE_FIAT"
  val SEND_ASSET              = "SEND_ASSET"
  val SEND_FIAT               = "SEND_FIAT"
  val REDEEM_ASSET            = "REDEEM_ASSET"
  val REDEEM_FIAT             = "REDEEM_FIAT"
  val RECEIVE_NOTIFICATIONS   = "RECEIVE_NOTIFICATIONS"
  val RATING                  = "RATING"
  val SELLER_EXECUTE_ORDER    = "SELLER_EXECUTE_ORDER"
  val BUYER_EXECUTE_ORDER     = "BUYER_EXECUTE_ORDER"
  val CHANGE_BUYER_BID        = "CHANGE_BUYER_BID"
  val CHANGE_SELLER_BID       = "CHANGE_SELLER_BID"
  val CONFIRM_BUYER_BID       = "CONFIRM_BUYER_BID"
  val CONFIRM_SELLER_BID      = "CONFIRM_SELLER_BID"
  val NEGOTIATION             = "NEGOTIATION"
  val RELEASE_ASSET           = "RELEASE_ASSET"

  //Master
  val ADDRESS = "address"
  val PHONE = "phone"
  val EMAIL = "email"
  val ID = "id"
  val CURRENCY = "currency"
  val LOGIN = "Login"
  val LOGOUT = "Logout"
  val USERNAME = "username"
  val NOTIFICATION_TOKEN = "notificationToken"
  val TOKEN = "Token"
  val SIGNUP = "SignUp"
  val UPDATE_CONTACT = "UpdateContact"
  val MOBILE_NUMBER = "mobileNumber"
  val COUNTRY_CODE = "countryCode"
  val EMAIL_ADDRESS = "emailAddress"
  val VERIFY_EMAIL_ADDRESS = "VerifyEmailAddress"
  val OTP = "otp"
  val VERIFY_MOBILE_NUMBER = "VerifyMobileNumber"
  val VERIFY_ORGANIZATION = "VerifyOrganization"
  val VERIFY_ZONE = "VerifyZone"
  val SHOW_NOTIFICATIONS = "ShowNotifications"
  val NOTIFICATION_BOX = "NotificationBox"
  val PAGE_NUMBER= "pageNumber"
  val NOTIFICATION_ID= "notificationID"
}
