package constants

object KeyStore {
  val MEMBER_CHECK_API_HEADER_VALUE = "MEMBER_CHECK_API_HEADER_VALUE"

  val TRULIOO_API_KEY_VALUE = "TRULIOO_API_KEY_VALUE"

  val DOCUSIGN_ACCOUNT_ID = "DOCUSIGN_ACCOUNT_ID"
  val DOCUSIGN_CLIENT_SECRET = "DOCUSIGN_CLIENT_SECRET"
  val DOCUSIGN_INTEGRATION_KEY = "DOCUSIGN_INTEGRATION_KEY"

  val WESTERN_UNION_CLIENT_ID = "WESTERN_UNION_CLIENT_ID"
  val WESTERN_UNION_SERVICE_ID = "WESTERN_UNION_SERVICE_ID"
  val WESTERN_UNION_URL = "WESTERN_UNION_URL"
  val WESTERN_UNION_SFTP_SITE = "WESTERN_UNION_SFTP_SITE"
  val WESTERN_UNION_SFTP_USERNAME = "WESTERN_UNION_SFTP_USERNAME"
  val WESTERN_UNION_SFTP_PASSWORD = "WESTERN_UNION_SFTP_PASSWORD"
  val WESTERN_UNION_RTCB_SECRET_KEY = "WESTERN_UNION_RTCB_SECRET_KEY"
  val COMDEX_PGP_PRIVATE_KEY_PASSWORD = "COMDEX_PGP_PRIVATE_KEY_PASSWORD"

  val TWILIO_SMS_ACCOUNT_SID = "TWILIO_SMS_ACCOUNT_SID"
  val TWILIO_SMS_FROM_NUMBER = "TWILIO_SMS_FROM_NUMBER"
  val TWILIO_SMS_AUTH_TOKEN = "TWILIO_SMS_AUTH_TOKEN"

  val PUSH_NOTIFICATION_AUTHORIZATION_KEY = "PUSH_NOTIFICATION_AUTHORIZATION_KEY"

}
