package constants

object Log {

  val DEFAULT_ERROR_LOGGER = "DEFAULT_ERROR_LOGGER"
  val DEFAULT_INFO_LOGGER = "DEFAULT_INFO_LOGGER"

  object Info {
    val CONTROLLERS_REQUEST= "CONTROLLERS_REQUEST"
    val CONTROLLERS_RESPONSE= "CONTROLLERS_RESPONSE"
    val STORE_FILE_ENTRY = "STORE_FILE_ENTRY"
    val STORE_FILE_EXIT = "STORE_FILE_EXIT"
  }

}
