package constants

object Module {
  //Master model
  val MASTER_ACCOUNT = "MASTER_ACCOUNT"
  val MASTER_ACCOUNT_FILE = "MASTER_ACCOUNT_FILE"
  val MASTER_ACCOUNT_KYC = "MASTER_ACCOUNT_KYC"
  val MASTER_EMAIL_ADDRESS = "MASTER_EMAIL_ADDRESS"
  val MASTER_IDENTIFICATION = "MASTER_IDENTIFICATION"
  val MASTER_MOBILE_NUMBER = "MASTER_MOBILE_NUMBER"
  val MASTER_ORGANIZATION_UBO = "MASTER_ORGANIZATION_UBO"

  val FILE_RESOURCE_MANAGER = "FILE_RESOURCE_MANAGER"
  val FILE_OPERATIONS = "FILE_OPERATIONS"
  val IMAGE_PROCESS = "IMAGE_PROCESS"
  val FILE_CONTROLLER = "FILE_CONTROLLER"
  val SFTP_SCHEDULER = "SFTP_SCHEDULER"
  val SERIALIZABLE = "SERIALIZABLE"

  //BlockchainTransaction model
  val BLOCKCHAIN_TRANSACTION_SEND_COIN = "BLOCKCHAIN_TRANSACTION_SEND_COIN"

  //Blockchain model
  val BLOCKCHAIN_ACCOUNT = "BLOCKCHAIN_ACCOUNT"

  //Transactions
  val TRANSACTIONS_ADD_KEY = "TRANSACTIONS_ADD_KEY"
  val TRANSACTIONS_CHANGE_PASSWORD = "TRANSACTIONS_CHANGE_PASSWORD"
  val TRANSACTIONS_FORGOT_PASSWORD = "TRANSACTIONS_FORGOT_PASSWORD"
  val TRANSACTIONS_MEMBER_CHECK_MEMBER_SCAN = "TRANSACTIONS_MEMBER_CHECK_MEMBER_SCAN"
  val TRANSACTIONS_MEMBER_CHECK_MEMBER_SCAN_RESULT_DECISION = "TRANSACTIONS_MEMBER_CHECK_MEMBER_SCAN_RESULT_DECISION"
  val TRANSACTIONS_MEMBER_CHECK_CORPORATE_SCAN = "TRANSACTIONS_MEMBER_CHECK_CORPORATE_SCAN"
  val TRANSACTIONS_MEMBER_CHECK_CORPORATE_SCAN_RESULT_DECISION = "TRANSACTIONS_MEMBER_CHECK_CORPORATE_SCAN_RESULT_DECISION"
  val TRANSACTIONS_SEND_COIN = "TRANSACTIONS_SEND_COIN"
  val TRANSACTIONS_TRULIOO_VERIFY = "TRANSACTIONS_TRULIOO_VERIFY"
  val TRANSACTIONS_DOCUSIGN_REGENERATE_TOKEN = "TRANSACTIONS_DOCUSIGN_REGENERATE_TOKEN"

  //QUERIES
  val QUERIES_GET_ACCOUNT = "QUERIES_GET_ACCOUNT"
  val QUERIES_GET_BLOCK_DETAILS = "QUERIES_GET_BLOCK_DETAILS"
  val QUERIES_GET_MEMBER_CHECK_MEMBER_SCAN = "QUERIES_GET_MEMBER_CHECK_MEMBER_SCAN"
  val QUERIES_GET_MEMBER_CHECK_MEMBER_SCAN_RESULT = "QUERIES_GET_MEMBER_CHECK_MEMBER_SCAN_RESULT"
  val QUERIES_GET_MEMBER_CHECK_CORPORATE_SCAN = "QUERIES_GET_MEMBER_CHECK_CORPORATE_SCAN"
  val QUERIES_GET_MEMBER_CHECK_CORPORATE_SCAN_RESULT = "QUERIES_GET_MEMBER_CHECK_CORPORATE_SCAN_RESULT"
  val QUERIES_GET_TRANSACTION_HASH = "QUERIES_GET_TRANSACTION_HASH"
  val QUERIES_GET_RESPONSE = "QUERIES_GET_RESPONSE"
  val QUERIES_GET_MNEMONIC = "QUERIES_GET_MNEMONIC"
  val QUERIES_GET_TRANSACTION_HASH_RESPONSE = "QUERIES_GET_TRANSACTION_HASH_RESPONSE"
  val QUERIES_GET_TRULIOO_COUNTRY_CODES = "QUERIES_GET_TRULIOO_COUNTRY_CODES"
  val QUERIES_GET_TRULIOO_AUTHENTICATION = "QUERIES_GET_TRULIOO_AUTHENTICATION"
  val QUERIES_GET_TRULIOO_ENTITIES = "QUERIES_GET_TRULIOO_ENTITIES"
  val QUERIES_GET_TRULIOO_FIELDS = "QUERIES_GET_TRULIOO_FIELDS"
  val QUERIES_GET_TRULIOO_RECOMMENDED_FIELDS = "QUERIES_GET_TRULIOO_RECOMMENDED_FIELDS"
  val QUERIES_GET_TRULIOO_CONSENTS = "QUERIES_GET_TRULIOO_CONSENTS"
  val QUERIES_GET_TRULIOO_DETAILED_CONSENTS = "QUERIES_GET_TRULIOO_DETAILED_CONSENTS"
  val QUERIES_GET_TRULIOO_COUNTRY_SUBDIVISIONS = "QUERIES_GET_TRULIOO_COUNTRY_SUBDIVISIONS"
  val QUERIES_GET_TRULIOO_DATA_SOURCES = "QUERIES_GET_TRULIOO_DATA_SOURCES"
  val QUERIES_GET_TRULIOO_TRANSACTION_RECORD = "QUERIES_GET_TRULIOO_TRANSACTION_RECORD"
  val QUERIES_GET_ABCI_INFO = "QUERIES_GET_ABCI_INFO"

  //MasterTransactions
  val MASTER_TRANSACTION_SESSION_TOKEN = "MASTER_TRANSACTION_SESSION_TOKEN"
  val MASTER_TRANSACTION_EMAIL_OTP = "MASTER_TRANSACTION_EMAIL_OTP"
  val MASTER_TRANSACTION_NOTIFICATION = "MASTER_TRANSACTION_NOTIFICATION"
  val MASTER_TRANSACTION_PUSH_NOTIFICATION_TOKEN = "MASTER_TRANSACTION_PUSH_NOTIFICATION_TOKEN"
  val MASTER_TRANSACTION_SMS_OTP = "MASTER_TRANSACTION_SMS_OTP"
  val MASTER_TRANSACTION_TRADE_TERM = "MASTER_TRANSACTION_TRADE_TERMS"
  val MASTER_TRANSACTION_CHAT = "MASTER_TRANSACTION_CHAT"
  val MASTER_TRANSACTION_MESSAGE = "MASTER_TRANSACTION_MESSAGE"
  val MASTER_TRANSACTION_MESSAGE_READ = "MASTER_TRANSACTION_MESSAGE_READ"

  //Western Union
  val WESTERN_UNION_RTCB = "WESTERN_UNION_RTCB"
  val WESTERN_UNION_SFTP_FILE_TRANSACTION = "WESTERN_UNION_SFTP_FILE_TRANSACTION"
  val WESTERN_UNION_FIAT_REQUEST = "WESTERN_UNION_FIAT_REQUEST"

  //Docusign
  val DOCUSIGN_ENVELOPE = "DOCUSIGN_ENVELOPE"
  val DOCUSIGN_ENVELOPE_HISTORY = "DOCUSIGN_ENVELOPE_HISTORY"
  val DOCUSIGN_OAUTH_TOKEN = "DOCUSIGN_OAUTH_TOKEN"

  //Member Check
  val MEMBER_CHECK_MEMBER_SCAN = "MEMBER_CHECK_MEMBER_SCAN"
  val MEMBER_CHECK_MEMBER_SCAN_DECISION = "MEMBER_CHECK_MEMBER_SCAN_DECISION"
  val MEMBER_CHECK_CORPORATE_SCAN = "MEMBER_CHECK_CORPORATE_SCAN"
  val MEMBER_CHECK_CORPORATE_SCAN_DECISION = "MEMBER_CHECK_CORPORATE_SCAN_DECISION"
  val MEMBER_CHECK_VESSEL_SCAN = "MEMBER_CHECK_VESSEL_SCAN"
  val MEMBER_CHECK_VESSEL_SCAN_DECISION = "MEMBER_CHECK_VESSEL_SCAN_DECISION"
  val MEMBER_CHECK_VESSEL_SCAN_DECISION_HISTORY = "MEMBER_CHECK_VESSEL_SCAN_DECISION_HISTORY"

  //Controllers
  val CONTROLLERS_SIGN_UP = "CONTROLLERS_SIGN_UP"
  val CONTROLLERS_LOGIN = "CONTROLLERS_LOGIN"
  val CONTROLLERS_LOGOUT = "CONTROLLERS_LOGOUT"
  val CONTROLLERS_NOTIFICATION = "CONTROLLERS_NOTIFICATION"
  val CONTROLLERS_ACCOUNT = "CONTROLLERS_ACCOUNT"
  val CONTROLLERS_SEND_COIN = "CONTROLLERS_SEND_COIN"
  val CONTROLLERS_CONTACT = "CONTROLLERS_CONTACT"
  val CONTROLLERS_INDEX = "CONTROLLERS_INDEX"
  val CONTROLLERS_VIEW = "CONTROLLERS_VIEW"
  val CONTROLLERS_WESTERN_UNION = "CONTROLLERS_WESTERN_UNION"
  val CONTROLLERS_CHAT = "CONTROLLERS_CHAT"
  val CONTROLLERS_BACKGROUND_CHECK = "CONTROLLERS_BACKGROUND_CHECK"
  val CONTROLLERS_COMPONENT_VIEW = "CONTROLLERS_COMPONENT_VIEW"
  val CONTROLLERS_DOCUSIGN = "CONTROLLERS_DOCUSIGN"

  //Actions
  val ACTIONS_WITH_LOGIN_ACTION = "ACTIONS_WITH_LOGIN_ACTION"
  val ACTIONS_WITH_UNKNOWN_LOGIN_ACTION = "ACTIONS_WITH_UNKNOWN_LOGIN_ACTION"
  val ACTIONS_WITH_USER_LOGIN_ACTION = "ACTIONS_WITH_USER_LOGIN_ACTION"

  //Utilities
  val UTILITIES_TRANSACTION = "UTILITIES_TRANSACTION"
  val UTILITIES_NOTIFICATION = "UTILITIES_NOTIFICATION"
  val UTILITIES_DOCUSIGN = "UTILITIES_DOCUSIGN"
  val UTILITIES_KEY_STORE = "UTILITIES_KEY_STORE"

  //actors
  val ACTOR_COMET = "ACTOR_COMET"
  val ACTOR_SERVICE = "ACTOR_SERVICE"
  val ACTOR_EMAIL = "ACTOR_EMAIL"
  val ACTOR_SMS = "ACTOR_SMS"
  val ACTOR_PUSH_NOTIFICATION = "ACTOR_PUSH_NOTIFICATION"
}
