package constants

object Module {
  val MASTER_ACCOUNT = "MASTER_ACCOUNT"
  val TRANSACTIONS_ADD_KEY = "TRANSACTIONS_ADD_KEY"
  val TRANSACTIONS_GET_SEED = "TRANSACTIONS_GET_SEED"
  val CONTROLLER_SIGN_UP = "CONTROLLER_SIGN_UP"
}
