package constants

object Module {
  //Master model
  val MASTER_ACCOUNT = "MASTER_ACCOUNT"

  //BlockchainTransaction model
  val Blockchain_TRANSACTION_ADD_ORGANIZATION = "Blockchain_TRANSACTION_ADD_ORGANIZATION"
  val Blockchain_TRANSACTION_SEND_COIN = "Blockchain_TRANSACTION_SEND_COIN"

  //Transactions
  val TRANSACTIONS_ADD_KEY                  = "TRANSACTIONS_ADD_KEY"
  val TRANSACTIONS_ADD_ORGANIZATION         = "TRANSACTIONS_ADD_ORGANIZATION"
  val TRANSACTIONS_ADD_ZONE                 = "TRANSACTIONS_ADD_ZONE"
  val TRANSACTIONS_BUYER_EXECUTE_ORDER      = "TRANSACTIONS_BUYER_EXECUTE_ORDER"
  val TRANSACTIONS_CHANGE_BUYER_BID         = "TRANSACTIONS_CHANGE_BUYER_BID"
  val TRANSACTIONS_CHANGE_SELLER_BID        = "TRANSACTIONS_CHANGE_SELLER_BID"
  val TRANSACTIONS_CONFIRM_BUYER_BID        = "TRANSACTIONS_CONFIRM_BUYER_BID"
  val TRANSACTIONS_CONFIRM_SELLER_BID       = "TRANSACTIONS_CONFIRM_SELLER_BID"
  val TRANSACTIONS_GET_ACCOUNT              = "TRANSACTIONS_GET_ACCOUNT"
  val TRANSACTIONS_GET_ACL                  = "TRANSACTIONS_GET_ACL"
  val TRANSACTIONS_GET_ASSET                = "TRANSACTIONS_GET_ASSET"
  val TRANSACTIONS_GET_FIAT                 = "TRANSACTIONS_GET_FIAT"
  val TRANSACTIONS_GET_NEGOTIATION          = "TRANSACTIONS_GET_NEGOTIATION"
  val TRANSACTIONS_GET_ORDER                = "TRANSACTIONS_GET_ORDER"
  val TRANSACTIONS_GET_ORGANIZATION         = "TRANSACTIONS_GET_ORGANIZATION"
  val TRANSACTIONS_GET_RESPONSE             = "TRANSACTIONS_GET_RESPONSE"
  val TRANSACTIONS_GET_SEED                 = "TRANSACTIONS_GET_SEED"
  val TRANSACTIONS_GET_TRADER_REPUTATION    = "TRANSACTIONS_GET_TRADER_REPUTATION"
  val TRANSACTIONS_GET_ZONE                 = "TRANSACTIONS_GET_ZONE"
  val TRANSACTIONS_ISSUE_ASSET              = "TRANSACTIONS_ISSUE_ASSET"
  val TRANSACTIONS_ISSUE_FIAT               = "TRANSACTIONS_ISSUE_FIAT"
  val TRANSACTIONS_REDEEM_ASSET             = "TRANSACTIONS_REDEEM_ASSET"
  val TRANSACTIONS_REDEEM_FIAT              = "TRANSACTIONS_REDEEM_FIAT"
  val TRANSACTIONS_RELEASE_ASSET            = "TRANSACTIONS_RELEASE_ASSET"
  val TRANSACTIONS_SELLER_EXECUTE_ORDER     = "TRANSACTIONS_SELLER_EXECUTE_ORDER"
  val TRANSACTIONS_SEND_ASSET               = "TRANSACTIONS_SEND_ASSET"
  val TRANSACTIONS_SEND_COIN                = "TRANSACTIONS_SEND_COIN"
  val TRANSACTIONS_SEND_FIAT                = "TRANSACTIONS_SEND_FIAT"
  val TRANSACTIONS_SET_ACL                  = "TRANSACTIONS_SET_ACL"
  val TRANSACTIONS_SET_BUYER_FEEDBACK       = "TRANSACTIONS_SET_BUYER_FEEDBACK"
  val TRANSACTIONS_SET_SELLER_FEEDBACK      = "TRANSACTIONS_SET_SELLER_FEEDBACK"

  //Controllers
  val CONTROLLERS_SIGN_UP = "CONTROLLERS_SIGN_UP"
  val CONTROLLERS_ADD_ORGANIZATION = "CONTROLLERS_ADD_ORGANIZATION"
  val CONTROLLERS_LOGIN = "CONTROLLERS_LOGIN"
}
