package constants

object Status {

  object Account {
    val NO_CONTACT = "NO_CONTACT"
    val CONTACT_UNVERIFIED = "CONTACT_UNVERIFIED"
    val EMAIL_ADDRESS_UNVERIFIED = "EMAIL_ADDRESS_UNVERIFIED"
    val MOBILE_NUMBER_UNVERIFIED = "MOBILE_NUMBER_UNVERIFIED"
    val COMPLETE = "COMPLETE"
  }

}
