package constants

object Status {

  object Contact {
    val NO_MOBILE_NUMBER = "NO_MOBILE_NUMBER"
    val NO_EMAIL_ADDRESS = "NO_EMAIL_ADDRESS"
    val EMAIL_ADDRESS_UNVERIFIED = "EMAIL_ADDRESS_UNVERIFIED"
    val EMAIL_ADDRESS_VERIFIED = "EMAIL_ADDRESS_VERIFIED"
    val MOBILE_NUMBER_UNVERIFIED = "MOBILE_NUMBER_UNVERIFIED"
    val MOBILE_NUMBER_VERIFIED = "MOBILE_NUMBER_VERIFIED"
  }

  object TraderInvitation {
    val NO_CONTACT = "NO_CONTACT"
    val CONTACT_VERIFICATION_PENDING = "CONTACT_VERIFICATION_PENDING"
    val CONTACT_VERIFICATION_COMPLETE_NO_IDENTIFICATION = "CONTACT_VERIFICATION_COMPLETE_NO_IDENTIFICATION"
    val IDENTIFICATION_VERIFICATION_PENDING = "IDENTIFICATION_VERIFICATION_PENDING"
    val IDENTIFICATION_COMPLETE_DOCUMENT_UPLOAD_PENDING = "IDENTIFICATION_COMPLETE_DOCUMENT_UPLOAD_PENDING"
    val TRADER_ADDED_FOR_VERIFICATION = "TRADER_ADDED_FOR_VERIFICATION"
  }

  object Asset {
    val REQUESTED_TO_ZONE = "REQUESTED_TO_ZONE"
    val AWAITING_BLOCKCHAIN_RESPONSE = "AWAITING_BLOCKCHAIN_RESPONSE"

    val ISSUED = "ISSUED"

    val IN_ORDER = "IN_ORDER"
    val REDEEMED = "REDEEMED"

    val TRADED = "TRADED"

    val ISSUE_ASSET_FAILED = "ISSUE_ASSET_FAILED"
    val REJECTED_BY_ZONE = "REJECTED_BY_ZONE"
  }

  object Negotiation {
    val FORM_INCOMPLETE = "FORM_INCOMPLETE"
    val ISSUE_ASSET_PENDING = "ISSUE_ASSET_PENDING"
    val ISSUE_ASSET_FAILED = "ISSUE_ASSET_FAILED"
    val REQUEST_SENT = "REQUEST_SENT"
    val STARTED = "STARTED"
    val BUYER_CONFIRMED_SELLER_PENDING = "BUYER_CONFIRMED_SELLER_PENDING"
    val SELLER_CONFIRMED_BUYER_PENDING = "SELLER_CONFIRMED_BUYER_PENDING"
    val BOTH_PARTIES_CONFIRMED = "BOTH_PARTIES_CONFIRMED"
    val REJECTED = "REJECTED"
  }

  object Order {
    val SENDING_ASSET_AND_FIAT_PENDING = "SENDING_ASSET_AND_FIAT_PENDING"
    val ASSET_SENT_FIAT_PENDING = "ASSET_SENT_FIAT_PENDING"
    val FIAT_SENT_ASSET_PENDING = "FIAT_SENT_ASSET_PENDING"
    val COMPLETED = "COMPLETED"
    val REVERSED = "REVERSED"
    val TIMED_OUT = "TIMED_OUT"
  }

}