package constants

object Success {
  val SIGN_UP = "SIGN_UP"
  val LOG_OUT = "LOG_OUT"
  val ADD_KEY = "ADD_KEY"
  val VERIFY_ORGANIZATION = "VERIFY_ORGANIZATION"
  val VERIFY_ZONE = "VERIFY_ZONE"
  val ADD_ORGANIZATION = "ADD_ORGANIZATION"
  val ADD_ZONE = "ADD_ZONE"
  val REQUEST_COINS = "REQUEST_COINS"
  val APPROVED_FAUCET_REQUEST = "APPROVED_FAUCET_REQUEST"
  val ISSUE_ASSET_REQUEST = "ISSUE_ASSET_REQUEST"
  val ISSUE_FIAT_REQUEST = "ISSUE_FIAT_REQUEST"
  val ISSUE_ASSET_REQUEST_REJECTED = "ISSUE_ASSET_REQUEST_REJECTED"
  val ISSUE_FIAT_REQUEST_REJECTED = "ISSUE_FIAT_REQUEST_REJECTED"
}
