package constants

object Test {
  val NUMBER_OF_USERS = 1500

  val BASE_URL = "http://localhost:9000"

  val IMAGE_FILE_FEED="/home/persistence-1/testImages/"
  val TEST_NAME = "TEST_NAME"
  val TEST_MNEMONIC = "TEST_MNEMONIC"

  val TEST_ZONE_ID = "TEST_ZONE_ID"
  val TEST_TRADER_ID = "TEST_TRADER_ID"
  val TEST_ADDRESS = "TEST_ADDRESS"
  val TEST_EMAIL = "TEST_EMAIL"
  val TEST_PHONE = "TEST_PHONE"

  val TEST_ORGANIZATION_ID = "TEST_ORGANIZATION_ID"
  val TEST_FROM = "TEST_FROM"
  val TEST_TO = "TEST_TO"

  val TEST_CURRENCY = "TEST_CURRENCY"

  val TEST_SELLER_ADDRESS = "TEST_SELLER_ADDRESS"
  val TEST_BUYER_ADDRESS = "TEST_BUYER_ADDRESS"
  val TEST_FIAT_PROOF_HASH = "TEST_FIAT_PROOF_HASH"
  val TEST_PEG_HASH = "TEST_PEG_HASH"
  val TEST_GAS = "TEST_GAS"

  val TEST_BID = "TEST_BID"
  val TEST_TIME = "TEST_TIME"

  val TEST_DOCUMENT_HASH = "TEST_DOCUMENT_HASH"
  val TEST_ASSET_TYPE = "TEST_ASSET_TYPE"
  val TEST_ASSET_PRICE = "TEST_ASSET_PRICE"
  val TEST_QUANTITY_UNIT = "TEST_QUANTITY_UNIT"
  val TEST_ASSET_QUANTITY = "TEST_ASSET_QUANTITY"
  val TEST_REQUEST_ID = "TEST_REQUEST_ID"
  val TEST_ACCOUNT_ID = "TEST_ACCOUNT_ID"
  val TEST_COMMODITY_NAME="TEST_COMMODITY_NAME"
  val TEST_QUALITY="TEST_QUALITY"
  val TEST_DELIVERY_TERM="TEST_DELIVERY_TERM"
  val TEST_TRADE_TYPE="TEST_TRADE_TYPE"
  val TEST_PORT_OF_LOADING="TEST_PORT_OF_LOADING"
  val TEST_PORT_OF_DISCHARGE="TEST_PORT_OF_DISCHARGE"
  val TEST_SHIPMENT_DATE="TEST_SHIPMENT_DATE"
  val TEST_COMDEX_PAYMENT_TERMS="TEST_COMDEX_PAYMENT_TERMS"
  val TEST_BILL_OF_LADING_NUMBER="TEST_BILL_OF_LADING_NUMBER"
  val TEST_SHIPPER_NAME="TEST_SHIPPER_NAME"
  val TEST_SHIPPER_ADDRESS="TEST_SHIPPER_ADDRESS"
  val TEST_NOTIFY_PARTY_NAME="NOTIFY_PARTY_NAME"
  val TEST_NOTIFY_PARTY_ADDRESS="TEST_NOTIFY_PARTY_ADDRESS"


  val TEST_TRANSACTION_ID = "TEST_TRANSACTION_ID"
  val TEST_TRANSACTION_AMOUNT = "TEST_TRANSACTION_AMOUNT"

  val TEST_RECEIVE_NOTIFICATIONS = "TEST_RECEIVE_NOTIFICATIONS"

  val TEST_REDEEM_AMOUNT = "TEST_REDEEM_AMOUNT"

  val TEST_AWB_PROOF_HASH = "TEST_AWB_PROOF_HASH"

  val TEST_AMOUNT = "TEST_AMOUNT"

  val TEST_ACL_ADDRESS = "TEST_ACL_ADDRESS"
  val TEST_ISSUE_ASSET = "TEST_ISSUE_ASSET"
  val TEST_ISSUE_FIAT = "TEST_ISSUE_FIAT"
  val TEST_SEND_ASSET = "TEST_SEND_ASSET"
  val TEST_SEND_FIAT = "TEST_SEND_FIAT"
  val TEST_REDEEM_ASSET = "TEST_REDEEM_ASSET"
  val TEST_REDEEM_FIAT = "TEST_REDEEM_FIAT"
  val TEST_SELLER_EXECUTE_ORDER = "TEST_SELLER_EXECUTE_ORDER"
  val TEST_BUYER_EXECUTE_ORDER = "TEST_BUYER_EXECUTE_ORDER"
  val TEST_CHANGE_BUYER_BID = "TEST_CHANGE_BUYER_BID"
  val TEST_CHANGE_SELLER_BID = "TEST_CHANGE_SELLER_BID"
  val TEST_CONFIRM_BUYER_BID = "TEST_CONFIRM_BUYER_BID"
  val TEST_CONFIRM_SELLER_BID = "TEST_CONFIRM_SELLER_BID"
  val TEST_NEGOTIATION = "TEST_NEGOTIATION"
  val TEST_NEGOTIATION_ID = "TEST_NEGOTIATION_ID"
  val TEST_RELEASE_ASSET = "TEST_RELEASE_ASSET"

  val TEST_RATING = "TEST_RATING"

  val TEST_EMAIL_ADDRESS = "TEST_EMAIL_ADDRESS"
  val TEST_MOBILE_NUMBER = "TEST_MOBILE_NUMBER"
  val TEST_COUNTRY_CODE = "TEST_COUNTRY_CODE"

  val TEST_OTP = "TEST_OTP"

  val TEST_COUPON = "TEST_COUPON"
  val TEST_USERNAME = "TEST_USERNAME"
  val TEST_PASSWORD = "TEST_PASSWORD"
  val ID = "ID"
  val IDU = "IDU"
  val IDP = "IDP"

  val TEST_ZONE_USERNAME = "TEST_ZONE_USERNAME"
  val TEST_ZONE_PASSWORD = "TEST_ZONE_PASSWORD"
  val TEST_ORGANIZATION_USERNAME = "TEST_ORGANIZATION_USERNAME"
  val TEST_ORGANIZATION_PASSWORD = "TEST_ORGANIZATION_PASSWORD"
  val TEST_SELLER_USERNAME = "TEST_SELLER_USERNAME"
  val TEST_SELLER_PASSWORD = "TEST_SELLER_PASSWORD"
  val TEST_BUYER_USERNAME = "TEST_BUYER_USERNAME"
  val TEST_BUYER_PASSWORD = "TEST_BUYER_PASSWORD"
  val TEST_TRADER_USERNAME = "TEST_TRADER_USERNAME"
  val TEST_BUYER_BID = "TEST_BUYER_BID"
  val TEST_SELLER_BID = "TEST_SELLER_BID"

  val TEST_MAIN_USERNAME = "TEST_MAIN_USERNAME"
  val TEST_MAIN_PASSWORD = "TEST_MAIN_PASSWORD"

  val TEST_ZONE_USERNAME_UNIQUE= "ZONE567048"
  val TEST_ZONE_PASSWORD_UNIQUE= "ZONE567048"

  val TEST_ORGANIZATION_USERNAME_UNIQUE= "ORG567048"
  val TEST_ORGANIZATION_PASSWORD_UNIQUE= "ORG567048"

  val TEST_FILE_NAME="TEST_FILE_NAME"
  val TEST_FILE_SIZE="TEST_FILE_SIZE"

  val ZONE_BANK_DETAIL_FILENAME="ZONE_BANK_DETAIL_FILENAME"
  val ZONE_IDENTIFICATION_FILENAME="ZONE_IDENTIFICATION_FILENAME"

  val ZONE_BANK_DETAIL_FILESIZE="ZONE_BANK_DETAIL_FILESIZE"
  val ZONE_IDENTIFICATION_FILESIZE="ZONE_IDENTIFICATION_FILESIZE"

  val TEST_ADDRESS_LINE_1="TEST_ADDRESS_LINE_1"
  val TEST_ADDRESS_LINE_2="TEST_ADDRESS_LINE_2"
  val TEST_LANDMARK="TEST_LANDMARK"
  val TEST_CITY="TEST_CITY"
  val TEST_COUNTRY="TEST_COUNTRY"
  val TEST_ZIP_CODE="TEST_ZIP_CODE"
  val ABBREVIATION = "ABBREVIATION"
  val TEST_MODE= "TEST_MODE"

  val TEST_ACCOUNT_NUMBER="TEST_ACCOUNT_NUMBER"
  val TEST_SWIFT_CODE="TEST_SWIFT_CODE"

  val TEST_DOCUMENT_TYPE="TEST_DOCUMENT_TYPE"
  val TEST_NEGOTIATION_REQUEST_ID="TEST_NEGOTIATION_REQUEST_ID"

  val TEST_ZONE_ACCOUNT_ID="TEST_ZONE_ACCOUNT_ID"
  val TEST_ORGANIZATION_ACCOUNT_ID="TEST_ORGANIZATION_ACCOUNT_ID"

  val USER_TYPE="USER_TYPE"
  val TEST_BLOCKCHAIN_ADDRESS="TEST_BLOCKCHAIN_ADDRESS"
  val TEST_PUBLIC_KEY="TEST_PUBLIC_KEY"
  val TEST_ZONE_ADDRESS="TEST_ZONE_ADDRESS"
  val TEST_ORGANIZATION_ADDRESS="TEST_ORGANIZATION_ADDRESS"

  val TEST_ACCOUNT_HOLDER_NAME="TEST_ACCOUNT_HOLDER_NAME"
  val TEST_NICK_NAME="TEST_NICK_NAME"
  val TEST_STREET_ADDRESS="TEST_STREET_ADDRESS"
  val TEST_BANK_NAME="TEST_BANK_NAME"
  val TEST_CONFIRM_BID="TEST_CONFIRM_BID"


}
