package constants

class TradeActivity(val template: String)

object TradeActivity {
  val PREFIX = "TRADE_ACTIVITY"
  val TITLE_SUFFIX = "TITLE"
  val MESSAGE_SUFFIX = "MESSAGE"

  val NEGOTIATION_STARTED = new TradeActivity("NEGOTIATION_STARTED")
  val DOCUMENT_LIST_UPDATED = new TradeActivity("DOCUMENT_LIST_UPDATED")
  val PAYMENT_TERMS_UPDATED = new TradeActivity("PAYMENT_TERMS_UPDATED")
  val ASSET_DETAILS_UPDATED = new TradeActivity("ASSET_DETAILS_UPDATED")
  val BUYER_SENT_CONFIRM_NEGOTIATION_TRANSACTION_TO_BLOCKCHAIN = new TradeActivity("BUYER_SENT_CONFIRM_NEGOTIATION_TRANSACTION_TO_BLOCKCHAIN")
  val SELLER_SENT_CONFIRM_NEGOTIATION_TRANSACTION_TO_BLOCKCHAIN = new TradeActivity("SELLER_SENT_CONFIRM_NEGOTIATION_TRANSACTION_TO_BLOCKCHAIN")
  val MODERATED_BUY_ORDER_EXECUTED = new TradeActivity("MODERATED_BUY_ORDER_EXECUTED")
  val MODERATED_SELL_ORDER_EXECUTED = new constants.TradeActivity("MODERATED_SELL_ORDER_EXECUTED")
  val BUYER_BID_CONFIRMED = new TradeActivity("BUYER_BID_CONFIRMED")
  val SELLER_BID_CONFIRMED = new TradeActivity("SELLER_BID_CONFIRMED")
}
