package constants

object User {

  //common
  val UNAUTHORIZED_TRANSACTION = "UNAUTHORIZED_TRANSACTION"
  val COMMIT_CENTRAL = "COMMIT_CENTRAL"
  val HOME = "HOME"
  val USER_TYPE = "USER_TYPE"
  val ADDRESS = "ADDRESS"
  val COINS = "COINS"
  val NAME = "NAME"

  val GENESIS = "GENESIS"
  val MAIN_ACCOUNT = "main"
  val TRADER = "TRADER"
  val USER = "USER"
  val ASSETS_OWNED = "ASSETS OWNED"
  val FIATS_OWNED = "FIATS OWNED"
  val FIATS_TOTAL_VALUE = "FIATS TOTAL VALUE"
  val ORGANIZATION = "ORGANIZATION"
  val ZONE = "ZONE"
  val UNKNOWN = "UNKNOWN"
  val WITHOUT_LOGIN = "WITHOUT_LOGIN"

}
