package constants

object View {
  val ORGANIZATION_BANK_ACCOUNT_DETAIL = "ORGANIZATION_BANK_ACCOUNT_DETAIL"
  val CONFIRM_BUYER_BID = "CONFIRM_BUYER_BID"
  val CONFIRM_SELLER_BID = "CONFIRM_SELLER_BID"

  //ZoneRequests
  val PENDING_VERIFY_ORGANIZATION_REQUESTS = "PENDING_VERIFY_ORGANIZATION_REQUESTS"
  val PENDING_SET_ACL = "PENDING_SET_ACL"
  val PENDING_ISSUE_ASSET_REQUESTS = "PENDING_ISSUE_ASSET_REQUESTS"
  val PENDING_ISSUE_FIAT_REQUESTS = "PENDING_ISSUE_FIAT_REQUESTS"
  val PENDING_RELEASE_ASSET = "PENDING_RELEASE_ASSET"
  val PENDING_BUYER_EXECUTE_ORDER = "PENDING_BUYER_EXECUTE_ORDER"
  val PENDING_SELLER_EXECUTE_ORDER = "PENDING_SELLER_EXECUTE_ORDER_LIST"

  //GenesisRequests
  val PENDING_VERIFY_ZONE_REQUESTS = "PENDING_VERIFY_ZONE_REQUESTS"
  val PENDING_FAUCET_REQUESTS = "PENDING_FAUCET_REQUESTS"

  //identification
  val ID_PROOF = "ID_PROOF"
  val NOT_SPECIFIED = "NOT_SPECIFIED"
  val CONTACT_DETAILS = "CONTACT_DETAILS"

  //salesQuote
  val SALES_QUOTE_LIST = "SALES_QUOTE_LIST"
  val COMMODITY_DETAILS = "COMMODITY_DETAILS"
  val SHIPPING_DETAILS = "SHIPPING_DETAILS"
  val PAYMENT_TERMS = "PAYMENT_TERMS"
  val SALES_QUOTE_DOCUMENTS = "DOCUMENTS"
  val ACTION = "ACTION"
  val INVITE = "INVITE"
  val COMPLETE = "COMPLETE"
  val SALES_QUOTE_ID = "SALES_QUOTE_ID"
  val ASSET_DESCRIPTION = "ASSET_DESCRIPTION"

  //TradeRoom
  val FINANCIALS = "FINANCIALS"
  val TRADE_ROOM_ID = "TRADE_ROOM_ID"
  val TRADE_TERMS = "TRADE_TERMS"
  val BUYER_ACCEPTANCE = "BUYER_ACCEPTANCE"
  val DESCRIPTION = "DESCRIPTION"
  val QUANTITY = "QUANTITY"
  val CONTRACT_PRICE = "CONTRACT_PRICE"
  val SHIPMENT_PERIOD = "SHIPMENT_PERIOD"
  val LOAD_PORT = "LOAD_PORT"
  val DISCHARGE_PORT = "DISCHARGE_PORT"
  val ADVANCE_PAYMENT = "ADVANCE_PAYMENT"
  val CREDIT_TERMS = "CREDIT_TERMS"
  val BILL_OF_EXCHANGE_REQUIRED = "BILL_OF_EXCHANGE_REQUIRED"
  val PRIMARY_DOCUMENTS = "PRIMARY_DOCUMENTS"
  val OBL = "OBL"
  val TRADE_LIST = "TRADE_LIST"
  val BUYER = "BUYER"
  val SELLER = "SELLER"


}
