package constants

object View {
  val ORGANIZATION_BANK_ACCOUNT_DETAIL = "ORGANIZATION_BANK_ACCOUNT_DETAIL"
  val CONFIRM_BUYER_BID = "CONFIRM_BUYER_BID"
  val CONFIRM_SELLER_BID = "CONFIRM_SELLER_BID"

  //ZoneRequests
  val PENDING_VERIFY_ORGANIZATION_REQUESTS = "PENDING_VERIFY_ORGANIZATION_REQUESTS"
  val PENDING_SET_ACL = "PENDING_SET_ACL"
  val PENDING_ISSUE_ASSET_REQUESTS = "PENDING_ISSUE_ASSET_REQUESTS"
  val PENDING_ISSUE_FIAT_REQUESTS = "PENDING_ISSUE_FIAT_REQUESTS"
  val PENDING_RELEASE_ASSET = "PENDING_RELEASE_ASSET"
  val PENDING_BUYER_EXECUTE_ORDER = "PENDING_BUYER_EXECUTE_ORDER"
  val PENDING_SELLER_EXECUTE_ORDER = "PENDING_SELLER_EXECUTE_ORDER_LIST"

  //GenesisRequests
  val PENDING_VERIFY_ZONE_REQUESTS = "PENDING_VERIFY_ZONE_REQUESTS"
  val PENDING_FAUCET_REQUESTS = "PENDING_FAUCET_REQUESTS"

  //identification
  val ID_PROOF="ID_PROOF"
  val NOT_SPECIFIED="NOT_SPECIFIED"
  
}
