// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/unwrap/message.proto

package com.splits.transactions.unwrap;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_unwrap_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_unwrap_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/splits/internal/transactions/u" +
      "nwrap/message.proto\022\032splits.transactions" +
      ".unwrap\032\024gogoproto/gogo.proto\032 schema/id" +
      "s/base/identityID.proto\032\"schema/ids/base" +
      "/anyOwnableID.proto\"\221\001\n\007Message\022\022\n\004from\030" +
      "\001 \001(\tR\004from\022)\n\010from_i_d\030\002 \001(\0132\017.ids.Iden" +
      "tityIDR\006fromID\0221\n\013ownable_i_d\030\003 \001(\0132\021.id" +
      "s.AnyOwnableIDR\townableID\022\024\n\005value\030\004 \001(\t" +
      "R\005valueB\204\002\n\036com.splits.transactions.unwr" +
      "apB\014MessageProtoP\001ZJgithub.com/AssetMant" +
      "le/modules/modules/splits/internal/trans" +
      "actions/unwrap\242\002\003STU\252\002\032Splits.Transactio" +
      "ns.Unwrap\312\002\032Splits\\Transactions\\Unwrap\342\002" +
      "&Splits\\Transactions\\Unwrap\\GPBMetadata\352" +
      "\002\034Splits::Transactions::Unwrapb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
        });
    internal_static_splits_transactions_unwrap_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_unwrap_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_unwrap_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "OwnableID", "Value", });
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
