// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/unwrap/service.proto

package com.splits.transactions.unwrap;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/splits/internal/transactions/u" +
      "nwrap/service.proto\022\032splits.transactions" +
      ".unwrap\032\034google/api/annotations.proto\0329m" +
      "odules/splits/internal/transactions/unwr" +
      "ap/message.proto\032Emodules/splits/interna" +
      "l/transactions/unwrap/transactionRespons" +
      "e.proto2\210\001\n\007Service\022}\n\006Handle\022#.splits.t" +
      "ransactions.unwrap.Message\032/.splits.tran" +
      "sactions.unwrap.TransactionResponse\"\035\202\323\344" +
      "\223\002\027\"\025/mantle/splits/unwrapB\204\002\n\036com.split" +
      "s.transactions.unwrapB\014ServiceProtoP\001ZJg" +
      "ithub.com/AssetMantle/modules/modules/sp" +
      "lits/internal/transactions/unwrap\242\002\003STU\252" +
      "\002\032Splits.Transactions.Unwrap\312\002\032Splits\\Tr" +
      "ansactions\\Unwrap\342\002&Splits\\Transactions\\" +
      "Unwrap\\GPBMetadata\352\002\034Splits::Transaction" +
      "s::Unwrapb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.splits.transactions.unwrap.MessageProto.getDescriptor(),
          com.splits.transactions.unwrap.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.splits.transactions.unwrap.MessageProto.getDescriptor();
    com.splits.transactions.unwrap.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
