// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/unwrap/transactionResponse.proto

package com.splits.transactions.unwrap;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_unwrap_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_unwrap_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEmodules/splits/internal/transactions/u" +
      "nwrap/transactionResponse.proto\022\032splits." +
      "transactions.unwrap\"\025\n\023TransactionRespon" +
      "seB\220\002\n\036com.splits.transactions.unwrapB\030T" +
      "ransactionResponseProtoP\001ZJgithub.com/As" +
      "setMantle/modules/modules/splits/interna" +
      "l/transactions/unwrap\242\002\003STU\252\002\032Splits.Tra" +
      "nsactions.Unwrap\312\002\032Splits\\Transactions\\U" +
      "nwrap\342\002&Splits\\Transactions\\Unwrap\\GPBMe" +
      "tadata\352\002\034Splits::Transactions::Unwrapb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_splits_transactions_unwrap_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_unwrap_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_unwrap_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
