// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/unwrap/transactionResponse.proto

package com.splits.transactions.unwrap;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:splits.transactions.unwrap.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
