// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/queries/split/queryResponse.proto

package com.splits.queries.split;

public final class QueryResponseProto {
  private QueryResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_queries_split_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_queries_split_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/splits/internal/queries/split/" +
      "queryResponse.proto\022\024splits.queries.spli" +
      "t\032\024gogoproto/gogo.proto\032/modules/splits/" +
      "internal/mappable/mappable.proto\"k\n\rQuer" +
      "yResponse\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005e" +
      "rror\030\002 \001(\tR\005error\022$\n\004list\030\003 \003(\0132\020.splits" +
      ".MappableR\004list:\004\210\240\037\000B\346\001\n\030com.splits.que" +
      "ries.splitB\022QueryResponseProtoP\001ZDgithub" +
      ".com/AssetMantle/modules/modules/splits/" +
      "internal/queries/split\242\002\003SQS\252\002\024Splits.Qu" +
      "eries.Split\312\002\024Splits\\Queries\\Split\342\002 Spl" +
      "its\\Queries\\Split\\GPBMetadata\352\002\026Splits::" +
      "Queries::Splitb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.splits.MappableProto.getDescriptor(),
        });
    internal_static_splits_queries_split_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_queries_split_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_queries_split_QueryResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "List", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.splits.MappableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
