// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/queries/split/queryRequest.proto

package com.splits.queries.split;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_queries_split_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_queries_split_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8modules/splits/internal/queries/split/" +
      "queryRequest.proto\022\024splits.queries.split" +
      "\032\035schema/ids/base/splitID.proto\"8\n\014Query" +
      "Request\022(\n\tsplit_i_d\030\001 \001(\0132\014.ids.SplitID" +
      "R\007splitIDB\345\001\n\030com.splits.queries.splitB\021" +
      "QueryRequestProtoP\001ZDgithub.com/AssetMan" +
      "tle/modules/modules/splits/internal/quer" +
      "ies/split\242\002\003SQS\252\002\024Splits.Queries.Split\312\002" +
      "\024Splits\\Queries\\Split\342\002 Splits\\Queries\\S" +
      "plit\\GPBMetadata\352\002\026Splits::Queries::Spli" +
      "tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.SplitIDProto.getDescriptor(),
        });
    internal_static_splits_queries_split_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_queries_split_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_queries_split_QueryRequest_descriptor,
        new java.lang.String[] { "SplitID", });
    com.ids.SplitIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
