// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/queries/split/service.proto

package com.splits.queries.split;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3modules/splits/internal/queries/split/" +
      "service.proto\022\024splits.queries.split\032\034goo" +
      "gle/api/annotations.proto\0328modules/split" +
      "s/internal/queries/split/queryRequest.pr" +
      "oto\0329modules/splits/internal/queries/spl" +
      "it/queryResponse.proto2\202\001\n\007Service\022w\n\006Ha" +
      "ndle\022\".splits.queries.split.QueryRequest" +
      "\032#.splits.queries.split.QueryResponse\"$\202" +
      "\323\344\223\002\036\022\034/mantle/splits/v1beta1/splitB\340\001\n\030" +
      "com.splits.queries.splitB\014ServiceProtoP\001" +
      "ZDgithub.com/AssetMantle/modules/modules" +
      "/splits/internal/queries/split\242\002\003SQS\252\002\024S" +
      "plits.Queries.Split\312\002\024Splits\\Queries\\Spl" +
      "it\342\002 Splits\\Queries\\Split\\GPBMetadata\352\002\026" +
      "Splits::Queries::Splitb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.splits.queries.split.QueryRequestProto.getDescriptor(),
          com.splits.queries.split.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.splits.queries.split.QueryRequestProto.getDescriptor();
    com.splits.queries.split.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
