// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/deputize/service.proto

package com.assets.transactions.deputize;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;modules/assets/internal/transactions/d" +
      "eputize/service.proto\022\034assets.transactio" +
      "ns.deputize\032\034google/api/annotations.prot" +
      "o\032;modules/assets/internal/transactions/" +
      "deputize/message.proto\032Gmodules/assets/i" +
      "nternal/transactions/deputize/transactio" +
      "nResponse.proto2\217\001\n\007Service\022\203\001\n\006Handle\022%" +
      ".assets.transactions.deputize.Message\0321." +
      "assets.transactions.deputize.Transaction" +
      "Response\"\037\202\323\344\223\002\031\"\027/mantle/assets/deputiz" +
      "eB\220\002\n com.assets.transactions.deputizeB\014" +
      "ServiceProtoP\001ZLgithub.com/AssetMantle/m" +
      "odules/modules/assets/internal/transacti" +
      "ons/deputize\242\002\003ATD\252\002\034Assets.Transactions" +
      ".Deputize\312\002\034Assets\\Transactions\\Deputize" +
      "\342\002(Assets\\Transactions\\Deputize\\GPBMetad" +
      "ata\352\002\036Assets::Transactions::Deputizeb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assets.transactions.deputize.MessageProto.getDescriptor(),
          com.assets.transactions.deputize.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assets.transactions.deputize.MessageProto.getDescriptor();
    com.assets.transactions.deputize.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
