// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/deputize/transactionResponse.proto

package com.assets.transactions.deputize;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_deputize_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_deputize_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nGmodules/assets/internal/transactions/d" +
      "eputize/transactionResponse.proto\022\034asset" +
      "s.transactions.deputize\"\025\n\023TransactionRe" +
      "sponseB\234\002\n com.assets.transactions.deput" +
      "izeB\030TransactionResponseProtoP\001ZLgithub." +
      "com/AssetMantle/modules/modules/assets/i" +
      "nternal/transactions/deputize\242\002\003ATD\252\002\034As" +
      "sets.Transactions.Deputize\312\002\034Assets\\Tran" +
      "sactions\\Deputize\342\002(Assets\\Transactions\\" +
      "Deputize\\GPBMetadata\352\002\036Assets::Transacti" +
      "ons::Deputizeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_deputize_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_deputize_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_deputize_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
