// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/documents/base/document.proto

package com.documents;

public final class DocumentProto {
  private DocumentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_documents_Document_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_documents_Document_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$schema/documents/base/document.proto\022\t" +
      "documents\032&schema/ids/base/classificatio" +
      "nID.proto\032&schema/qualified/base/immutab" +
      "les.proto\032$schema/qualified/base/mutable" +
      "s.proto\032\024gogoproto/gogo.proto\"\275\001\n\010Docume" +
      "nt\022C\n\022classification_i_d\030\001 \001(\0132\025.ids.Cla" +
      "ssificationIDR\020classificationID\0225\n\nimmut" +
      "ables\030\002 \001(\0132\025.qualified.ImmutablesR\nimmu" +
      "tables\022/\n\010mutables\030\003 \001(\0132\023.qualified.Mut" +
      "ablesR\010mutables:\004\210\240\037\000B\230\001\n\rcom.documentsB" +
      "\rDocumentProtoP\001Z4github.com/AssetMantle" +
      "/modules/schema/documents/base\242\002\003DXX\252\002\tD" +
      "ocuments\312\002\tDocuments\342\002\025Documents\\GPBMeta" +
      "data\352\002\tDocumentsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.qualified.ImmutablesProto.getDescriptor(),
          com.qualified.MutablesProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_documents_Document_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_documents_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_documents_Document_descriptor,
        new java.lang.String[] { "ClassificationID", "Immutables", "Mutables", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.ClassificationIDProto.getDescriptor();
    com.qualified.ImmutablesProto.getDescriptor();
    com.qualified.MutablesProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
