// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/queries/order/queryRequest.proto

package com.orders.queries.order;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_queries_order_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_queries_order_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8modules/orders/internal/queries/order/" +
      "queryRequest.proto\022\024orders.queries.order" +
      "\032\035schema/ids/base/orderID.proto\"8\n\014Query" +
      "Request\022(\n\torder_i_d\030\001 \001(\0132\014.ids.OrderID" +
      "R\007orderIDB\345\001\n\030com.orders.queries.orderB\021" +
      "QueryRequestProtoP\001ZDgithub.com/AssetMan" +
      "tle/modules/modules/orders/internal/quer" +
      "ies/order\242\002\003OQO\252\002\024Orders.Queries.Order\312\002" +
      "\024Orders\\Queries\\Order\342\002 Orders\\Queries\\O" +
      "rder\\GPBMetadata\352\002\026Orders::Queries::Orde" +
      "rb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.OrderIDProto.getDescriptor(),
        });
    internal_static_orders_queries_order_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_queries_order_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_queries_order_QueryRequest_descriptor,
        new java.lang.String[] { "OrderID", });
    com.ids.OrderIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
