// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mutate/message.proto

package com.assets.transactions.mutate;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_mutate_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_mutate_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/assets/internal/transactions/m" +
      "utate/message.proto\022\032assets.transactions" +
      ".mutate\032\035schema/ids/base/assetID.proto\032 " +
      "schema/ids/base/identityID.proto\032$schema" +
      "/lists/base/propertyList.proto\"\203\002\n\007Messa" +
      "ge\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_i_d\030\002 \001(\013" +
      "2\017.ids.IdentityIDR\006fromID\022(\n\tasset_i_d\030\003" +
      " \001(\0132\014.ids.AssetIDR\007assetID\022K\n\027mutable_m" +
      "eta_properties\030\004 \001(\0132\023.lists.PropertyLis" +
      "tR\025mutableMetaProperties\022B\n\022mutable_prop" +
      "erties\030\005 \001(\0132\023.lists.PropertyListR\021mutab" +
      "lePropertiesB\204\002\n\036com.assets.transactions" +
      ".mutateB\014MessageProtoP\001ZJgithub.com/Asse" +
      "tMantle/modules/modules/assets/internal/" +
      "transactions/mutate\242\002\003ATM\252\002\032Assets.Trans" +
      "actions.Mutate\312\002\032Assets\\Transactions\\Mut" +
      "ate\342\002&Assets\\Transactions\\Mutate\\GPBMeta" +
      "data\352\002\034Assets::Transactions::Mutateb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AssetIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_assets_transactions_mutate_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_mutate_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_mutate_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "AssetID", "MutableMetaProperties", "MutableProperties", });
    com.ids.AssetIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
