// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mutate/service.proto

package com.assets.transactions.mutate;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/assets/internal/transactions/m" +
      "utate/service.proto\022\032assets.transactions" +
      ".mutate\032\034google/api/annotations.proto\0329m" +
      "odules/assets/internal/transactions/muta" +
      "te/message.proto\032Emodules/assets/interna" +
      "l/transactions/mutate/transactionRespons" +
      "e.proto2\210\001\n\007Service\022}\n\006Handle\022#.assets.t" +
      "ransactions.mutate.Message\032/.assets.tran" +
      "sactions.mutate.TransactionResponse\"\035\202\323\344" +
      "\223\002\027\"\025/mantle/assets/mutateB\204\002\n\036com.asset" +
      "s.transactions.mutateB\014ServiceProtoP\001ZJg" +
      "ithub.com/AssetMantle/modules/modules/as" +
      "sets/internal/transactions/mutate\242\002\003ATM\252" +
      "\002\032Assets.Transactions.Mutate\312\002\032Assets\\Tr" +
      "ansactions\\Mutate\342\002&Assets\\Transactions\\" +
      "Mutate\\GPBMetadata\352\002\034Assets::Transaction" +
      "s::Mutateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assets.transactions.mutate.MessageProto.getDescriptor(),
          com.assets.transactions.mutate.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assets.transactions.mutate.MessageProto.getDescriptor();
    com.assets.transactions.mutate.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
