// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/revoke/service.proto

package com.assets.transactions.revoke;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/assets/internal/transactions/r" +
      "evoke/service.proto\022\032assets.transactions" +
      ".revoke\032\034google/api/annotations.proto\0329m" +
      "odules/assets/internal/transactions/revo" +
      "ke/message.proto\032Emodules/assets/interna" +
      "l/transactions/revoke/transactionRespons" +
      "e.proto2\210\001\n\007Service\022}\n\006Handle\022#.assets.t" +
      "ransactions.revoke.Message\032/.assets.tran" +
      "sactions.revoke.TransactionResponse\"\035\202\323\344" +
      "\223\002\027\"\025/mantle/assets/revokeB\204\002\n\036com.asset" +
      "s.transactions.revokeB\014ServiceProtoP\001ZJg" +
      "ithub.com/AssetMantle/modules/modules/as" +
      "sets/internal/transactions/revoke\242\002\003ATR\252" +
      "\002\032Assets.Transactions.Revoke\312\002\032Assets\\Tr" +
      "ansactions\\Revoke\342\002&Assets\\Transactions\\" +
      "Revoke\\GPBMetadata\352\002\034Assets::Transaction" +
      "s::Revokeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assets.transactions.revoke.MessageProto.getDescriptor(),
          com.assets.transactions.revoke.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assets.transactions.revoke.MessageProto.getDescriptor();
    com.assets.transactions.revoke.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
