// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/revoke/transactionResponse.proto

package com.assets.transactions.revoke;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_revoke_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_revoke_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEmodules/assets/internal/transactions/r" +
      "evoke/transactionResponse.proto\022\032assets." +
      "transactions.revoke\"\025\n\023TransactionRespon" +
      "seB\220\002\n\036com.assets.transactions.revokeB\030T" +
      "ransactionResponseProtoP\001ZJgithub.com/As" +
      "setMantle/modules/modules/assets/interna" +
      "l/transactions/revoke\242\002\003ATR\252\002\032Assets.Tra" +
      "nsactions.Revoke\312\002\032Assets\\Transactions\\R" +
      "evoke\342\002&Assets\\Transactions\\Revoke\\GPBMe" +
      "tadata\352\002\034Assets::Transactions::Revokeb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_revoke_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_revoke_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_revoke_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
