// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/revoke/transactionResponse.proto

package com.assets.transactions.revoke;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.transactions.revoke.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
