// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/define/message.proto

package com.assets.transactions.define;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_define_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_define_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/assets/internal/transactions/d" +
      "efine/message.proto\022\032assets.transactions" +
      ".define\032 schema/ids/base/identityID.prot" +
      "o\032$schema/lists/base/propertyList.proto\"" +
      "\362\002\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_" +
      "i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromID\022O\n\031im" +
      "mutable_meta_properties\030\003 \001(\0132\023.lists.Pr" +
      "opertyListR\027immutableMetaProperties\022F\n\024i" +
      "mmutable_properties\030\004 \001(\0132\023.lists.Proper" +
      "tyListR\023immutableProperties\022K\n\027mutable_m" +
      "eta_properties\030\005 \001(\0132\023.lists.PropertyLis" +
      "tR\025mutableMetaProperties\022B\n\022mutable_prop" +
      "erties\030\006 \001(\0132\023.lists.PropertyListR\021mutab" +
      "lePropertiesB\204\002\n\036com.assets.transactions" +
      ".defineB\014MessageProtoP\001ZJgithub.com/Asse" +
      "tMantle/modules/modules/assets/internal/" +
      "transactions/define\242\002\003ATD\252\002\032Assets.Trans" +
      "actions.Define\312\002\032Assets\\Transactions\\Def" +
      "ine\342\002&Assets\\Transactions\\Define\\GPBMeta" +
      "data\352\002\034Assets::Transactions::Defineb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_assets_transactions_define_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_define_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_define_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
