// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/define/transactionResponse.proto

package com.assets.transactions.define;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_define_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_define_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEmodules/assets/internal/transactions/d" +
      "efine/transactionResponse.proto\022\032assets." +
      "transactions.define\"C\n\023TransactionRespon" +
      "se\022,\n\022classification_i_d\030\001 \001(\tR\020classifi" +
      "cationIDB\220\002\n\036com.assets.transactions.def" +
      "ineB\030TransactionResponseProtoP\001ZJgithub." +
      "com/AssetMantle/modules/modules/assets/i" +
      "nternal/transactions/define\242\002\003ATD\252\002\032Asse" +
      "ts.Transactions.Define\312\002\032Assets\\Transact" +
      "ions\\Define\342\002&Assets\\Transactions\\Define" +
      "\\GPBMetadata\352\002\034Assets::Transactions::Def" +
      "ineb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_define_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_define_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_define_TransactionResponse_descriptor,
        new java.lang.String[] { "ClassificationID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
