// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/issue/message.proto

package com.identities.transactions.issue;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_issue_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_issue_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<modules/identities/internal/transactio" +
      "ns/issue/message.proto\022\035identities.trans" +
      "actions.issue\032&schema/ids/base/classific" +
      "ationID.proto\032 schema/ids/base/identityI" +
      "D.proto\032$schema/lists/base/propertyList." +
      "proto\"\307\003\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n" +
      "\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromID" +
      "\022\016\n\002to\030\003 \001(\tR\002to\022C\n\022classification_i_d\030\004" +
      " \001(\0132\025.ids.ClassificationIDR\020classificat" +
      "ionID\022O\n\031immutable_meta_properties\030\005 \001(\013" +
      "2\023.lists.PropertyListR\027immutableMetaProp" +
      "erties\022F\n\024immutable_properties\030\006 \001(\0132\023.l" +
      "ists.PropertyListR\023immutableProperties\022K" +
      "\n\027mutable_meta_properties\030\007 \001(\0132\023.lists." +
      "PropertyListR\025mutableMetaProperties\022B\n\022m" +
      "utable_properties\030\010 \001(\0132\023.lists.Property" +
      "ListR\021mutablePropertiesB\226\002\n!com.identiti" +
      "es.transactions.issueB\014MessageProtoP\001ZMg" +
      "ithub.com/AssetMantle/modules/modules/id" +
      "entities/internal/transactions/issue\242\002\003I" +
      "TI\252\002\035Identities.Transactions.Issue\312\002\035Ide" +
      "ntities\\Transactions\\Issue\342\002)Identities\\" +
      "Transactions\\Issue\\GPBMetadata\352\002\037Identit" +
      "ies::Transactions::Issueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_identities_transactions_issue_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_issue_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_issue_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "To", "ClassificationID", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
