// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/issue/service.proto

package com.identities.transactions.issue;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<modules/identities/internal/transactio" +
      "ns/issue/service.proto\022\035identities.trans" +
      "actions.issue\032\034google/api/annotations.pr" +
      "oto\032<modules/identities/internal/transac" +
      "tions/issue/message.proto\032Hmodules/ident" +
      "ities/internal/transactions/issue/transa" +
      "ctionResponse.proto2\222\001\n\007Service\022\206\001\n\006Hand" +
      "le\022&.identities.transactions.issue.Messa" +
      "ge\0322.identities.transactions.issue.Trans" +
      "actionResponse\" \202\323\344\223\002\032\"\030/mantle/identiti" +
      "es/issueB\226\002\n!com.identities.transactions" +
      ".issueB\014ServiceProtoP\001ZMgithub.com/Asset" +
      "Mantle/modules/modules/identities/intern" +
      "al/transactions/issue\242\002\003ITI\252\002\035Identities" +
      ".Transactions.Issue\312\002\035Identities\\Transac" +
      "tions\\Issue\342\002)Identities\\Transactions\\Is" +
      "sue\\GPBMetadata\352\002\037Identities::Transactio" +
      "ns::Issueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.issue.MessageProto.getDescriptor(),
          com.identities.transactions.issue.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.issue.MessageProto.getDescriptor();
    com.identities.transactions.issue.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
