// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/issue/transactionResponse.proto

package com.identities.transactions.issue;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_issue_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_issue_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHmodules/identities/internal/transactio" +
      "ns/issue/transactionResponse.proto\022\035iden" +
      "tities.transactions.issue\"7\n\023Transaction" +
      "Response\022 \n\014identity_i_d\030\001 \001(\tR\nidentity" +
      "IDB\242\002\n!com.identities.transactions.issue" +
      "B\030TransactionResponseProtoP\001ZMgithub.com" +
      "/AssetMantle/modules/modules/identities/" +
      "internal/transactions/issue\242\002\003ITI\252\002\035Iden" +
      "tities.Transactions.Issue\312\002\035Identities\\T" +
      "ransactions\\Issue\342\002)Identities\\Transacti" +
      "ons\\Issue\\GPBMetadata\352\002\037Identities::Tran" +
      "sactions::Issueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_issue_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_issue_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_issue_TransactionResponse_descriptor,
        new java.lang.String[] { "IdentityID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
