// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/issue/transactionResponse.proto

package com.identities.transactions.issue;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.transactions.issue.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identity_i_d = 1 [json_name = "identityID"];</code>
   * @return The identityID.
   */
  java.lang.String getIdentityID();
  /**
   * <code>string identity_i_d = 1 [json_name = "identityID"];</code>
   * @return The bytes for identityID.
   */
  com.google.protobuf.ByteString
      getIdentityIDBytes();
}
