// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/queries/maintainer/queryResponse.proto

package com.maintainers.queries.maintainer;

public final class QueryResponseProto {
  private QueryResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maintainers_queries_maintainer_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maintainers_queries_maintainer_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/maintainers/internal/queries/m" +
      "aintainer/queryResponse.proto\022\036maintaine" +
      "rs.queries.maintainer\032\024gogoproto/gogo.pr" +
      "oto\0324modules/maintainers/internal/mappab" +
      "le/mappable.proto\"p\n\rQueryResponse\022\030\n\007su" +
      "ccess\030\001 \001(\010R\007success\022\024\n\005error\030\002 \001(\tR\005err" +
      "or\022)\n\004list\030\003 \003(\0132\025.maintainers.MappableR" +
      "\004list:\004\210\240\037\000B\242\002\n\"com.maintainers.queries." +
      "maintainerB\022QueryResponseProtoP\001ZNgithub" +
      ".com/AssetMantle/modules/modules/maintai" +
      "ners/internal/queries/maintainer\242\002\003MQM\252\002" +
      "\036Maintainers.Queries.Maintainer\312\002\036Mainta" +
      "iners\\Queries\\Maintainer\342\002*Maintainers\\Q" +
      "ueries\\Maintainer\\GPBMetadata\352\002 Maintain" +
      "ers::Queries::Maintainerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.maintainers.MappableProto.getDescriptor(),
        });
    internal_static_maintainers_queries_maintainer_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maintainers_queries_maintainer_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maintainers_queries_maintainer_QueryResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "List", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.maintainers.MappableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
