// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/queries/maintainer/queryRequest.proto

package com.maintainers.queries.maintainer;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maintainers_queries_maintainer_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maintainers_queries_maintainer_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBmodules/maintainers/internal/queries/m" +
      "aintainer/queryRequest.proto\022\036maintainer" +
      "s.queries.maintainer\032\"schema/ids/base/ma" +
      "intainerID.proto\032\024gogoproto/gogo.proto\"M" +
      "\n\014QueryRequest\0227\n\016maintainer_i_d\030\001 \001(\0132\021" +
      ".ids.MaintainerIDR\014maintainerID:\004\210\240\037\000B\241\002" +
      "\n\"com.maintainers.queries.maintainerB\021Qu" +
      "eryRequestProtoP\001ZNgithub.com/AssetMantl" +
      "e/modules/modules/maintainers/internal/q" +
      "ueries/maintainer\242\002\003MQM\252\002\036Maintainers.Qu" +
      "eries.Maintainer\312\002\036Maintainers\\Queries\\M" +
      "aintainer\342\002*Maintainers\\Queries\\Maintain" +
      "er\\GPBMetadata\352\002 Maintainers::Queries::M" +
      "aintainerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.MaintainerIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_maintainers_queries_maintainer_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maintainers_queries_maintainer_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maintainers_queries_maintainer_QueryRequest_descriptor,
        new java.lang.String[] { "MaintainerID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.MaintainerIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
