// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/queries/maintainer/service.proto

package com.maintainers.queries.maintainer;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/maintainers/internal/queries/m" +
      "aintainer/service.proto\022\036maintainers.que" +
      "ries.maintainer\032\034google/api/annotations." +
      "proto\032Bmodules/maintainers/internal/quer" +
      "ies/maintainer/queryRequest.proto\032Cmodul" +
      "es/maintainers/internal/queries/maintain" +
      "er/queryResponse.proto2\241\001\n\007Service\022\225\001\n\006H" +
      "andle\022,.maintainers.queries.maintainer.Q" +
      "ueryRequest\032-.maintainers.queries.mainta" +
      "iner.QueryResponse\".\202\323\344\223\002(\022&/mantle/main" +
      "tainers/v1beta1/maintainerB\234\002\n\"com.maint" +
      "ainers.queries.maintainerB\014ServiceProtoP" +
      "\001ZNgithub.com/AssetMantle/modules/module" +
      "s/maintainers/internal/queries/maintaine" +
      "r\242\002\003MQM\252\002\036Maintainers.Queries.Maintainer" +
      "\312\002\036Maintainers\\Queries\\Maintainer\342\002*Main" +
      "tainers\\Queries\\Maintainer\\GPBMetadata\352\002" +
      " Maintainers::Queries::Maintainerb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.maintainers.queries.maintainer.QueryRequestProto.getDescriptor(),
          com.maintainers.queries.maintainer.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.maintainers.queries.maintainer.QueryRequestProto.getDescriptor();
    com.maintainers.queries.maintainer.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
