// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/deputize/message.proto

package com.identities.transactions.deputize;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_deputize_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_deputize_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?modules/identities/internal/transactio" +
      "ns/deputize/message.proto\022 identities.tr" +
      "ansactions.deputize\032&schema/ids/base/cla" +
      "ssificationID.proto\032 schema/ids/base/ide" +
      "ntityID.proto\032$schema/lists/base/propert" +
      "yList.proto\"\222\004\n\007Message\022\022\n\004from\030\001 \001(\tR\004f" +
      "rom\022)\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006" +
      "fromID\022%\n\006to_i_d\030\003 \001(\0132\017.ids.IdentityIDR" +
      "\004toID\022C\n\022classification_i_d\030\004 \001(\0132\025.ids." +
      "ClassificationIDR\020classificationID\022H\n\025ma" +
      "intained_properties\030\005 \001(\0132\023.lists.Proper" +
      "tyListR\024maintainedProperties\022$\n\016can_mint" +
      "_asset\030\006 \001(\010R\014canMintAsset\022$\n\016can_burn_a" +
      "sset\030\007 \001(\010R\014canBurnAsset\0220\n\024can_renumera" +
      "te_asset\030\010 \001(\010R\022canRenumerateAsset\022,\n\022ca" +
      "n_add_maintainer\030\t \001(\010R\020canAddMaintainer" +
      "\0222\n\025can_remove_maintainer\030\n \001(\010R\023canRemo" +
      "veMaintainer\0222\n\025can_mutate_maintainer\030\013 " +
      "\001(\010R\023canMutateMaintainerB\250\002\n$com.identit" +
      "ies.transactions.deputizeB\014MessageProtoP" +
      "\001ZPgithub.com/AssetMantle/modules/module" +
      "s/identities/internal/transactions/deput" +
      "ize\242\002\003ITD\252\002 Identities.Transactions.Depu" +
      "tize\312\002 Identities\\Transactions\\Deputize\342" +
      "\002,Identities\\Transactions\\Deputize\\GPBMe" +
      "tadata\352\002\"Identities::Transactions::Deput" +
      "izeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_identities_transactions_deputize_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_deputize_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_deputize_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", "MaintainedProperties", "CanMintAsset", "CanBurnAsset", "CanRenumerateAsset", "CanAddMaintainer", "CanRemoveMaintainer", "CanMutateMaintainer", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
