// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/deputize/service.proto

package com.identities.transactions.deputize;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?modules/identities/internal/transactio" +
      "ns/deputize/service.proto\022 identities.tr" +
      "ansactions.deputize\032\034google/api/annotati" +
      "ons.proto\032?modules/identities/internal/t" +
      "ransactions/deputize/message.proto\032Kmodu" +
      "les/identities/internal/transactions/dep" +
      "utize/transactionResponse.proto2\233\001\n\007Serv" +
      "ice\022\217\001\n\006Handle\022).identities.transactions" +
      ".deputize.Message\0325.identities.transacti" +
      "ons.deputize.TransactionResponse\"#\202\323\344\223\002\035" +
      "\"\033/mantle/identities/deputizeB\250\002\n$com.id" +
      "entities.transactions.deputizeB\014ServiceP" +
      "rotoP\001ZPgithub.com/AssetMantle/modules/m" +
      "odules/identities/internal/transactions/" +
      "deputize\242\002\003ITD\252\002 Identities.Transactions" +
      ".Deputize\312\002 Identities\\Transactions\\Depu" +
      "tize\342\002,Identities\\Transactions\\Deputize\\" +
      "GPBMetadata\352\002\"Identities::Transactions::" +
      "Deputizeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.deputize.MessageProto.getDescriptor(),
          com.identities.transactions.deputize.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.deputize.MessageProto.getDescriptor();
    com.identities.transactions.deputize.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
