// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/deputize/transactionResponse.proto

package com.identities.transactions.deputize;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_deputize_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_deputize_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nKmodules/identities/internal/transactio" +
      "ns/deputize/transactionResponse.proto\022 i" +
      "dentities.transactions.deputize\"\025\n\023Trans" +
      "actionResponseB\264\002\n$com.identities.transa" +
      "ctions.deputizeB\030TransactionResponseProt" +
      "oP\001ZPgithub.com/AssetMantle/modules/modu" +
      "les/identities/internal/transactions/dep" +
      "utize\242\002\003ITD\252\002 Identities.Transactions.De" +
      "putize\312\002 Identities\\Transactions\\Deputiz" +
      "e\342\002,Identities\\Transactions\\Deputize\\GPB" +
      "Metadata\352\002\"Identities::Transactions::Dep" +
      "utizeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_deputize_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_deputize_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_deputize_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
