// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/queries/asset/queryResponse.proto

package com.assets.queries.asset;

public final class QueryResponseProto {
  private QueryResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_queries_asset_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_queries_asset_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/assets/internal/queries/asset/" +
      "queryResponse.proto\022\024assets.queries.asse" +
      "t\032\024gogoproto/gogo.proto\032/modules/assets/" +
      "internal/mappable/mappable.proto\"k\n\rQuer" +
      "yResponse\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005e" +
      "rror\030\002 \001(\tR\005error\022$\n\004list\030\003 \003(\0132\020.assets" +
      ".MappableR\004list:\004\210\240\037\000B\346\001\n\030com.assets.que" +
      "ries.assetB\022QueryResponseProtoP\001ZDgithub" +
      ".com/AssetMantle/modules/modules/assets/" +
      "internal/queries/asset\242\002\003AQA\252\002\024Assets.Qu" +
      "eries.Asset\312\002\024Assets\\Queries\\Asset\342\002 Ass" +
      "ets\\Queries\\Asset\\GPBMetadata\352\002\026Assets::" +
      "Queries::Assetb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.assets.MappableProto.getDescriptor(),
        });
    internal_static_assets_queries_asset_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_queries_asset_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_queries_asset_QueryResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "List", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.assets.MappableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
