// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/queries/asset/queryRequest.proto

package com.assets.queries.asset;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_queries_asset_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_queries_asset_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8modules/assets/internal/queries/asset/" +
      "queryRequest.proto\022\024assets.queries.asset" +
      "\032\035schema/ids/base/assetID.proto\"8\n\014Query" +
      "Request\022(\n\tasset_i_d\030\001 \001(\0132\014.ids.AssetID" +
      "R\007assetIDB\345\001\n\030com.assets.queries.assetB\021" +
      "QueryRequestProtoP\001ZDgithub.com/AssetMan" +
      "tle/modules/modules/assets/internal/quer" +
      "ies/asset\242\002\003AQA\252\002\024Assets.Queries.Asset\312\002" +
      "\024Assets\\Queries\\Asset\342\002 Assets\\Queries\\A" +
      "sset\\GPBMetadata\352\002\026Assets::Queries::Asse" +
      "tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AssetIDProto.getDescriptor(),
        });
    internal_static_assets_queries_asset_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_queries_asset_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_queries_asset_QueryRequest_descriptor,
        new java.lang.String[] { "AssetID", });
    com.ids.AssetIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
