// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/quash/message.proto

package com.identities.transactions.quash;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_quash_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_quash_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<modules/identities/internal/transactio" +
      "ns/quash/message.proto\022\035identities.trans" +
      "actions.quash\032 schema/ids/base/identityI" +
      "D.proto\"{\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)" +
      "\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromI" +
      "D\0221\n\014identity_i_d\030\003 \001(\0132\017.ids.IdentityID" +
      "R\nidentityIDB\226\002\n!com.identities.transact" +
      "ions.quashB\014MessageProtoP\001ZMgithub.com/A" +
      "ssetMantle/modules/modules/identities/in" +
      "ternal/transactions/quash\242\002\003ITQ\252\002\035Identi" +
      "ties.Transactions.Quash\312\002\035Identities\\Tra" +
      "nsactions\\Quash\342\002)Identities\\Transaction" +
      "s\\Quash\\GPBMetadata\352\002\037Identities::Transa" +
      "ctions::Quashb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_identities_transactions_quash_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_quash_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_quash_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "IdentityID", });
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
