// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/quash/service.proto

package com.identities.transactions.quash;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<modules/identities/internal/transactio" +
      "ns/quash/service.proto\022\035identities.trans" +
      "actions.quash\032\034google/api/annotations.pr" +
      "oto\032<modules/identities/internal/transac" +
      "tions/quash/message.proto\032Hmodules/ident" +
      "ities/internal/transactions/quash/transa" +
      "ctionResponse.proto2\222\001\n\007Service\022\206\001\n\006Hand" +
      "le\022&.identities.transactions.quash.Messa" +
      "ge\0322.identities.transactions.quash.Trans" +
      "actionResponse\" \202\323\344\223\002\032\"\030/mantle/identiti" +
      "es/quashB\226\002\n!com.identities.transactions" +
      ".quashB\014ServiceProtoP\001ZMgithub.com/Asset" +
      "Mantle/modules/modules/identities/intern" +
      "al/transactions/quash\242\002\003ITQ\252\002\035Identities" +
      ".Transactions.Quash\312\002\035Identities\\Transac" +
      "tions\\Quash\342\002)Identities\\Transactions\\Qu" +
      "ash\\GPBMetadata\352\002\037Identities::Transactio" +
      "ns::Quashb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.quash.MessageProto.getDescriptor(),
          com.identities.transactions.quash.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.quash.MessageProto.getDescriptor();
    com.identities.transactions.quash.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
