// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/quash/transactionResponse.proto

package com.identities.transactions.quash;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_quash_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_quash_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHmodules/identities/internal/transactio" +
      "ns/quash/transactionResponse.proto\022\035iden" +
      "tities.transactions.quash\"\025\n\023Transaction" +
      "ResponseB\242\002\n!com.identities.transactions" +
      ".quashB\030TransactionResponseProtoP\001ZMgith" +
      "ub.com/AssetMantle/modules/modules/ident" +
      "ities/internal/transactions/quash\242\002\003ITQ\252" +
      "\002\035Identities.Transactions.Quash\312\002\035Identi" +
      "ties\\Transactions\\Quash\342\002)Identities\\Tra" +
      "nsactions\\Quash\\GPBMetadata\352\002\037Identities" +
      "::Transactions::Quashb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_quash_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_quash_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_quash_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
