// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/renumerate/message.proto

package com.assets.transactions.renumerate;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_renumerate_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_renumerate_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/assets/internal/transactions/r" +
      "enumerate/message.proto\022\036assets.transact" +
      "ions.renumerate\032\035schema/ids/base/assetID" +
      ".proto\032 schema/ids/base/identityID.proto" +
      "\"r\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_" +
      "i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromID\022(\n\tas" +
      "set_i_d\030\003 \001(\0132\014.ids.AssetIDR\007assetIDB\234\002\n" +
      "\"com.assets.transactions.renumerateB\014Mes" +
      "sageProtoP\001ZNgithub.com/AssetMantle/modu" +
      "les/modules/assets/internal/transactions" +
      "/renumerate\242\002\003ATR\252\002\036Assets.Transactions." +
      "Renumerate\312\002\036Assets\\Transactions\\Renumer" +
      "ate\342\002*Assets\\Transactions\\Renumerate\\GPB" +
      "Metadata\352\002 Assets::Transactions::Renumer" +
      "ateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AssetIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_assets_transactions_renumerate_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_renumerate_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_renumerate_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "AssetID", });
    com.ids.AssetIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
