// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/renumerate/service.proto

package com.assets.transactions.renumerate;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/assets/internal/transactions/r" +
      "enumerate/service.proto\022\036assets.transact" +
      "ions.renumerate\032\034google/api/annotations." +
      "proto\032=modules/assets/internal/transacti" +
      "ons/renumerate/message.proto\032Imodules/as" +
      "sets/internal/transactions/renumerate/tr" +
      "ansactionResponse.proto2\225\001\n\007Service\022\211\001\n\006" +
      "Handle\022\'.assets.transactions.renumerate." +
      "Message\0323.assets.transactions.renumerate" +
      ".TransactionResponse\"!\202\323\344\223\002\033\"\031/mantle/as" +
      "sets/renumerateB\234\002\n\"com.assets.transacti" +
      "ons.renumerateB\014ServiceProtoP\001ZNgithub.c" +
      "om/AssetMantle/modules/modules/assets/in" +
      "ternal/transactions/renumerate\242\002\003ATR\252\002\036A" +
      "ssets.Transactions.Renumerate\312\002\036Assets\\T" +
      "ransactions\\Renumerate\342\002*Assets\\Transact" +
      "ions\\Renumerate\\GPBMetadata\352\002 Assets::Tr" +
      "ansactions::Renumerateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assets.transactions.renumerate.MessageProto.getDescriptor(),
          com.assets.transactions.renumerate.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assets.transactions.renumerate.MessageProto.getDescriptor();
    com.assets.transactions.renumerate.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
