// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/renumerate/transactionResponse.proto

package com.assets.transactions.renumerate;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_renumerate_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_renumerate_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nImodules/assets/internal/transactions/r" +
      "enumerate/transactionResponse.proto\022\036ass" +
      "ets.transactions.renumerate\"\025\n\023Transacti" +
      "onResponseB\250\002\n\"com.assets.transactions.r" +
      "enumerateB\030TransactionResponseProtoP\001ZNg" +
      "ithub.com/AssetMantle/modules/modules/as" +
      "sets/internal/transactions/renumerate\242\002\003" +
      "ATR\252\002\036Assets.Transactions.Renumerate\312\002\036A" +
      "ssets\\Transactions\\Renumerate\342\002*Assets\\T" +
      "ransactions\\Renumerate\\GPBMetadata\352\002 Ass" +
      "ets::Transactions::Renumerateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_renumerate_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_renumerate_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_renumerate_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
