// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/renumerate/transactionResponse.proto

package com.assets.transactions.renumerate;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.transactions.renumerate.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
