apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:
  name: client
  namespace: client-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: persistenceclient_seed_1
          image: persistence/persistenceclient:latest
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 2
              memory: 1024Mi