// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/deputize/message.proto

package com.orders.transactions.deputize;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_deputize_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_deputize_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;modules/orders/internal/transactions/d" +
      "eputize/message.proto\022\034orders.transactio" +
      "ns.deputize\032&schema/ids/base/classificat" +
      "ionID.proto\032 schema/ids/base/identityID." +
      "proto\032$schema/lists/base/propertyList.pr" +
      "oto\"\222\004\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010f" +
      "rom_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromID\022%" +
      "\n\006to_i_d\030\003 \001(\0132\017.ids.IdentityIDR\004toID\022C\n" +
      "\022classification_i_d\030\004 \001(\0132\025.ids.Classifi" +
      "cationIDR\020classificationID\022H\n\025maintained" +
      "_properties\030\005 \001(\0132\023.lists.PropertyListR\024" +
      "maintainedProperties\022$\n\016can_mint_asset\030\006" +
      " \001(\010R\014canMintAsset\022$\n\016can_burn_asset\030\007 \001" +
      "(\010R\014canBurnAsset\0220\n\024can_renumerate_asset" +
      "\030\010 \001(\010R\022canRenumerateAsset\022,\n\022can_add_ma" +
      "intainer\030\t \001(\010R\020canAddMaintainer\0222\n\025can_" +
      "remove_maintainer\030\n \001(\010R\023canRemoveMainta" +
      "iner\0222\n\025can_mutate_maintainer\030\013 \001(\010R\023can" +
      "MutateMaintainerB\220\002\n com.orders.transact" +
      "ions.deputizeB\014MessageProtoP\001ZLgithub.co" +
      "m/AssetMantle/modules/modules/orders/int" +
      "ernal/transactions/deputize\242\002\003OTD\252\002\034Orde" +
      "rs.Transactions.Deputize\312\002\034Orders\\Transa" +
      "ctions\\Deputize\342\002(Orders\\Transactions\\De" +
      "putize\\GPBMetadata\352\002\036Orders::Transaction" +
      "s::Deputizeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_orders_transactions_deputize_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_deputize_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_deputize_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", "MaintainedProperties", "CanMintAsset", "CanBurnAsset", "CanRenumerateAsset", "CanAddMaintainer", "CanRemoveMaintainer", "CanMutateMaintainer", });
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
