// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilities/test/schema/helpers/base/genesis.proto

package com.test;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0utilities/test/schema/helpers/base/gen" +
      "esis.proto\022\004test\032\024gogoproto/gogo.proto\0321" +
      "utilities/test/schema/helpers/base/mappa" +
      "ble.proto\032&schema/parameters/base/parame" +
      "ter.proto\"x\n\007Genesis\0220\n\tmappables\030\001 \003(\0132" +
      "\022.test.TestMappableR\tmappables\0225\n\nparame" +
      "ters\030\002 \003(\0132\025.parameters.ParameterR\nparam" +
      "eters:\004\210\240\037\000B\213\001\n\010com.testB\014GenesisProtoP\001" +
      "ZAgithub.com/AssetMantle/modules/utiliti" +
      "es/test/schema/helpers/base\242\002\003TXX\252\002\004Test" +
      "\312\002\004Test\342\002\020Test\\GPBMetadata\352\002\004Testb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.test.MappableProto.getDescriptor(),
          com.parameters.ParameterProto.getDescriptor(),
        });
    internal_static_test_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "Parameters", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.test.MappableProto.getDescriptor();
    com.parameters.ParameterProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
