// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/modify/message.proto

package com.orders.transactions.modify;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_modify_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_modify_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/orders/internal/transactions/m" +
      "odify/message.proto\022\032orders.transactions" +
      ".modify\032\024gogoproto/gogo.proto\032&schema/id" +
      "s/base/classificationID.proto\032 schema/id" +
      "s/base/identityID.proto\032\035schema/ids/base" +
      "/orderID.proto\032$schema/lists/base/proper" +
      "tyList.proto\032\036schema/types/base/height.p" +
      "roto\"\221\003\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010" +
      "from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006fromID\022" +
      "(\n\torder_i_d\030\003 \001(\0132\014.ids.OrderIDR\007orderI" +
      "D\022.\n\023maker_ownable_split\030\004 \001(\tR\021makerOwn" +
      "ableSplit\022.\n\023taker_ownable_split\030\005 \001(\tR\021" +
      "takerOwnableSplit\022,\n\nexpires_in\030\006 \001(\0132\r." +
      "types.HeightR\texpiresIn\022K\n\027mutable_meta_" +
      "properties\030\007 \001(\0132\023.lists.PropertyListR\025m" +
      "utableMetaProperties\022B\n\022mutable_properti" +
      "es\030\010 \001(\0132\023.lists.PropertyListR\021mutablePr" +
      "opertiesB\204\002\n\036com.orders.transactions.mod" +
      "ifyB\014MessageProtoP\001ZJgithub.com/AssetMan" +
      "tle/modules/modules/orders/internal/tran" +
      "sactions/modify\242\002\003OTM\252\002\032Orders.Transacti" +
      "ons.Modify\312\002\032Orders\\Transactions\\Modify\342" +
      "\002&Orders\\Transactions\\Modify\\GPBMetadata" +
      "\352\002\034Orders::Transactions::Modifyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.OrderIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
          com.types.HeightProto.getDescriptor(),
        });
    internal_static_orders_transactions_modify_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_modify_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_modify_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "OrderID", "MakerOwnableSplit", "TakerOwnableSplit", "ExpiresIn", "MutableMetaProperties", "MutableProperties", });
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.OrderIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
    com.types.HeightProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
