// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/take/message.proto

package com.orders.transactions.take;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_take_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_take_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/orders/internal/transactions/t" +
      "ake/message.proto\022\030orders.transactions.t" +
      "ake\032\024gogoproto/gogo.proto\032 schema/ids/ba" +
      "se/identityID.proto\032\035schema/ids/base/ord" +
      "erID.proto\"\242\001\n\007Message\022\022\n\004from\030\001 \001(\tR\004fr" +
      "om\022)\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006f" +
      "romID\022.\n\023taker_ownable_split\030\003 \001(\tR\021take" +
      "rOwnableSplit\022(\n\torder_i_d\030\004 \001(\0132\014.ids.O" +
      "rderIDR\007orderIDB\370\001\n\034com.orders.transacti" +
      "ons.takeB\014MessageProtoP\001ZHgithub.com/Ass" +
      "etMantle/modules/modules/orders/internal" +
      "/transactions/take\242\002\003OTT\252\002\030Orders.Transa" +
      "ctions.Take\312\002\030Orders\\Transactions\\Take\342\002" +
      "$Orders\\Transactions\\Take\\GPBMetadata\352\002\032" +
      "Orders::Transactions::Takeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.OrderIDProto.getDescriptor(),
        });
    internal_static_orders_transactions_take_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_take_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_take_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "TakerOwnableSplit", "OrderID", });
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.OrderIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
