// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/take/service.proto

package com.orders.transactions.take;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/orders/internal/transactions/t" +
      "ake/service.proto\022\030orders.transactions.t" +
      "ake\032\034google/api/annotations.proto\0327modul" +
      "es/orders/internal/transactions/take/mes" +
      "sage.proto\032Cmodules/orders/internal/tran" +
      "sactions/take/transactionResponse.proto2" +
      "\202\001\n\007Service\022w\n\006Handle\022!.orders.transacti" +
      "ons.take.Message\032-.orders.transactions.t" +
      "ake.TransactionResponse\"\033\202\323\344\223\002\025\"\023/mantle" +
      "/orders/takeB\370\001\n\034com.orders.transactions" +
      ".takeB\014ServiceProtoP\001ZHgithub.com/AssetM" +
      "antle/modules/modules/orders/internal/tr" +
      "ansactions/take\242\002\003OTT\252\002\030Orders.Transacti" +
      "ons.Take\312\002\030Orders\\Transactions\\Take\342\002$Or" +
      "ders\\Transactions\\Take\\GPBMetadata\352\002\032Ord" +
      "ers::Transactions::Takeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.orders.transactions.take.MessageProto.getDescriptor(),
          com.orders.transactions.take.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.orders.transactions.take.MessageProto.getDescriptor();
    com.orders.transactions.take.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
