// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/take/transactionResponse.proto

package com.orders.transactions.take;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_take_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_take_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/orders/internal/transactions/t" +
      "ake/transactionResponse.proto\022\030orders.tr" +
      "ansactions.take\"\025\n\023TransactionResponseB\204" +
      "\002\n\034com.orders.transactions.takeB\030Transac" +
      "tionResponseProtoP\001ZHgithub.com/AssetMan" +
      "tle/modules/modules/orders/internal/tran" +
      "sactions/take\242\002\003OTT\252\002\030Orders.Transaction" +
      "s.Take\312\002\030Orders\\Transactions\\Take\342\002$Orde" +
      "rs\\Transactions\\Take\\GPBMetadata\352\002\032Order" +
      "s::Transactions::Takeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_take_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_take_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_take_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
