// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/mutate/message.proto

package com.identities.transactions.mutate;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_mutate_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_mutate_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/identities/internal/transactio" +
      "ns/mutate/message.proto\022\036identities.tran" +
      "sactions.mutate\032 schema/ids/base/identit" +
      "yID.proto\032$schema/lists/base/propertyLis" +
      "t.proto\"\214\002\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022" +
      ")\n\010from_i_d\030\002 \001(\0132\017.ids.IdentityIDR\006from" +
      "ID\0221\n\014identity_i_d\030\003 \001(\0132\017.ids.IdentityI" +
      "DR\nidentityID\022K\n\027mutable_meta_properties" +
      "\030\004 \001(\0132\023.lists.PropertyListR\025mutableMeta" +
      "Properties\022B\n\022mutable_properties\030\005 \001(\0132\023" +
      ".lists.PropertyListR\021mutablePropertiesB\234" +
      "\002\n\"com.identities.transactions.mutateB\014M" +
      "essageProtoP\001ZNgithub.com/AssetMantle/mo" +
      "dules/modules/identities/internal/transa" +
      "ctions/mutate\242\002\003ITM\252\002\036Identities.Transac" +
      "tions.Mutate\312\002\036Identities\\Transactions\\M" +
      "utate\342\002*Identities\\Transactions\\Mutate\\G" +
      "PBMetadata\352\002 Identities::Transactions::M" +
      "utateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
        });
    internal_static_identities_transactions_mutate_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_mutate_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_mutate_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "IdentityID", "MutableMetaProperties", "MutableProperties", });
    com.ids.IdentityIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
