// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/mutate/transactionResponse.proto

package com.identities.transactions.mutate;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_mutate_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_mutate_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nImodules/identities/internal/transactio" +
      "ns/mutate/transactionResponse.proto\022\036ide" +
      "ntities.transactions.mutate\"\025\n\023Transacti" +
      "onResponseB\250\002\n\"com.identities.transactio" +
      "ns.mutateB\030TransactionResponseProtoP\001ZNg" +
      "ithub.com/AssetMantle/modules/modules/id" +
      "entities/internal/transactions/mutate\242\002\003" +
      "ITM\252\002\036Identities.Transactions.Mutate\312\002\036I" +
      "dentities\\Transactions\\Mutate\342\002*Identiti" +
      "es\\Transactions\\Mutate\\GPBMetadata\352\002 Ide" +
      "ntities::Transactions::Mutateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_mutate_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_mutate_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_mutate_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
