// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/mutate/transactionResponse.proto

package com.identities.transactions.mutate;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.transactions.mutate.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
