// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/queries/identity/queryResponse.proto

package com.identities.queries.identity;

public final class QueryResponseProto {
  private QueryResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_queries_identity_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_queries_identity_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@modules/identities/internal/queries/id" +
      "entity/queryResponse.proto\022\033identities.q" +
      "ueries.identity\032\024gogoproto/gogo.proto\0323m" +
      "odules/identities/internal/mappable/mapp" +
      "able.proto\"o\n\rQueryResponse\022\030\n\007success\030\001" +
      " \001(\010R\007success\022\024\n\005error\030\002 \001(\tR\005error\022(\n\004l" +
      "ist\030\003 \003(\0132\024.identities.MappableR\004list:\004\210" +
      "\240\037\000B\220\002\n\037com.identities.queries.identityB" +
      "\022QueryResponseProtoP\001ZKgithub.com/AssetM" +
      "antle/modules/modules/identities/interna" +
      "l/queries/identity\242\002\003IQI\252\002\033Identities.Qu" +
      "eries.Identity\312\002\033Identities\\Queries\\Iden" +
      "tity\342\002\'Identities\\Queries\\Identity\\GPBMe" +
      "tadata\352\002\035Identities::Queries::Identityb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.identities.MappableProto.getDescriptor(),
        });
    internal_static_identities_queries_identity_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_queries_identity_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_queries_identity_QueryResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "List", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.identities.MappableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
