// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/queries/identity/queryRequest.proto

package com.identities.queries.identity;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_queries_identity_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_queries_identity_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?modules/identities/internal/queries/id" +
      "entity/queryRequest.proto\022\033identities.qu" +
      "eries.identity\032 schema/ids/base/identity" +
      "ID.proto\"A\n\014QueryRequest\0221\n\014identity_i_d" +
      "\030\001 \001(\0132\017.ids.IdentityIDR\nidentityIDB\217\002\n\037" +
      "com.identities.queries.identityB\021QueryRe" +
      "questProtoP\001ZKgithub.com/AssetMantle/mod" +
      "ules/modules/identities/internal/queries" +
      "/identity\242\002\003IQI\252\002\033Identities.Queries.Ide" +
      "ntity\312\002\033Identities\\Queries\\Identity\342\002\'Id" +
      "entities\\Queries\\Identity\\GPBMetadata\352\002\035" +
      "Identities::Queries::Identityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
        });
    internal_static_identities_queries_identity_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_queries_identity_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_queries_identity_QueryRequest_descriptor,
        new java.lang.String[] { "IdentityID", });
    com.ids.IdentityIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
