// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/queries/identity/service.proto

package com.identities.queries.identity;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:modules/identities/internal/queries/id" +
      "entity/service.proto\022\033identities.queries" +
      ".identity\032\034google/api/annotations.proto\032" +
      "?modules/identities/internal/queries/ide" +
      "ntity/queryRequest.proto\032@modules/identi" +
      "ties/internal/queries/identity/queryResp" +
      "onse.proto2\230\001\n\007Service\022\214\001\n\006Handle\022).iden" +
      "tities.queries.identity.QueryRequest\032*.i" +
      "dentities.queries.identity.QueryResponse" +
      "\"+\202\323\344\223\002%\022#/mantle/identities/v1beta1/ide" +
      "ntityB\212\002\n\037com.identities.queries.identit" +
      "yB\014ServiceProtoP\001ZKgithub.com/AssetMantl" +
      "e/modules/modules/identities/internal/qu" +
      "eries/identity\242\002\003IQI\252\002\033Identities.Querie" +
      "s.Identity\312\002\033Identities\\Queries\\Identity" +
      "\342\002\'Identities\\Queries\\Identity\\GPBMetada" +
      "ta\352\002\035Identities::Queries::Identityb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.queries.identity.QueryRequestProto.getDescriptor(),
          com.identities.queries.identity.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.queries.identity.QueryRequestProto.getDescriptor();
    com.identities.queries.identity.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
