// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/key/key.proto

package com.assets;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%modules/assets/internal/key/key.proto\022" +
      "\006assets\032\035schema/ids/base/assetID.proto\"/" +
      "\n\003Key\022(\n\tasset_i_d\030\001 \001(\0132\014.ids.AssetIDR\007" +
      "assetIDB\212\001\n\ncom.assetsB\010KeyProtoP\001Z:gith" +
      "ub.com/AssetMantle/modules/modules/asset" +
      "s/internal/key\242\002\003AXX\252\002\006Assets\312\002\006Assets\342\002" +
      "\022Assets\\GPBMetadata\352\002\006Assetsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.AssetIDProto.getDescriptor(),
        });
    internal_static_assets_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_Key_descriptor,
        new java.lang.String[] { "AssetID", });
    com.ids.AssetIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
