// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/nub/message.proto

package com.identities.transactions.nub;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_nub_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_nub_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:modules/identities/internal/transactio" +
      "ns/nub/message.proto\022\033identities.transac" +
      "tions.nub\032 schema/ids/base/identityID.pr" +
      "oto\032\036schema/ids/base/stringID.proto\"D\n\007M" +
      "essage\022\022\n\004from\030\001 \001(\tR\004from\022%\n\007nub_i_d\030\002 " +
      "\001(\0132\r.ids.StringIDR\005nubIDB\212\002\n\037com.identi" +
      "ties.transactions.nubB\014MessageProtoP\001ZKg" +
      "ithub.com/AssetMantle/modules/modules/id" +
      "entities/internal/transactions/nub\242\002\003ITN" +
      "\252\002\033Identities.Transactions.Nub\312\002\033Identit" +
      "ies\\Transactions\\Nub\342\002\'Identities\\Transa" +
      "ctions\\Nub\\GPBMetadata\352\002\035Identities::Tra" +
      "nsactions::Nubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.StringIDProto.getDescriptor(),
        });
    internal_static_identities_transactions_nub_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_nub_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_nub_Message_descriptor,
        new java.lang.String[] { "From", "NubID", });
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.StringIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
