// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/nub/service.proto

package com.identities.transactions.nub;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:modules/identities/internal/transactio" +
      "ns/nub/service.proto\022\033identities.transac" +
      "tions.nub\032\034google/api/annotations.proto\032" +
      ":modules/identities/internal/transaction" +
      "s/nub/message.proto\032Fmodules/identities/" +
      "internal/transactions/nub/transactionRes" +
      "ponse.proto2\214\001\n\007Service\022\200\001\n\006Handle\022$.ide" +
      "ntities.transactions.nub.Message\0320.ident" +
      "ities.transactions.nub.TransactionRespon" +
      "se\"\036\202\323\344\223\002\030\"\026/mantle/identities/nubB\212\002\n\037c" +
      "om.identities.transactions.nubB\014ServiceP" +
      "rotoP\001ZKgithub.com/AssetMantle/modules/m" +
      "odules/identities/internal/transactions/" +
      "nub\242\002\003ITN\252\002\033Identities.Transactions.Nub\312" +
      "\002\033Identities\\Transactions\\Nub\342\002\'Identiti" +
      "es\\Transactions\\Nub\\GPBMetadata\352\002\035Identi" +
      "ties::Transactions::Nubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.nub.MessageProto.getDescriptor(),
          com.identities.transactions.nub.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.nub.MessageProto.getDescriptor();
    com.identities.transactions.nub.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
