// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/nub/transactionResponse.proto

package com.identities.transactions.nub;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.transactions.nub.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nub_i_d = 1 [json_name = "nubID"];</code>
   * @return The nubID.
   */
  java.lang.String getNubID();
  /**
   * <code>string nub_i_d = 1 [json_name = "nubID"];</code>
   * @return The bytes for nubID.
   */
  com.google.protobuf.ByteString
      getNubIDBytes();
}
