// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/nub/transactionResponse.proto

package com.identities.transactions.nub;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_nub_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_nub_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nFmodules/identities/internal/transactio" +
      "ns/nub/transactionResponse.proto\022\033identi" +
      "ties.transactions.nub\"-\n\023TransactionResp" +
      "onse\022\026\n\007nub_i_d\030\001 \001(\tR\005nubIDB\226\002\n\037com.ide" +
      "ntities.transactions.nubB\030TransactionRes" +
      "ponseProtoP\001ZKgithub.com/AssetMantle/mod" +
      "ules/modules/identities/internal/transac" +
      "tions/nub\242\002\003ITN\252\002\033Identities.Transaction" +
      "s.Nub\312\002\033Identities\\Transactions\\Nub\342\002\'Id" +
      "entities\\Transactions\\Nub\\GPBMetadata\352\002\035" +
      "Identities::Transactions::Nubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_nub_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_nub_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_nub_TransactionResponse_descriptor,
        new java.lang.String[] { "NubID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
