// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/types/base/split.proto

package com.types;

public final class SplitProto {
  private SplitProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_Split_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_Split_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035schema/types/base/split.proto\022\005types\032 " +
      "schema/ids/base/identityID.proto\032\"schema" +
      "/ids/base/anyOwnableID.proto\032\024gogoproto/" +
      "gogo.proto\"\203\001\n\005Split\022+\n\towner_i_d\030\001 \001(\0132" +
      "\017.ids.IdentityIDR\007ownerID\0221\n\013ownable_i_d" +
      "\030\002 \001(\0132\021.ids.AnyOwnableIDR\townableID\022\024\n\005" +
      "value\030\003 \001(\tR\005value:\004\210\240\037\000B}\n\tcom.typesB\nS" +
      "plitProtoP\001Z0github.com/AssetMantle/modu" +
      "les/schema/types/base\242\002\003TXX\252\002\005Types\312\002\005Ty" +
      "pes\342\002\021Types\\GPBMetadata\352\002\005Typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_types_Split_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_Split_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_Split_descriptor,
        new java.lang.String[] { "OwnerID", "OwnableID", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
