// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/queries/classification/queryResponse.proto

package com.classifications.queries.classification;

public final class QueryResponseProto {
  private QueryResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classifications_queries_classification_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classifications_queries_classification_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nKmodules/classifications/internal/queri" +
      "es/classification/queryResponse.proto\022&c" +
      "lassifications.queries.classification\032\024g" +
      "ogoproto/gogo.proto\0328modules/classificat" +
      "ions/internal/mappable/mappable.proto\"t\n" +
      "\rQueryResponse\022\030\n\007success\030\001 \001(\010R\007success" +
      "\022\024\n\005error\030\002 \001(\tR\005error\022-\n\004list\030\003 \003(\0132\031.c" +
      "lassifications.MappableR\004list:\004\210\240\037\000B\322\002\n*" +
      "com.classifications.queries.classificati" +
      "onB\022QueryResponseProtoP\001ZVgithub.com/Ass" +
      "etMantle/modules/modules/classifications" +
      "/internal/queries/classification\242\002\003CQC\252\002" +
      "&Classifications.Queries.Classification\312" +
      "\002&Classifications\\Queries\\Classification" +
      "\342\0022Classifications\\Queries\\Classificatio" +
      "n\\GPBMetadata\352\002(Classifications::Queries" +
      "::Classificationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.classifications.MappableProto.getDescriptor(),
        });
    internal_static_classifications_queries_classification_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classifications_queries_classification_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classifications_queries_classification_QueryResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "List", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.classifications.MappableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
