// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/queries/classification/queryRequest.proto

package com.classifications.queries.classification;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classifications_queries_classification_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classifications_queries_classification_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJmodules/classifications/internal/queri" +
      "es/classification/queryRequest.proto\022&cl" +
      "assifications.queries.classification\032&sc" +
      "hema/ids/base/classificationID.proto\"S\n\014" +
      "QueryRequest\022C\n\022classification_i_d\030\001 \001(\013" +
      "2\025.ids.ClassificationIDR\020classificationI" +
      "DB\321\002\n*com.classifications.queries.classi" +
      "ficationB\021QueryRequestProtoP\001ZVgithub.co" +
      "m/AssetMantle/modules/modules/classifica" +
      "tions/internal/queries/classification\242\002\003" +
      "CQC\252\002&Classifications.Queries.Classifica" +
      "tion\312\002&Classifications\\Queries\\Classific" +
      "ation\342\0022Classifications\\Queries\\Classifi" +
      "cation\\GPBMetadata\352\002(Classifications::Qu" +
      "eries::Classificationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
        });
    internal_static_classifications_queries_classification_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classifications_queries_classification_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classifications_queries_classification_QueryRequest_descriptor,
        new java.lang.String[] { "ClassificationID", });
    com.ids.ClassificationIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
