// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/queries/classification/service.proto

package com.classifications.queries.classification;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEmodules/classifications/internal/queri" +
      "es/classification/service.proto\022&classif" +
      "ications.queries.classification\032\034google/" +
      "api/annotations.proto\032Jmodules/classific" +
      "ations/internal/queries/classification/q" +
      "ueryRequest.proto\032Kmodules/classificatio" +
      "ns/internal/queries/classification/query" +
      "Response.proto2\271\001\n\007Service\022\255\001\n\006Handle\0224." +
      "classifications.queries.classification.Q" +
      "ueryRequest\0325.classifications.queries.cl" +
      "assification.QueryResponse\"6\202\323\344\223\0020\022./man" +
      "tle/classifications/v1beta1/classificati" +
      "onB\314\002\n*com.classifications.queries.class" +
      "ificationB\014ServiceProtoP\001ZVgithub.com/As" +
      "setMantle/modules/modules/classification" +
      "s/internal/queries/classification\242\002\003CQC\252" +
      "\002&Classifications.Queries.Classification" +
      "\312\002&Classifications\\Queries\\Classificatio" +
      "n\342\0022Classifications\\Queries\\Classificati" +
      "on\\GPBMetadata\352\002(Classifications::Querie" +
      "s::Classificationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.classifications.queries.classification.QueryRequestProto.getDescriptor(),
          com.classifications.queries.classification.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.classifications.queries.classification.QueryRequestProto.getDescriptor();
    com.classifications.queries.classification.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
