// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/genesis/genesis.proto

package com.classifications;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classifications_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classifications_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6modules/classifications/internal/genes" +
      "is/genesis.proto\022\017classifications\032\024gogop" +
      "roto/gogo.proto\0328modules/classifications" +
      "/internal/mappable/mappable.proto\032*schem" +
      "a/parameters/base/parameterList.proto\"\211\001" +
      "\n\007Genesis\0227\n\tmappables\030\001 \003(\0132\031.classific" +
      "ations.MappableR\tmappables\022?\n\rparameterL" +
      "ist\030\002 \001(\0132\031.parameters.ParameterListR\rpa" +
      "rameterList:\004\210\240\037\000B\310\001\n\023com.classification" +
      "sB\014GenesisProtoP\001ZGgithub.com/AssetMantl" +
      "e/modules/modules/classifications/intern" +
      "al/genesis\242\002\003CXX\252\002\017Classifications\312\002\017Cla" +
      "ssifications\342\002\033Classifications\\GPBMetada" +
      "ta\352\002\017Classificationsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.classifications.MappableProto.getDescriptor(),
          com.parameters.ParameterListProto.getDescriptor(),
        });
    internal_static_classifications_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classifications_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classifications_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "ParameterList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.classifications.MappableProto.getDescriptor();
    com.parameters.ParameterListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
