// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/key/key.proto

package com.classifications;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classifications_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classifications_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.modules/classifications/internal/key/k" +
      "ey.proto\022\017classifications\032&schema/ids/ba" +
      "se/classificationID.proto\"J\n\003Key\022C\n\022clas" +
      "sification_i_d\030\001 \001(\0132\025.ids.Classificatio" +
      "nIDR\020classificationIDB\300\001\n\023com.classifica" +
      "tionsB\010KeyProtoP\001ZCgithub.com/AssetMantl" +
      "e/modules/modules/classifications/intern" +
      "al/key\242\002\003CXX\252\002\017Classifications\312\002\017Classif" +
      "ications\342\002\033Classifications\\GPBMetadata\352\002" +
      "\017Classificationsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDProto.getDescriptor(),
        });
    internal_static_classifications_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classifications_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classifications_Key_descriptor,
        new java.lang.String[] { "ClassificationID", });
    com.ids.ClassificationIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
