// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/mappable/mappable.proto

package com.classifications;

public final class MappableProto {
  private MappableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classifications_Mappable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classifications_Mappable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8modules/classifications/internal/mappa" +
      "ble/mappable.proto\022\017classifications\032$sch" +
      "ema/documents/base/document.proto\"G\n\010Map" +
      "pable\022;\n\016classification\030\001 \001(\0132\023.document" +
      "s.DocumentR\016classificationB\312\001\n\023com.class" +
      "ificationsB\rMappableProtoP\001ZHgithub.com/" +
      "AssetMantle/modules/modules/classificati" +
      "ons/internal/mappable\242\002\003CXX\252\002\017Classifica" +
      "tions\312\002\017Classifications\342\002\033Classification" +
      "s\\GPBMetadata\352\002\017Classificationsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.documents.DocumentProto.getDescriptor(),
        });
    internal_static_classifications_Mappable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classifications_Mappable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classifications_Mappable_descriptor,
        new java.lang.String[] { "Classification", });
    com.documents.DocumentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
