// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/ids/base/anyID.proto

package com.ids;

public final class AnyIDProto {
  private AnyIDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ids_AnyID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ids_AnyID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033schema/ids/base/anyID.proto\022\003ids\032\024gogo" +
      "proto/gogo.proto\032\"schema/ids/base/anyOwn" +
      "ableID.proto\032\035schema/ids/base/assetID.pr" +
      "oto\032&schema/ids/base/classificationID.pr" +
      "oto\032\034schema/ids/base/coinID.proto\032\034schem" +
      "a/ids/base/dataID.proto\032\034schema/ids/base" +
      "/hashID.proto\032 schema/ids/base/identityI" +
      "D.proto\032\"schema/ids/base/maintainerID.pr" +
      "oto\032\035schema/ids/base/orderID.proto\032 sche" +
      "ma/ids/base/propertyID.proto\032\035schema/ids" +
      "/base/splitID.proto\032\036schema/ids/base/str" +
      "ingID.proto\"\344\004\n\005AnyID\022*\n\tasset_i_d\030\001 \001(\013" +
      "2\014.ids.AssetIDH\000R\007assetID\022E\n\022classificat" +
      "ion_i_d\030\002 \001(\0132\025.ids.ClassificationIDH\000R\020" +
      "classificationID\022\'\n\010coin_i_d\030\003 \001(\0132\013.ids" +
      ".CoinIDH\000R\006coinID\022\'\n\010data_i_d\030\004 \001(\0132\013.id" +
      "s.DataIDH\000R\006dataID\022\'\n\010hash_i_d\030\005 \001(\0132\013.i" +
      "ds.HashIDH\000R\006hashID\0223\n\014identity_i_d\030\006 \001(" +
      "\0132\017.ids.IdentityIDH\000R\nidentityID\0229\n\016main" +
      "tainer_i_d\030\007 \001(\0132\021.ids.MaintainerIDH\000R\014m" +
      "aintainerID\022*\n\torder_i_d\030\010 \001(\0132\014.ids.Ord" +
      "erIDH\000R\007orderID\0223\n\013ownable_i_d\030\t \001(\0132\021.i" +
      "ds.AnyOwnableIDH\000R\townableID\0223\n\014property" +
      "_i_d\030\n \001(\0132\017.ids.PropertyIDH\000R\npropertyI" +
      "D\022*\n\tsplit_i_d\030\013 \001(\0132\014.ids.SplitIDH\000R\007sp" +
      "litID\022-\n\nstring_i_d\030\014 \001(\0132\r.ids.StringID" +
      "H\000R\010stringID:\004\210\240\037\000B\006\n\004implBq\n\007com.idsB\nA" +
      "nyIDProtoP\001Z.github.com/AssetMantle/modu" +
      "les/schema/ids/base\242\002\003IXX\252\002\003Ids\312\002\003Ids\342\002\017" +
      "Ids\\GPBMetadata\352\002\003Idsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
          com.ids.AssetIDProto.getDescriptor(),
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.CoinIDProto.getDescriptor(),
          com.ids.DataIDProto.getDescriptor(),
          com.ids.HashIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.MaintainerIDProto.getDescriptor(),
          com.ids.OrderIDProto.getDescriptor(),
          com.ids.PropertyIDProto.getDescriptor(),
          com.ids.SplitIDProto.getDescriptor(),
          com.ids.StringIDProto.getDescriptor(),
        });
    internal_static_ids_AnyID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ids_AnyID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ids_AnyID_descriptor,
        new java.lang.String[] { "AssetID", "ClassificationID", "CoinID", "DataID", "HashID", "IdentityID", "MaintainerID", "OrderID", "OwnableID", "PropertyID", "SplitID", "StringID", "Impl", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
    com.ids.AssetIDProto.getDescriptor();
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.CoinIDProto.getDescriptor();
    com.ids.DataIDProto.getDescriptor();
    com.ids.HashIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.MaintainerIDProto.getDescriptor();
    com.ids.OrderIDProto.getDescriptor();
    com.ids.PropertyIDProto.getDescriptor();
    com.ids.SplitIDProto.getDescriptor();
    com.ids.StringIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
