// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/ids/base/dataID.proto

package com.ids;

public final class DataIDProto {
  private DataIDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ids_DataID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ids_DataID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034schema/ids/base/dataID.proto\022\003ids\032\034sch" +
      "ema/ids/base/hashID.proto\032\036schema/ids/ba" +
      "se/stringID.proto\032\024gogoproto/gogo.proto\"" +
      "^\n\006DataID\022\'\n\010type_i_d\030\001 \001(\0132\r.ids.String" +
      "IDR\006typeID\022%\n\010hash_i_d\030\002 \001(\0132\013.ids.HashI" +
      "DR\006hashID:\004\210\240\037\000Br\n\007com.idsB\013DataIDProtoP" +
      "\001Z.github.com/AssetMantle/modules/schema" +
      "/ids/base\242\002\003IXX\252\002\003Ids\312\002\003Ids\342\002\017Ids\\GPBMet" +
      "adata\352\002\003Idsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.HashIDProto.getDescriptor(),
          com.ids.StringIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_ids_DataID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ids_DataID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ids_DataID_descriptor,
        new java.lang.String[] { "TypeID", "HashID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.HashIDProto.getDescriptor();
    com.ids.StringIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
