// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/ids/base/identityID.proto

package com.ids;

public final class IdentityIDProto {
  private IdentityIDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ids_IdentityID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ids_IdentityID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n schema/ids/base/identityID.proto\022\003ids\032" +
      "\024gogoproto/gogo.proto\032\034schema/ids/base/h" +
      "ashID.proto\"9\n\nIdentityID\022%\n\010hash_i_d\030\001 " +
      "\001(\0132\013.ids.HashIDR\006hashID:\004\210\240\037\000Bv\n\007com.id" +
      "sB\017IdentityIDProtoP\001Z.github.com/AssetMa" +
      "ntle/modules/schema/ids/base\242\002\003IXX\252\002\003Ids" +
      "\312\002\003Ids\342\002\017Ids\\GPBMetadata\352\002\003Idsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.HashIDProto.getDescriptor(),
        });
    internal_static_ids_IdentityID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ids_IdentityID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ids_IdentityID_descriptor,
        new java.lang.String[] { "HashID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.HashIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
