// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/ids/base/maintainerID.proto

package com.ids;

public final class MaintainerIDProto {
  private MaintainerIDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ids_MaintainerID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ids_MaintainerID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"schema/ids/base/maintainerID.proto\022\003id" +
      "s\032\034schema/ids/base/hashID.proto\032\024gogopro" +
      "to/gogo.proto\";\n\014MaintainerID\022%\n\010hash_i_" +
      "d\030\001 \001(\0132\013.ids.HashIDR\006hashID:\004\210\240\037\000Bx\n\007co" +
      "m.idsB\021MaintainerIDProtoP\001Z.github.com/A" +
      "ssetMantle/modules/schema/ids/base\242\002\003IXX" +
      "\252\002\003Ids\312\002\003Ids\342\002\017Ids\\GPBMetadata\352\002\003Idsb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.HashIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_ids_MaintainerID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ids_MaintainerID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ids_MaintainerID_descriptor,
        new java.lang.String[] { "HashID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.HashIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
