// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/ids/base/propertyID.proto

package com.ids;

public final class PropertyIDProto {
  private PropertyIDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ids_PropertyID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ids_PropertyID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n schema/ids/base/propertyID.proto\022\003ids\032" +
      "\036schema/ids/base/stringID.proto\032\024gogopro" +
      "to/gogo.proto\"b\n\nPropertyID\022%\n\007key_i_d\030\001" +
      " \001(\0132\r.ids.StringIDR\005keyID\022\'\n\010type_i_d\030\002" +
      " \001(\0132\r.ids.StringIDR\006typeID:\004\210\240\037\000Bv\n\007com" +
      ".idsB\017PropertyIDProtoP\001Z.github.com/Asse" +
      "tMantle/modules/schema/ids/base\242\002\003IXX\252\002\003" +
      "Ids\312\002\003Ids\342\002\017Ids\\GPBMetadata\352\002\003Idsb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.StringIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_ids_PropertyID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ids_PropertyID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ids_PropertyID_descriptor,
        new java.lang.String[] { "KeyID", "TypeID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.StringIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
