// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/ids/base/splitID.proto

package com.ids;

public final class SplitIDProto {
  private SplitIDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ids_SplitID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ids_SplitID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035schema/ids/base/splitID.proto\022\003ids\032 sc" +
      "hema/ids/base/identityID.proto\032\"schema/i" +
      "ds/base/anyOwnableID.proto\032\024gogoproto/go" +
      "go.proto\"o\n\007SplitID\022+\n\towner_i_d\030\001 \001(\0132\017" +
      ".ids.IdentityIDR\007ownerID\0221\n\013ownable_i_d\030" +
      "\002 \001(\0132\021.ids.AnyOwnableIDR\townableID:\004\210\240\037" +
      "\000Bs\n\007com.idsB\014SplitIDProtoP\001Z.github.com" +
      "/AssetMantle/modules/schema/ids/base\242\002\003I" +
      "XX\252\002\003Ids\312\002\003Ids\342\002\017Ids\\GPBMetadata\352\002\003Idsb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_ids_SplitID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ids_SplitID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ids_SplitID_descriptor,
        new java.lang.String[] { "OwnerID", "OwnableID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
