// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/queries/meta/queryRequest.proto

package com.metas.queries.meta;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metas_queries_meta_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metas_queries_meta_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6modules/metas/internal/queries/meta/qu" +
      "eryRequest.proto\022\022metas.queries.meta\032\034sc" +
      "hema/ids/base/dataID.proto\032\024gogoproto/go" +
      "go.proto\";\n\014QueryRequest\022%\n\010data_i_d\030\001 \001" +
      "(\0132\013.ids.DataIDR\006dataID:\004\210\240\037\000B\331\001\n\026com.me" +
      "tas.queries.metaB\021QueryRequestProtoP\001ZBg" +
      "ithub.com/AssetMantle/modules/modules/me" +
      "tas/internal/queries/meta\242\002\003MQM\252\002\022Metas." +
      "Queries.Meta\312\002\022Metas\\Queries\\Meta\342\002\036Meta" +
      "s\\Queries\\Meta\\GPBMetadata\352\002\024Metas::Quer" +
      "ies::Metab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.DataIDProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_metas_queries_meta_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metas_queries_meta_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metas_queries_meta_QueryRequest_descriptor,
        new java.lang.String[] { "DataID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ids.DataIDProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
