// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/queries/meta/service.proto

package com.metas.queries.meta;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1modules/metas/internal/queries/meta/se" +
      "rvice.proto\022\022metas.queries.meta\032\034google/" +
      "api/annotations.proto\0326modules/metas/int" +
      "ernal/queries/meta/queryRequest.proto\0327m" +
      "odules/metas/internal/queries/meta/query" +
      "Response.proto2|\n\007Service\022q\n\006Handle\022 .me" +
      "tas.queries.meta.QueryRequest\032!.metas.qu" +
      "eries.meta.QueryResponse\"\"\202\323\344\223\002\034\022\032/mantl" +
      "e/metas/v1beta1/metaB\324\001\n\026com.metas.queri" +
      "es.metaB\014ServiceProtoP\001ZBgithub.com/Asse" +
      "tMantle/modules/modules/metas/internal/q" +
      "ueries/meta\242\002\003MQM\252\002\022Metas.Queries.Meta\312\002" +
      "\022Metas\\Queries\\Meta\342\002\036Metas\\Queries\\Meta" +
      "\\GPBMetadata\352\002\024Metas::Queries::Metab\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.metas.queries.meta.QueryRequestProto.getDescriptor(),
          com.metas.queries.meta.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.metas.queries.meta.QueryRequestProto.getDescriptor();
    com.metas.queries.meta.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
