// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/genesis/genesis.proto

package com.maintainers;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maintainers_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maintainers_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2modules/maintainers/internal/genesis/g" +
      "enesis.proto\022\013maintainers\032\024gogoproto/gog" +
      "o.proto\0324modules/maintainers/internal/ma" +
      "ppable/mappable.proto\032*schema/parameters" +
      "/base/parameterList.proto\"\205\001\n\007Genesis\0223\n" +
      "\tmappables\030\001 \003(\0132\025.maintainers.MappableR" +
      "\tmappables\022?\n\rparameterList\030\002 \001(\0132\031.para" +
      "meters.ParameterListR\rparameterList:\004\210\240\037" +
      "\000B\260\001\n\017com.maintainersB\014GenesisProtoP\001ZCg" +
      "ithub.com/AssetMantle/modules/modules/ma" +
      "intainers/internal/genesis\242\002\003MXX\252\002\013Maint" +
      "ainers\312\002\013Maintainers\342\002\027Maintainers\\GPBMe" +
      "tadata\352\002\013Maintainersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.maintainers.MappableProto.getDescriptor(),
          com.parameters.ParameterListProto.getDescriptor(),
        });
    internal_static_maintainers_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maintainers_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maintainers_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "ParameterList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.maintainers.MappableProto.getDescriptor();
    com.parameters.ParameterListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
