// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/key/key.proto

package com.maintainers;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maintainers_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maintainers_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*modules/maintainers/internal/key/key.p" +
      "roto\022\013maintainers\032\"schema/ids/base/maint" +
      "ainerID.proto\">\n\003Key\0227\n\016maintainer_i_d\030\001" +
      " \001(\0132\021.ids.MaintainerIDR\014maintainerIDB\250\001" +
      "\n\017com.maintainersB\010KeyProtoP\001Z?github.co" +
      "m/AssetMantle/modules/modules/maintainer" +
      "s/internal/key\242\002\003MXX\252\002\013Maintainers\312\002\013Mai" +
      "ntainers\342\002\027Maintainers\\GPBMetadata\352\002\013Mai" +
      "ntainersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.MaintainerIDProto.getDescriptor(),
        });
    internal_static_maintainers_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maintainers_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maintainers_Key_descriptor,
        new java.lang.String[] { "MaintainerID", });
    com.ids.MaintainerIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
