// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/mappable/mappable.proto

package com.maintainers;

public final class MappableProto {
  private MappableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maintainers_Mappable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maintainers_Mappable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4modules/maintainers/internal/mappable/" +
      "mappable.proto\022\013maintainers\032$schema/docu" +
      "ments/base/document.proto\"?\n\010Mappable\0223\n" +
      "\nmaintainer\030\001 \001(\0132\023.documents.DocumentR\n" +
      "maintainerB\262\001\n\017com.maintainersB\rMappable" +
      "ProtoP\001ZDgithub.com/AssetMantle/modules/" +
      "modules/maintainers/internal/mappable\242\002\003" +
      "MXX\252\002\013Maintainers\312\002\013Maintainers\342\002\027Mainta" +
      "iners\\GPBMetadata\352\002\013Maintainersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.documents.DocumentProto.getDescriptor(),
        });
    internal_static_maintainers_Mappable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maintainers_Mappable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maintainers_Mappable_descriptor,
        new java.lang.String[] { "Maintainer", });
    com.documents.DocumentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
