// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/immediate/message.proto

package com.orders.transactions.immediate;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_immediate_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_immediate_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<modules/orders/internal/transactions/i" +
      "mmediate/message.proto\022\035orders.transacti" +
      "ons.immediate\032\024gogoproto/gogo.proto\032&sch" +
      "ema/ids/base/classificationID.proto\032 sch" +
      "ema/ids/base/identityID.proto\032\"schema/id" +
      "s/base/anyOwnableID.proto\032$schema/lists/" +
      "base/propertyList.proto\032\036schema/types/ba" +
      "se/height.proto\"\356\005\n\007Message\022\022\n\004from\030\001 \001(" +
      "\tR\004from\022)\n\010from_i_d\030\002 \001(\0132\017.ids.Identity" +
      "IDR\006fromID\022C\n\022classification_i_d\030\003 \001(\0132\025" +
      ".ids.ClassificationIDR\020classificationID\022" +
      "+\n\ttaker_i_d\030\004 \001(\0132\017.ids.IdentityIDR\007tak" +
      "erID\022<\n\021maker_ownable_i_d\030\005 \001(\0132\021.ids.An" +
      "yOwnableIDR\016makerOwnableID\022<\n\021taker_owna" +
      "ble_i_d\030\006 \001(\0132\021.ids.AnyOwnableIDR\016takerO" +
      "wnableID\022,\n\nexpires_in\030\007 \001(\0132\r.types.Hei" +
      "ghtR\texpiresIn\022.\n\023maker_ownable_split\030\010 " +
      "\001(\tR\021makerOwnableSplit\022.\n\023taker_ownable_" +
      "split\030\t \001(\tR\021takerOwnableSplit\022O\n\031immuta" +
      "ble_meta_properties\030\n \001(\0132\023.lists.Proper" +
      "tyListR\027immutableMetaProperties\022F\n\024immut" +
      "able_properties\030\013 \001(\0132\023.lists.PropertyLi" +
      "stR\023immutableProperties\022K\n\027mutable_meta_" +
      "properties\030\014 \001(\0132\023.lists.PropertyListR\025m" +
      "utableMetaProperties\022B\n\022mutable_properti" +
      "es\030\r \001(\0132\023.lists.PropertyListR\021mutablePr" +
      "opertiesB\226\002\n!com.orders.transactions.imm" +
      "ediateB\014MessageProtoP\001ZMgithub.com/Asset" +
      "Mantle/modules/modules/orders/internal/t" +
      "ransactions/immediate\242\002\003OTI\252\002\035Orders.Tra" +
      "nsactions.Immediate\312\002\035Orders\\Transaction" +
      "s\\Immediate\342\002)Orders\\Transactions\\Immedi" +
      "ate\\GPBMetadata\352\002\037Orders::Transactions::" +
      "Immediateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.ClassificationIDProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
          com.lists.PropertyListProto.getDescriptor(),
          com.types.HeightProto.getDescriptor(),
        });
    internal_static_orders_transactions_immediate_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_immediate_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_immediate_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ClassificationID", "TakerID", "MakerOwnableID", "TakerOwnableID", "ExpiresIn", "MakerOwnableSplit", "TakerOwnableSplit", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.ClassificationIDProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
    com.lists.PropertyListProto.getDescriptor();
    com.types.HeightProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
