// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/immediate/service.proto

package com.orders.transactions.immediate;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<modules/orders/internal/transactions/i" +
      "mmediate/service.proto\022\035orders.transacti" +
      "ons.immediate\032\034google/api/annotations.pr" +
      "oto\032<modules/orders/internal/transaction" +
      "s/immediate/message.proto\032Hmodules/order" +
      "s/internal/transactions/immediate/transa" +
      "ctionResponse.proto2\222\001\n\007Service\022\206\001\n\006Hand" +
      "le\022&.orders.transactions.immediate.Messa" +
      "ge\0322.orders.transactions.immediate.Trans" +
      "actionResponse\" \202\323\344\223\002\032\"\030/mantle/orders/i" +
      "mmediateB\226\002\n!com.orders.transactions.imm" +
      "ediateB\014ServiceProtoP\001ZMgithub.com/Asset" +
      "Mantle/modules/modules/orders/internal/t" +
      "ransactions/immediate\242\002\003OTI\252\002\035Orders.Tra" +
      "nsactions.Immediate\312\002\035Orders\\Transaction" +
      "s\\Immediate\342\002)Orders\\Transactions\\Immedi" +
      "ate\\GPBMetadata\352\002\037Orders::Transactions::" +
      "Immediateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.orders.transactions.immediate.MessageProto.getDescriptor(),
          com.orders.transactions.immediate.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.orders.transactions.immediate.MessageProto.getDescriptor();
    com.orders.transactions.immediate.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
