// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/immediate/transactionResponse.proto

package com.orders.transactions.immediate;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_immediate_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_immediate_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHmodules/orders/internal/transactions/i" +
      "mmediate/transactionResponse.proto\022\035orde" +
      "rs.transactions.immediate\"\025\n\023Transaction" +
      "ResponseB\242\002\n!com.orders.transactions.imm" +
      "ediateB\030TransactionResponseProtoP\001ZMgith" +
      "ub.com/AssetMantle/modules/modules/order" +
      "s/internal/transactions/immediate\242\002\003OTI\252" +
      "\002\035Orders.Transactions.Immediate\312\002\035Orders" +
      "\\Transactions\\Immediate\342\002)Orders\\Transac" +
      "tions\\Immediate\\GPBMetadata\352\002\037Orders::Tr" +
      "ansactions::Immediateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_immediate_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_immediate_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_immediate_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
