// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/immediate/transactionResponse.proto

package com.orders.transactions.immediate;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.transactions.immediate.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
