name:  Build Comdex
on:
  pull_request:
    branches:
      - comdex/development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SBT action test
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: dist
