name: Comdex Development

on:
  push:
    branches: [comdex/development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Operations
        uses: alinz/ssh-scp-action@master
        with:
          key: ${{ secrets.COMDEX_DEVELOP_SSH_KEY }}
          host: ${{ secrets.COMDEX_DEVELOP_HOST }}
          port: 22
          user: ${{ secrets.COMDEX_DEVELOP_USERNAME }}
          # then run these commands
          ssh_after: |
            ${{ secrets.COMDEX_DEVELOP_SCRIPT_PATH }}