name: Explorer - Staging 

on:
  push:
    tags:         
      - 'explorer-**-rc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: Compile
        run: sbt dist
      - uses: actions/upload-artifact@v2
        with:
          name: client.zip
          path: target/universal/persistenceclient-1.0.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: client.zip
          path: target/universal/persistenceclient-1.0.zip
      - name: Operations
        uses: alinz/ssh-scp-action@master
        with:
          key: ${{ secrets.EXPLORER_STAGING_SSH_KEY }}
          host: ${{ secrets.EXPLORER_STAGING_HOST }}
          port: 22
          user: ${{ secrets.EXPLORER_STAGING_USERNAME }}
          ssh_before: |
            rm -r explorer.zip
          scp: |
           target/universal/persistenceclient-1.0.zip ${{ secrets.EXPLORER_STAGING_USERNAME }}@${{ secrets.EXPLORER_STAGING_HOST }}:~/explorer.zip
          # then run these commands
          ssh_after: |
            ${{ secrets.EXPLORER_STAGING_SCRIPT }}

