name: Peristence

on:
  push:
    branches: [action-service]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SBT action test
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: dist
          sbt_project_directory: ./build
