// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/send/message.proto

package com.splits.transactions.send;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_send_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_send_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/splits/internal/transactions/s" +
      "end/message.proto\022\030splits.transactions.s" +
      "end\032\024gogoproto/gogo.proto\032 schema/ids/ba" +
      "se/identityID.proto\032\"schema/ids/base/any" +
      "OwnableID.proto\"\270\001\n\007Message\022\022\n\004from\030\001 \001(" +
      "\tR\004from\022)\n\010from_i_d\030\002 \001(\0132\017.ids.Identity" +
      "IDR\006fromID\022%\n\006to_i_d\030\003 \001(\0132\017.ids.Identit" +
      "yIDR\004toID\0221\n\013ownable_i_d\030\004 \001(\0132\021.ids.Any" +
      "OwnableIDR\townableID\022\024\n\005value\030\005 \001(\tR\005val" +
      "ueB\370\001\n\034com.splits.transactions.sendB\014Mes" +
      "sageProtoP\001ZHgithub.com/AssetMantle/modu" +
      "les/modules/splits/internal/transactions" +
      "/send\242\002\003STS\252\002\030Splits.Transactions.Send\312\002" +
      "\030Splits\\Transactions\\Send\342\002$Splits\\Trans" +
      "actions\\Send\\GPBMetadata\352\002\032Splits::Trans" +
      "actions::Sendb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.IdentityIDProto.getDescriptor(),
          com.ids.AnyOwnableIDProto.getDescriptor(),
        });
    internal_static_splits_transactions_send_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_send_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_send_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "OwnableID", "Value", });
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.IdentityIDProto.getDescriptor();
    com.ids.AnyOwnableIDProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
