// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/send/service.proto

package com.splits.transactions.send;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7modules/splits/internal/transactions/s" +
      "end/service.proto\022\030splits.transactions.s" +
      "end\032\034google/api/annotations.proto\0327modul" +
      "es/splits/internal/transactions/send/mes" +
      "sage.proto\032Cmodules/splits/internal/tran" +
      "sactions/send/transactionResponse.proto2" +
      "\202\001\n\007Service\022w\n\006Handle\022!.splits.transacti" +
      "ons.send.Message\032-.splits.transactions.s" +
      "end.TransactionResponse\"\033\202\323\344\223\002\025\"\023/mantle" +
      "/splits/sendB\370\001\n\034com.splits.transactions" +
      ".sendB\014ServiceProtoP\001ZHgithub.com/AssetM" +
      "antle/modules/modules/splits/internal/tr" +
      "ansactions/send\242\002\003STS\252\002\030Splits.Transacti" +
      "ons.Send\312\002\030Splits\\Transactions\\Send\342\002$Sp" +
      "lits\\Transactions\\Send\\GPBMetadata\352\002\032Spl" +
      "its::Transactions::Sendb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.splits.transactions.send.MessageProto.getDescriptor(),
          com.splits.transactions.send.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.splits.transactions.send.MessageProto.getDescriptor();
    com.splits.transactions.send.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
