// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/send/transactionResponse.proto

package com.splits.transactions.send;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_send_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_send_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCmodules/splits/internal/transactions/s" +
      "end/transactionResponse.proto\022\030splits.tr" +
      "ansactions.send\"\025\n\023TransactionResponseB\204" +
      "\002\n\034com.splits.transactions.sendB\030Transac" +
      "tionResponseProtoP\001ZHgithub.com/AssetMan" +
      "tle/modules/modules/splits/internal/tran" +
      "sactions/send\242\002\003STS\252\002\030Splits.Transaction" +
      "s.Send\312\002\030Splits\\Transactions\\Send\342\002$Spli" +
      "ts\\Transactions\\Send\\GPBMetadata\352\002\032Split" +
      "s::Transactions::Sendb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_splits_transactions_send_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_send_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_send_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
